import { describe, expect, it } from 'vitest';
import { appwriteCollectionReadData, appwriteCollectionWriteData } from '../src/backend/appwriteCollectionTransforms.js';

const stored = (value: Record<string, unknown>) => ({ id: 'row-1', agencyId: 'agency-1', version: 1, createdAt: '2026-09-15T00:00:00.000Z', updatedAt: '2026-09-15T00:00:00.000Z', ...value }) as never;

describe('Appwrite presentation and worker collection contracts', () => {
  it('serializes dashboard metrics into the canonical snapshot table', () => { const written = appwriteCollectionWriteData('dashboardMetricSnapshots', { agencyId: 'agency-1', capturedAt: '2026-09-15T01:00:00.000Z', metrics: { open: 4 } }); expect(written.timezone).toBe('Australia/Perth'); expect(JSON.parse(String(written.metrics))).toEqual({ open: 4 }); expect(appwriteCollectionReadData('dashboardMetricSnapshots', stored(written)).metrics).toEqual({ open: 4 }); });
  it('maps API PDF jobs to worker job identity and Appwrite artifact locations', () => { const written = appwriteCollectionWriteData('pdfJobs', { id: 'task-1', agencyId: 'agency-1', reportId: 'report-1', reportVersionId: 'version-1', status: 'queued', priority: 'high', requestedBy: 'user-1' }); expect(written.taskId).toBe('task-1'); expect(written.priority).toBe('high'); const read = appwriteCollectionReadData('pdfJobs', stored({ ...written, pdfFileId: 'file-1', manifestId: 'manifest-1', manifestSha256: 'a'.repeat(64) })); expect(read.pdfObjectPath).toBe('appwrite://reports/file-1'); expect(read.renderManifestObjectPath).toBe('appwrite-table://report_render_manifests/manifest-1'); expect(read.pdfGeneration).toBe('appwrite-v1'); });
  it('round-trips report presentation template payloads without flattening nested policy', () => { const input = { id: 'presentation-1', agencyId: 'agency-1', status: 'draft', name: 'Detailed', supportedInspectionTypes: ['entry'], page: { size: 'A4', marginMm: 12, showPageNumbers: true, showRunningHeader: true }, typography: { headingFont: 'Helvetica', bodyFont: 'Helvetica', baseFontSizePt: 9 }, cover: { style: 'corporate', showHeroPhoto: true, showClientName: true, showInspectorName: true }, sections: [{ id: 'cover', type: 'cover', visible: true }] }; const written = appwriteCollectionWriteData('reportPresentationTemplateVersions', input); expect(typeof written.payload).toBe('string'); const read = appwriteCollectionReadData('reportPresentationTemplateVersions', stored({ ...written, status: 'draft' })); expect(read.name).toBe('Detailed'); expect(read.page).toEqual(input.page); expect(read.sections).toEqual(input.sections); });
  it('round-trips versioned report branding payloads', () => { const input = { id: 'branding-1', agencyId: 'agency-1', status: 'draft', agencyName: 'ProInspect', primaryColour: '#1D4ED8', secondaryColour: '#0F172A', accentColour: '#0284C7', headingFont: 'Helvetica', bodyFont: 'Helvetica' }; const written = appwriteCollectionWriteData('reportBrandingProfileVersions', input); const read = appwriteCollectionReadData('reportBrandingProfileVersions', stored({ ...written, status: 'draft' })); expect(read.agencyName).toBe('ProInspect'); expect(read.primaryColour).toBe('#1D4ED8'); });
});
