import { manifest } from './runtime.mjs';
const focus={
  recovery:'Exercise the shipped encrypted backup and isolated database/file restore. Add measured recovery objectives, scheduled backups and restore access controls.',
  identity:'Extend real Appwrite personas, MFA challenge/recovery, owner versus tenant, council, expired Relief access, stale occupancy and assignment denial. Revoke all test sessions in finally blocks.',
  transactions:'Complete atomic Appwrite quotes/approval/work-order, report release/supersession, incidents/follow-up, controlled keys, contractor completion, privileged changes and service intake. Include idempotency, optimistic conflicts, audit and transactional outbox. Inject failures between writes.',
  'admin-client':'Complete site/service/entitlement administration, client user controls, property scoping, uploads/downloads, booking/rescheduling, approvals, settings provenance and accurate dashboards.',
  'inspection-reports':'Complete all five report workflows, baseline comparisons, exact issued versions, evidence transfer, human review, reproducible PDFs and immutability. Preserve source findings and never automate liability.',
  'building-strata':'Complete diary, tasks, triage and duplicate handling, defects and work orders, operational checkpoints, moves/devices/keys, assets/service generation, waste/inventory, restricted incidents, by-law decisions, notices, monthly reporting and relief handover. Require persisted evidence and approval authority.',
  'resident-contractor':'Complete household and occupancy onboarding, requests/documents/notices, signing and remote inspection, contractor-company scopes, quotes, attendance, key return, evidence, completion verification, insurance/licence expiry blocking and notifications.',
  offers:'Complete partner administration, audience eligibility, dates, redemption quotas and concurrency, history and privacy-safe handoff. Do not silently defer this full-product requirement.',
  offline:'Finish durable drafts, evidence queues, encryption/key recovery, session expiry, browser restart, conflict resolution, replay deduplication and safe PWA updates. Remove runtime CDN styling dependence; compile/bundle assets. Include real iPhone/Android camera procedures, not browser emulation claims.',
  migration:'Use the existing 49-table Strata manifest and migration framework to produce approved normalized bundles. Provide actual D1/Firestore export/transform, explicit omit rules, source reconciliation, parent maps, deterministic IDs and final delta. Never copy credentials. Test the shipped importer and own-record rollback.',
  files:'Provide complete R2/Firebase inventory and binary acquisition to the normalized bundle. Check every hash, orphan, entitlement, legal hold and retained source. Large files need a reviewed streaming path.',
  'commerce-calendar':'Complete generic service routing, Shopify authentic/invalid HMAC, duplicate effects, paid/cancel/refund/multiline cases and integration exceptions. Test Calendar OAuth/watch renewal, capacity, reschedule/cancel and Perth timezone using a dedicated calendar. Do not switch live Shopify webhooks or refund real orders.',
  workers:'Complete actual Appwrite adapters in API, AI, PDF, document, notification, dashboard and integration paths. The existing deployment has six Cloud Run services; inspect where AI executes before adding a seventh. Process real synthetic tasks, verify digests, retries/deadletters, no Firestore writeback and participant-isolated notifications.',
  operations:'Implement and trigger auth/API/worker/webhook/upload/queue alerts, credential rotation/expiry alerts, budgets/load testing, approved retention/privacy, support ownership and incident drills. Reconcile backup schedules with recovery policy.',
  rehearsal:'Run the same candidate through isolated Staging, source freeze, migration/final delta, all personas, data/file restoration, edge and worker rollback, post-rollback consistency and named release sign-off. Preserve legacy sources.',
  appwrite:'Exercise shipped additive schema operations, approved runtime keys, temporary-key cleanup, teams and registered origins. No schema destruction, public ACLs or broad credentials.',
};
export function workpack(id,config,context){const gate=manifest.gates.find((g)=>g.id===id);if(!gate)throw new Error('Unknown workstream');return `# Complete ProInspect: ${gate.title}\n\nCandidate: ${context.commit}\nTarget: ${context.environment}\n\n${focus[id] ?? 'Repair the source/build, not the acceptance threshold.'}\n\nRead existing implementation, platform-completion-v1, docs/migrations/strata-feature-parity.json, docs/deployment/unified-platform-readiness.md and the current launch package before editing.\n\nRequired acceptance assertions:\n${gate.checks.map((c)=>`- ${c}`).join('\n')}\n\nDeliver actual application changes, focused regression tests, and a committed live acceptance adapter at infrastructure/launch-adapters/${id}.mjs using adapter-sdk.mjs. Perform real operations before recording observations. Supply synthetic fixtures and clean only your own test data. Include failure, concurrent and denial cases. No always-green stubs, skip counts or copied PASS receipts.\n\nThis invocation is SOURCE ENGINEERING ONLY. Do not deploy, access Production, alter webhooks, rotate credentials, send real notifications or execute migrations. Do not edit the launch package, gate definitions, recorded evidence, existing installer safety checks or test thresholds. Do not remove tests. Do not read or print secrets. Preserve unrelated source. Run focused tests and npm run check. Leave changes uncommitted and list remaining defects/inputs. Device and live acceptance run separately after review.\n\nConfigured non-secret target: ${JSON.stringify(config.environments[context.environment])}\n`;}
