import type { InspectionTypeTemplate, TemplateArea } from './index.js';

const component = (id: string, name: string, required = false, photoRequired = false) => ({ id, name, required, photoRequired });

export const pcrStandardAreas: TemplateArea[] = [
  {
    id: 'exterior-front',
    name: 'Exterior Front',
    components: [
      component('overall-presentation', 'Overall Presentation', true, true),
      component('doorbell', 'Doorbell'),
      component('porch-ceiling-cornices', 'Porch Ceiling / Cornices'),
      component('external-walls', 'External Walls', true, true),
      component('eaves', 'Eaves'),
      component('porch-floor-paving', 'Floor / Porch / Paving', true, true),
      component('fence-gate', 'Fence / Gate'),
      component('light-fittings', 'Light Fittings'),
      component('garden-lawn', 'Garden / Lawn'),
      component('gutters-downpipes-fascia', 'Gutters / Downpipes / Fascia'),
      component('driveway', 'Driveway'),
      component('meter-box', 'Meter Box'),
      component('letterbox-street-number', 'Letterbox / Street Number'),
      component('bins', 'Bins'),
      component('nbn-telstra-box', 'NBN / Telstra Box'),
    ],
  },
  {
    id: 'exterior-back',
    name: 'Exterior Back',
    components: [
      component('patio-alfresco-ceiling', 'Patio / Alfresco Ceiling'),
      component('external-walls', 'External Walls', true, true),
      component('floor-paving-concrete', 'Floor / Paving / Concrete', true, true),
      component('fence-gate', 'Fence / Gate'),
      component('garden-lawn', 'Garden / Lawn'),
      component('clothesline', 'Clothesline'),
      component('hot-water-system', 'Hot Water System'),
      component('air-conditioning-motor', 'Air-Conditioning Motor'),
    ],
  },
  {
    id: 'garage-carport',
    name: 'Garage / Carport',
    components: [
      component('door-to-house', 'Door to House'),
      component('garage-roller-door', 'Garage Roller Door', true, true),
      component('garage-door-motor', 'Garage Door Motor'),
      component('ceiling-cornices', 'Ceiling / Cornices'),
      component('walls', 'Walls'),
      component('light-fittings', 'Light Fittings'),
      component('points-switches', 'Points and Switches'),
      component('floor', 'Floor', true, true),
      component('shelving-storage', 'Shelving / Storage'),
    ],
  },
  {
    id: 'entry',
    name: 'Entry',
    components: [
      component('front-door', 'Front Door', true, true),
      component('security-screen-door', 'Security Screen Door'),
      component('doorway-frames', 'Doorway Frames', true),
      component('door-handles-locks', 'Door Handles / Locks', true),
      component('ceiling-cornices', 'Ceiling / Cornices', true),
      component('walls', 'Walls', true, true),
      component('light-fittings', 'Light Fittings'),
      component('points-switches', 'Points and Switches'),
      component('floor-floorcoverings', 'Floor / Floorcoverings', true, true),
      component('skirting', 'Skirting'),
      component('smoke-alarm', 'Smoke Alarm'),
    ],
  },
  ...['Lounge Room', 'Family Room', 'Dining Room', 'Lounge / Dining Room'].map((name) => ({
    id: name.toLowerCase().replaceAll(' / ', '-').replaceAll(' ', '-'),
    name,
    components: [
      component('doors-doorway-frames', 'Doors / Doorway Frames'),
      component('ceiling-cornices', 'Ceiling / Cornices', true),
      component('walls', 'Walls', true, true),
      component('air-conditioner', 'Air Conditioner'),
      component('ceiling-fan', 'Ceiling Fan'),
      component('light-fittings', 'Light Fittings'),
      component('points-switches', 'Points and Switches'),
      component('tv-data-telephone', 'TV / Data / Telephone Points'),
      component('floor-floorcoverings', 'Floor / Floorcoverings', true, true),
      component('skirting', 'Skirting'),
      component('windows-screens', 'Windows / Screens', true, true),
      component('blinds-curtains', 'Blinds / Curtains'),
    ],
  })),
  {
    id: 'kitchen',
    name: 'Kitchen',
    components: [
      component('ceiling-cornices', 'Ceiling / Cornices', true),
      component('walls', 'Walls', true, true),
      component('light-fittings', 'Light Fittings'),
      component('points-switches', 'Points and Switches'),
      component('floor-floorcoverings', 'Floor / Floorcoverings', true, true),
      component('windows-screens', 'Windows / Screens'),
      component('bench-tops', 'Bench Tops', true, true),
      component('sink-taps-spout', 'Sink / Taps / Spout', true, true),
      component('splashback-tiling', 'Splashback / Tiling', true),
      component('cupboards', 'Cupboards', true, true),
      component('drawers', 'Drawers', true),
      component('overhead-cupboards', 'Overhead Cupboards'),
      component('stove-top-hot-plates', 'Stove Top / Hot Plates', true, true),
      component('oven-griller', 'Oven / Griller', true, true),
      component('rangehood-exhaust', 'Rangehood / Exhaust Fan'),
      component('dishwasher', 'Dishwasher'),
      component('fridge-recess', 'Fridge Recess'),
      component('pantry', 'Pantry'),
    ],
  },
  {
    id: 'passage-hallway',
    name: 'Passage / Hallway',
    components: [
      component('ceiling-cornices', 'Ceiling / Cornices', true),
      component('manhole', 'Manhole'),
      component('walls', 'Walls', true, true),
      component('light-fittings', 'Light Fittings'),
      component('floor-floorcoverings', 'Floor / Floorcoverings', true, true),
      component('skirting', 'Skirting'),
      component('smoke-alarm', 'Smoke Alarm'),
      component('alarm-sensor', 'Alarm Sensor'),
    ],
  },
  {
    id: 'linen-press',
    name: 'Linen Press / Walk-in Linen Closet',
    components: [
      component('doors-frames-handles', 'Doors / Frames / Handles', true),
      component('ceiling', 'Ceiling'),
      component('walls', 'Walls'),
      component('floor', 'Floor'),
      component('shelves', 'Shelves', true, true),
      component('rails', 'Rails'),
      component('contents', 'Contents / Loose Items'),
    ],
  },
  ...['Bedroom', 'Study', 'Activity Room'].map((name) => ({
    id: name.toLowerCase().replaceAll(' ', '-'),
    name,
    components: [
      component('overall-condition', 'Overall Room Condition', true, true),
      component('doors-doorway-frames', 'Doors / Doorway Frames', true),
      component('door-handles', 'Door Handles'),
      component('ceiling-cornices', 'Ceiling / Cornices', true),
      component('walls', 'Walls', true, true),
      component('air-conditioner', 'Air Conditioner'),
      component('ceiling-fan', 'Ceiling Fan'),
      component('light-fittings', 'Light Fittings'),
      component('points-switches', 'Points and Switches'),
      component('floor-floorcoverings', 'Floor / Floorcoverings', true, true),
      component('skirting', 'Skirting'),
      component('windows-screens', 'Windows / Screens', true, true),
      component('blinds-curtains', 'Blinds / Curtains'),
      component('wardrobe', 'Wardrobe', true, true),
      component('shelves-rails', 'Shelves / Rails'),
    ],
  })),
  ...['Bathroom', 'Ensuite'].map((name) => ({
    id: name.toLowerCase(),
    name,
    components: [
      component('doors-doorway-frames', 'Doors / Doorway Frames'),
      component('ceiling-cornices', 'Ceiling / Cornices', true),
      component('walls-tiles', 'Walls / Tiles', true, true),
      component('light-fittings', 'Light Fittings'),
      component('points-switches', 'Points and Switches'),
      component('floor-tiles', 'Floor Tiles', true, true),
      component('windows-screens', 'Windows / Screens'),
      component('mirror', 'Mirror', true),
      component('bench-top', 'Bench Top'),
      component('basin-taps-spout-plug', 'Basin / Taps / Spout / Plug', true, true),
      component('vanity-cupboards-drawers', 'Vanity / Cupboards / Drawers', true),
      component('bath-taps', 'Bath / Taps'),
      component('shower-screen-taps', 'Shower / Screen / Taps', true, true),
      component('shower-rose', 'Shower Rose'),
      component('toilet', 'Toilet / Cistern / Seat / Lid / Pedestal'),
      component('towel-rails', 'Towel Rails'),
      component('exhaust-fan-vent', 'Exhaust Fan / Vent'),
    ],
  })),
  {
    id: 'toilet-wc',
    name: 'Toilet / WC',
    components: [
      component('doors-doorway-frames', 'Doors / Doorway Frames'),
      component('ceiling-cornices', 'Ceiling / Cornices'),
      component('walls', 'Walls'),
      component('light-fitting', 'Light Fitting'),
      component('floor', 'Floor', true, true),
      component('window-screen', 'Window / Screen'),
      component('toilet', 'Toilet / Cistern / Seat / Lid / Pedestal', true, true),
      component('toilet-roll-holder', 'Toilet Roll Holder'),
      component('exhaust-fan', 'Exhaust Fan'),
    ],
  },
  {
    id: 'laundry',
    name: 'Laundry',
    components: [
      component('doors-doorway-frames', 'Doors / Doorway Frames'),
      component('door-to-exterior', 'Door to Exterior'),
      component('ceiling-cornices', 'Ceiling / Cornices'),
      component('walls-tiles', 'Walls / Tiles', true, true),
      component('light-fittings', 'Light Fittings'),
      component('points-switches', 'Points and Switches'),
      component('floor', 'Floor', true, true),
      component('windows-screens', 'Windows / Screens'),
      component('bench-top', 'Bench Top'),
      component('trough-taps-spout', 'Trough Sink / Taps / Spout', true, true),
      component('washing-machine-taps', 'Washing Machine Taps'),
      component('splashback', 'Splashback'),
      component('trough-cupboard', 'Trough Cupboard'),
      component('overhead-cupboard', 'Overhead Cupboard'),
      component('exhaust-fan-vent', 'Exhaust Fan / Vent'),
    ],
  },
  {
    id: 'security-safety',
    name: 'Security / Safety',
    components: [
      component('smoke-alarms', 'Smoke Alarms', true, true),
      component('electrical-safety-switch', 'Electrical Safety Switch', true, true),
      component('keys', 'Keys'),
      component('remotes', 'Remotes'),
      component('opening-devices', 'Other Opening Devices'),
      component('alarm-panel-sensors', 'Security Alarm Panel / Sensors'),
      component('security-cameras', 'Security Cameras'),
    ],
  },
  {
    id: 'general-external-items',
    name: 'General External Items',
    components: [
      component('gardens', 'Gardens'),
      component('lawn-edges', 'Lawn / Edges'),
      component('letterbox-street-number', 'Letterbox / Street Number'),
      component('water-septic-tanks', 'Water Tanks / Septic Tanks'),
      component('garbage-bins', 'Garbage Bins'),
      component('paving-driveways', 'Paving / Driveways'),
      component('clothesline', 'Clothesline'),
      component('garage-carport-storeroom', 'Garage / Carport / Storeroom'),
      component('garden-shed', 'Garden Shed'),
      component('hot-water-system', 'Hot Water System'),
      component('gutters-downpipes', 'Gutters / Downpipes'),
      component('nbn-service-boxes', 'NBN / External Service Boxes'),
    ],
  },
  {
    id: 'garden-shed-external-storage',
    name: 'Garden Shed / External Storage',
    components: [
      component('door-frame-handle-lock', 'Door / Frame / Handle / Lock'),
      component('roof-ceiling', 'Roof / Ceiling'),
      component('walls', 'Walls'),
      component('floor', 'Floor'),
      component('shelving', 'Shelving'),
      component('contents-stored-items', 'Contents / Stored Items'),
      component('cleanliness', 'Cleanliness'),
      component('rust-dents-water-damage', 'Rust / Dents / Holes / Water Damage'),
    ],
  },
];

export const createInitialPcrTemplate = (createdAt = new Date().toISOString()): InspectionTypeTemplate => ({
  id: 'wa-residential-entry-pcr',
  version: 1,
  inspectionType: 'entry',
  propertyType: 'residential',
  status: 'draft',
  areas: structuredClone(pcrStandardAreas),
  commentaryBank: [],
  createdAt,
});
