import React, { useEffect, useState } from 'react';
import { Mail, MessageSquareText, Plus, Save, ShieldCheck } from 'lucide-react';
import { useAuth } from '../../../contexts/AuthContext';
import type { CommunicationTemplate, NotificationRule } from '../../../types/platform';
import { apiRequest } from '../../../services/apiClient';

const field = 'mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm';
const VARIABLES = ['tenant.firstName','tenant.fullName','property.address','inspection.startDate','inspection.startTime','report.accessUrl','maintenance.title','approval.accessUrl'];

const CommunicationSettingsPanel: React.FC = () => {
  const { userProfile } = useAuth(); const agencyId=userProfile?.agencyId;
  const [templates,setTemplates]=useState<CommunicationTemplate[]>([]); const [rules,setRules]=useState<NotificationRule[]>([]); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  const [name,setName]=useState('Inspection booking confirmation'); const [eventType,setEventType]=useState('inspection.booked'); const [channel,setChannel]=useState<'email'|'sms'>('email'); const [subject,setSubject]=useState('Your inspection booking'); const [body,setBody]=useState('Hello {{tenant.firstName}}, your inspection at {{property.address}} is booked for {{inspection.startDate}}.');
  const [ruleTemplate,setRuleTemplate]=useState(''); const [delay,setDelay]=useState(0);
  const load=async()=>{ if(!agencyId)return; const [nextTemplates,nextRules]=await Promise.all([apiRequest<CommunicationTemplate[]>(agencyId,'/api/v1/settings/communications/templates'),apiRequest<NotificationRule[]>(agencyId,'/api/v1/settings/communications/rules')]); setTemplates(nextTemplates); setRules(nextRules); if(!ruleTemplate&&nextTemplates[0])setRuleTemplate(nextTemplates[0].id); };
  useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:'Communication settings could not be loaded.'));},[agencyId]);
  const addTemplate=async()=>{if(!agencyId)return;setBusy(true);setError(null);try{await apiRequest(agencyId,'/api/v1/settings/communications/templates',{method:'POST',body:{name,eventType,channel,subject:channel==='email'?subject:undefined,body,allowedVariables:VARIABLES,status:'active'}});await load();}catch(e){setError(e instanceof Error?e.message:'Template could not be saved.');}finally{setBusy(false);}};
  const addRule=async()=>{if(!agencyId||!ruleTemplate)return;setBusy(true);setError(null);try{const template=templates.find(item=>item.id===ruleTemplate);await apiRequest(agencyId,'/api/v1/settings/communications/rules',{method:'POST',body:{eventType:template?.eventType||eventType,channel:template?.channel||channel,templateId:ruleTemplate,delayMinutes:delay,retryCount:2,enabled:true,status:'active'}});await load();}catch(e){setError(e instanceof Error?e.message:'Notification rule could not be saved.');}finally{setBusy(false);}};
  return <div className="space-y-5">{error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
    <div className="grid gap-4 lg:grid-cols-2"><ProviderCard agencyId={agencyId} provider="sendgrid" label="SendGrid Email" icon={<Mail size={18}/>}/><ProviderCard agencyId={agencyId} provider="twilio" label="Twilio SMS" icon={<MessageSquareText size={18}/>}/></div>
    <section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center gap-2"><Save size={17}/><h2 className="font-bold">Communication templates</h2></div><div className="mt-4 grid gap-3 md:grid-cols-2"><input className={field} value={name} onChange={e=>setName(e.target.value)} placeholder="Template name"/><input className={field} value={eventType} onChange={e=>setEventType(e.target.value)} placeholder="Event type"/><select className={field} value={channel} onChange={e=>setChannel(e.target.value as 'email'|'sms')}><option value="email">Email</option><option value="sms">SMS</option></select>{channel==='email'&&<input className={field} value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Subject"/>}<textarea className={`${field} md:col-span-2`} rows={5} value={body} onChange={e=>setBody(e.target.value)}/><button disabled={busy||!name.trim()||!eventType.trim()||!body.trim()} onClick={()=>void addTemplate()} className="md:col-span-2 inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-2 text-xs font-semibold text-white disabled:opacity-40"><Plus size={14}/>Create template</button></div><div className="mt-5 grid gap-3 md:grid-cols-2">{templates.map(item=><div key={item.id} className="rounded-xl border border-slate-200 p-4"><div className="flex justify-between gap-2"><b className="text-sm">{item.name}</b><span className="text-[10px] font-bold uppercase text-slate-400">{item.channel}</span></div><div className="mt-1 text-xs text-slate-500">{item.eventType} · v{item.version||1}</div><p className="mt-2 line-clamp-2 text-xs text-slate-600">{item.body}</p></div>)}</div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="font-bold">Notification rules</h2><div className="mt-4 grid gap-3 md:grid-cols-[1fr_180px_auto]"><select className={field} value={ruleTemplate} onChange={e=>setRuleTemplate(e.target.value)}><option value="">Select template</option>{templates.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><input className={field} type="number" min={0} value={delay} onChange={e=>setDelay(Number(e.target.value)||0)} placeholder="Delay minutes"/><button disabled={busy||!ruleTemplate} onClick={()=>void addRule()} className="rounded-xl bg-slate-950 px-4 py-2 text-xs font-semibold text-white disabled:opacity-40">Add rule</button></div><div className="mt-4 space-y-2">{rules.map(rule=><div key={rule.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 p-3 text-xs"><div><b>{rule.eventType}</b><span className="ml-2 text-slate-500">{rule.delayMinutes} min delay · {rule.retryCount} retries</span></div><span className={rule.enabled?'text-emerald-700':'text-slate-400'}>{rule.enabled?'Active':'Disabled'}</span></div>)}</div></section>
  </div>;
};

const ProviderCard:React.FC<{agencyId?:string;provider:'sendgrid'|'twilio';label:string;icon:React.ReactNode}>=({agencyId,provider,label,icon})=>{const [configured,setConfigured]=useState(false);const [secret,setSecret]=useState('');const [account,setAccount]=useState('');const [busy,setBusy]=useState(false);useEffect(()=>{if(!agencyId)return;void apiRequest<any>(agencyId,`/api/v1/settings/communications/providers/${provider}`).then(value=>setConfigured(Boolean(value))).catch(()=>setConfigured(false));},[agencyId,provider]);const connect=async()=>{if(!agencyId||!secret.trim())return;setBusy(true);try{const body=provider==='sendgrid'?{apiKey:secret,accountLabel:account||'SendGrid'}:{accountSid:account,authToken:secret,accountLabel:account||'Twilio'};await apiRequest(agencyId,`/api/v1/settings/communications/providers/${provider}`,{method:'POST',body});setConfigured(true);setSecret('');}finally{setBusy(false);}};return <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-2 font-bold">{icon}{label}</div><span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase ${configured?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-800'}`}>{configured?'Configured':'Not configured'}</span></div><div className="mt-4 grid gap-2"><input className={field} value={account} onChange={e=>setAccount(e.target.value)} placeholder={provider==='twilio'?'Account SID / label':'Account label'}/><input className={field} type="password" value={secret} onChange={e=>setSecret(e.target.value)} placeholder={provider==='sendgrid'?'API key':'Auth token'}/><button disabled={busy||!secret.trim()||(provider==='twilio'&&!account.trim())} onClick={()=>void connect()} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-xs font-semibold disabled:opacity-40"><ShieldCheck size={13}/>{busy?'Saving…':configured?'Rotate credential':'Connect'}</button></div></section>;};
export default CommunicationSettingsPanel;
