import React, { useEffect, useState } from 'react';
import { Save } from 'lucide-react';
import { useAuth } from '../../../contexts/AuthContext';
import type { AgencyOperationalSettings, InspectionReportType, InspectionTypeDefaults } from '../../../types/platform';
import { getOperationalSettings, saveOperationalSettings } from '../../../services/platform/agencySettingsService';

const REPORT_TYPES: InspectionReportType[] = ['Property Condition Report','Routine Inspection','Exit Inspection','Inspection Comparison Report','Maintenance and Follow-Up Report'];
function defaultRow(reportType: InspectionReportType): InspectionTypeDefaults { return { reportType, defaultDurationMinutes: reportType==='Routine Inspection'?45:60, bookingBufferBeforeMinutes:15, bookingBufferAfterMinutes:15, minimumNoticeHours:24, reportCompletionSlaHours:24, reviewSlaHours:12, requirePayment:false, requireAccessConfirmation:true, requireAnalystReview:true, requireReviewerApproval:true, automaticAiAnalysis:true, automaticPdfGeneration:true, automaticIssueAfterApproval:false }; }
const EMPTY: Omit<AgencyOperationalSettings,'id'|'agencyId'|'createdAt'|'updatedAt'>={version:undefined,status:'active',assignmentStrategy:'manual',automaticAssignmentEnabled:false,maximumTravelDistanceKm:50,operatingDays:[1,2,3,4,5],operatingStartTime:'08:00',operatingEndTime:'17:00',inspectionDefaults:REPORT_TYPES.map(defaultRow)};
const field='w-full rounded-lg border border-slate-200 px-2 py-1.5 text-xs';

const InspectionDefaultsPanel:React.FC=()=>{const {userProfile}=useAuth();const [form,setForm]=useState(EMPTY);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [saved,setSaved]=useState(false);
useEffect(()=>{if(!userProfile?.agencyId)return;void getOperationalSettings(userProfile.agencyId).then(value=>{if(value){const{id:_i,agencyId:_a,createdAt:_c,updatedAt:_u,...editable}=value;setForm({...EMPTY,...editable,inspectionDefaults:REPORT_TYPES.map(type=>editable.inspectionDefaults.find(row=>row.reportType===type)||defaultRow(type))});}}).catch(e=>setError(e instanceof Error?e.message:'Inspection defaults could not be loaded.'));},[userProfile?.agencyId]);
const update=(type:InspectionReportType,patch:Partial<InspectionTypeDefaults>)=>setForm(current=>({...current,inspectionDefaults:current.inspectionDefaults.map(row=>row.reportType===type?{...row,...patch}:row)}));
const save=async()=>{if(!userProfile?.agencyId)return;setBusy(true);setError(null);setSaved(false);try{const next=await saveOperationalSettings(userProfile.agencyId,form);const{id:_i,agencyId:_a,createdAt:_c,updatedAt:_u,...editable}=next;setForm(editable);setSaved(true);}catch(e){setError(e instanceof Error?e.message:'Inspection defaults could not be saved.');}finally{setBusy(false);}};
return <div className="space-y-5">{error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}{saved&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">Inspection defaults saved.</div>}<section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">Scheduling & assignment policy</h2><p className="text-xs text-slate-500">Agency defaults applied before client, property or job-specific overrides.</p></div><button disabled={busy} onClick={()=>void save()} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2 text-xs font-semibold text-white"><Save size={13}/>{busy?'Saving…':'Save defaults'}</button></div><div className="mt-4 grid gap-3 md:grid-cols-4"><label className="text-xs font-semibold">Assignment strategy<select className={`mt-1 ${field}`} value={form.assignmentStrategy} onChange={e=>setForm({...form,assignmentStrategy:e.target.value as AgencyOperationalSettings['assignmentStrategy']})}><option value="manual">Manual</option><option value="workload">Workload</option><option value="service_area">Service area</option><option value="round_robin">Round robin</option><option value="qualification">Qualification</option></select></label><label className="text-xs font-semibold">Operating start<input type="time" className={`mt-1 ${field}`} value={form.operatingStartTime} onChange={e=>setForm({...form,operatingStartTime:e.target.value})}/></label><label className="text-xs font-semibold">Operating end<input type="time" className={`mt-1 ${field}`} value={form.operatingEndTime} onChange={e=>setForm({...form,operatingEndTime:e.target.value})}/></label><label className="text-xs font-semibold">Max travel km<input type="number" min={0} className={`mt-1 ${field}`} value={form.maximumTravelDistanceKm||0} onChange={e=>setForm({...form,maximumTravelDistanceKm:Number(e.target.value)})}/></label></div><label className="mt-4 flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={form.automaticAssignmentEnabled} onChange={e=>setForm({...form,automaticAssignmentEnabled:e.target.checked})}/>Enable automatic assignment using this strategy</label></section>
<section className="overflow-x-auto rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">Inspection type defaults</h2><table className="mt-4 min-w-[1050px] w-full text-left text-xs"><thead className="text-slate-500"><tr><th className="pb-2">Report type</th><th>Duration</th><th>Buffer before</th><th>Buffer after</th><th>Notice hrs</th><th>Report SLA</th><th>Review SLA</th><th>Workflow gates</th></tr></thead><tbody>{form.inspectionDefaults.map(row=><tr key={row.reportType} className="border-t border-slate-100"><td className="py-3 pr-3 font-semibold">{row.reportType}</td>{(['defaultDurationMinutes','bookingBufferBeforeMinutes','bookingBufferAfterMinutes','minimumNoticeHours','reportCompletionSlaHours','reviewSlaHours'] as const).map(key=><td key={key} className="pr-2"><input type="number" min={0} className="w-20 rounded border border-slate-200 px-2 py-1" value={row[key]||0} onChange={e=>update(row.reportType,{[key]:Number(e.target.value)})}/></td>)}<td><div className="flex flex-wrap gap-x-3 gap-y-1">{([['requireAccessConfirmation','Access'],['requireAnalystReview','Analyst'],['requireReviewerApproval','Reviewer'],['automaticAiAnalysis','AI'],['automaticPdfGeneration','PDF']] as const).map(([key,label])=><label key={key} className="flex items-center gap-1"><input type="checkbox" checked={Boolean(row[key])} onChange={e=>update(row.reportType,{[key]:e.target.checked})}/>{label}</label>)}</div></td></tr>)}</tbody></table></section></div>;};
export default InspectionDefaultsPanel;
