import React, { useEffect, useState } from 'react';
import { Save } from 'lucide-react';
import { useAuth } from '../../../contexts/AuthContext';
import type { MaintenancePolicySettings } from '../../../types/platform';
import { getMaintenancePolicy, saveMaintenancePolicy } from '../../../services/platform/agencySettingsService';

type EditableMaintenance = Omit<MaintenancePolicySettings,'id'|'agencyId'|'createdAt'|'updatedAt'>;
const EMPTY:EditableMaintenance={version:undefined,status:'active',defaultTaxRate:10,defaultMarkupPercent:0,minimumCharge:0,quoteValidityDays:30,delegatedAuthorityLimit:500,emergencyAuthorityLimit:1000,landlordApprovalThreshold:500,multiQuoteThreshold:2000,minimumContractorQuoteCount:2,completionEvidenceRequired:true,invoiceReconciliationRequired:true,responseSlaHours:{emergency:2,urgent:4,routine:48,planned:168}};
const input='mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm';
function editable(value:MaintenancePolicySettings):EditableMaintenance{const copy={...value} as unknown as Record<string,unknown>;delete copy.id;delete copy.agencyId;delete copy.createdAt;delete copy.updatedAt;return copy as unknown as EditableMaintenance;}
const MaintenancePolicyPanel:React.FC=()=>{const{userProfile}=useAuth();const[form,setForm]=useState(EMPTY);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[saved,setSaved]=useState(false);useEffect(()=>{if(!userProfile?.agencyId)return;void getMaintenancePolicy(userProfile.agencyId).then(value=>{if(value)setForm(editable(value));}).catch(e=>setError(e instanceof Error?e.message:'Maintenance policy could not be loaded.'));},[userProfile?.agencyId]);
const set=(key:keyof typeof form,value:number|boolean)=>setForm(current=>({...current,[key]:value}));const save=async()=>{if(!userProfile?.agencyId)return;setBusy(true);setError(null);setSaved(false);try{const next=await saveMaintenancePolicy(userProfile.agencyId,form);setForm(editable(next));setSaved(true);}catch(e){setError(e instanceof Error?e.message:'Maintenance policy could not be saved.');}finally{setBusy(false);}};
return <div className="space-y-5">{error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}{saved&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">Maintenance policy saved.</div>}<section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex justify-between gap-3"><div><h2 className="font-bold">Commercial & authority defaults</h2><p className="mt-1 text-xs text-slate-500">Agency policy defaults. Existing detailed price books, contractor records and Xero mapping remain in Maintenance Configuration.</p></div><button disabled={busy} onClick={()=>void save()} className="inline-flex h-fit items-center gap-2 rounded-xl bg-blue-600 px-4 py-2 text-xs font-semibold text-white"><Save size={13}/>{busy?'Saving…':'Save policy'}</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{([['defaultTaxRate','Default tax %'],['defaultMarkupPercent','Default markup %'],['minimumCharge','Minimum charge'],['quoteValidityDays','Quote validity days'],['delegatedAuthorityLimit','Delegated authority'],['emergencyAuthorityLimit','Emergency authority'],['landlordApprovalThreshold','Approval threshold'],['multiQuoteThreshold','Multi-quote threshold'],['minimumContractorQuoteCount','Minimum quotes']] as const).map(([key,label])=><label key={key} className="text-xs font-semibold">{label}<input className={input} type="number" min={0} value={Number(form[key]||0)} onChange={e=>set(key,Number(e.target.value))}/></label>)}</div><div className="mt-5 flex flex-wrap gap-5"><label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={form.completionEvidenceRequired} onChange={e=>set('completionEvidenceRequired',e.target.checked)}/>Completion evidence required</label><label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={form.invoiceReconciliationRequired} onChange={e=>set('invoiceReconciliationRequired',e.target.checked)}/>Invoice reconciliation required</label></div></section><section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="font-bold">Response SLA</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{(['emergency','urgent','routine','planned'] as const).map(priority=><label key={priority} className="text-xs font-semibold capitalize">{priority} hours<input className={input} type="number" min={1} value={form.responseSlaHours[priority]||0} onChange={e=>setForm(current=>({...current,responseSlaHours:{...current.responseSlaHours,[priority]:Number(e.target.value)}}))}/></label>)}</div></section></div>;};
export default MaintenancePolicyPanel;
