import React, { useEffect, useState } from 'react';
import { History, RotateCcw, ShieldCheck } from 'lucide-react';
import { useAuth } from '../../../contexts/AuthContext';
import { apiRequest } from '../../../services/apiClient';

interface ChangeRecord { id:string; section?:string; entityId?:string; versionBefore?:number; versionAfter?:number; fieldsChanged?:string[]; changedBy?:string; changedAt?:string; reason?:string; }
interface VersionRecord { id:string; section?:string; sourceRecordId?:string; sourceVersion?:number; changedBy?:string; changedAt?:string; reason?:string; }
function date(value?:string){if(!value)return'Not recorded';const parsed=new Date(value);return Number.isNaN(parsed.getTime())?value:parsed.toLocaleString();}

const SecurityAuditPanel:React.FC=()=>{const{userProfile}=useAuth();const[changes,setChanges]=useState<ChangeRecord[]>([]);const[versions,setVersions]=useState<VersionRecord[]>([]);const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState<string|null>(null);
const load=async()=>{if(!userProfile?.agencyId)return;const[nextChanges,nextVersions]=await Promise.all([apiRequest<ChangeRecord[]>(userProfile.agencyId,'/api/v1/settings/history'),apiRequest<VersionRecord[]>(userProfile.agencyId,'/api/v1/settings/history/versions')]);setChanges(nextChanges);setVersions(nextVersions);};
useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:'Settings history could not be loaded.'));},[userProfile?.agencyId]);
const restore=async(version:VersionRecord)=>{if(!userProfile?.agencyId||!window.confirm(`Restore ${version.sourceRecordId} from version ${version.sourceVersion}? A new version will be created; history will not be rewritten.`))return;setBusy(version.id);setError(null);try{await apiRequest(userProfile.agencyId,`/api/v1/settings/history/restore/${encodeURIComponent(version.id)}`,{method:'POST',body:{}});await load();}catch(e){setError(e instanceof Error?e.message:'Version could not be restored.');}finally{setBusy(null);}};
return <div className="space-y-5">{error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}<section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center gap-2"><ShieldCheck size={18}/><h2 className="font-bold">Configuration governance</h2></div><p className="mt-2 text-sm text-slate-500">Settings writes remain capability-gated and privileged administrators retain the existing MFA requirement. Restores create a new current version rather than rewriting history.</p></section><div className="grid gap-5 xl:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><History size={17}/><h2 className="font-bold">Change history</h2></div><div className="mt-4 max-h-[560px] space-y-2 overflow-auto">{changes.length?changes.map(item=><div key={item.id} className="rounded-xl border border-slate-200 p-3"><div className="flex justify-between gap-2"><b className="text-xs capitalize">{item.section||'settings'} · {item.entityId}</b><span className="text-[10px] text-slate-400">{date(item.changedAt)}</span></div><div className="mt-1 text-xs text-slate-500">v{item.versionBefore||0} → v{item.versionAfter||1} · {item.changedBy||'system'}</div>{item.fieldsChanged?.length?<div className="mt-2 text-[11px] text-slate-600">Changed: {item.fieldsChanged.join(', ')}</div>:null}{item.reason&&<div className="mt-1 text-[11px] text-slate-500">Reason: {item.reason}</div>}</div>):<div className="text-sm text-slate-500">No settings changes have been recorded yet.</div>}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">Immutable versions</h2><div className="mt-4 max-h-[560px] space-y-2 overflow-auto">{versions.length?versions.map(item=><div key={item.id} className="flex items-center justify-between gap-3 rounded-xl border border-slate-200 p-3"><div><b className="text-xs capitalize">{item.section} · {item.sourceRecordId}</b><div className="mt-1 text-[11px] text-slate-500">Version {item.sourceVersion} · {date(item.changedAt)}</div></div><button disabled={busy===item.id} onClick={()=>void restore(item)} className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-3 py-2 text-[11px] font-semibold disabled:opacity-40"><RotateCcw size={12}/>{busy===item.id?'Restoring…':'Restore'}</button></div>):<div className="text-sm text-slate-500">No immutable settings versions have been recorded yet.</div>}</div></section></div></div>;};
export default SecurityAuditPanel;
