import React, { useEffect, useMemo, useState } from 'react';
import type { CommunicationMessage, CommunicationThread } from '@pcr/domain';
import { createCommunicationThread, listCommunicationMessages, listCommunicationThreads, sendThreadMessage } from '../../services/platform/enhancementService';

const CommunicationsPage: React.FC = () => {
  const [threads, setThreads] = useState<CommunicationThread[]>([]); const [messages, setMessages] = useState<CommunicationMessage[]>([]); const [active, setActive] = useState<string>(); const [body, setBody] = useState(''); const [recipient, setRecipient] = useState(''); const [error, setError] = useState('');
  const load = async () => { try { const [t, m] = await Promise.all([listCommunicationThreads(), listCommunicationMessages()]); setThreads(t); setMessages(m); if (!active && t[0]) setActive(t[0].id); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } };
  useEffect(() => { void load(); }, []);
  const visible = useMemo(() => messages.filter((message) => message.threadId === active).sort((a,b) => a.createdAt.localeCompare(b.createdAt)), [active, messages]);
  const newThread = async () => { try { const thread = await createCommunicationThread({ subject: 'New conversation', status: 'open', participants: [], entityLinks: [] }); setThreads((items) => [thread, ...items]); setActive(thread.id); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } };
  const send = async () => { if (!active || !body.trim() || !recipient.trim()) return; try { await sendThreadMessage(active, { channel: recipient.includes('@') ? 'email' : 'sms', recipients: [recipient.trim()], body: body.trim() }); setBody(''); await load(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } };
  return <section className="space-y-4"><header className="flex items-center justify-between"><div><h1 className="text-2xl font-bold">Communications</h1><p className="text-sm text-gray-600">Email, SMS and portal correspondence linked to operational records.</p></div><button className="rounded bg-gray-950 px-4 py-2 text-sm text-white" onClick={() => void newThread()}>New conversation</button></header>{error && <div className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>}<div className="grid min-h-[580px] gap-4 lg:grid-cols-[320px_1fr]"><aside className="rounded-xl border bg-white p-2">{threads.map((thread) => <button key={thread.id} onClick={() => setActive(thread.id)} className={`mb-1 w-full rounded-lg p-3 text-left ${active === thread.id ? 'bg-gray-950 text-white' : 'hover:bg-gray-50'}`}><div className="font-medium">{thread.subject}</div><div className="text-xs opacity-70">{thread.status} · {thread.lastMessageAt ? new Date(thread.lastMessageAt).toLocaleString() : 'No messages'}</div></button>)}</aside><div className="flex flex-col rounded-xl border bg-white"><div className="flex-1 space-y-3 overflow-auto p-4">{visible.map((message) => <div key={message.id} className={`max-w-2xl rounded-lg p-3 text-sm ${message.direction === 'outbound' ? 'ml-auto bg-gray-950 text-white' : 'bg-gray-100'}`}><div>{message.body}</div><div className="mt-1 text-xs opacity-60">{message.channel} · {message.status}</div></div>)}</div><div className="border-t p-4"><div className="mb-2 grid gap-2 sm:grid-cols-[240px_1fr]"><input className="rounded border px-3 py-2 text-sm" placeholder="Email or mobile" value={recipient} onChange={(e) => setRecipient(e.target.value)} /><textarea className="min-h-20 rounded border px-3 py-2 text-sm" placeholder="Message" value={body} onChange={(e) => setBody(e.target.value)} /></div><button className="rounded bg-gray-950 px-4 py-2 text-sm text-white" onClick={() => void send()} disabled={!active}>Send</button></div></div></div></section>;
};
export default CommunicationsPage;
