import React, { useEffect, useMemo, useState } from 'react';
import type { ComplianceObligation } from '@pcr/domain';
import { listComplianceObligations } from '../../services/platform/enhancementService';

const CompliancePage: React.FC = () => {
  const [items, setItems] = useState<ComplianceObligation[]>([]); const [filter, setFilter] = useState<'all' | 'open' | 'overdue' | 'satisfied'>('all'); const [error, setError] = useState('');
  useEffect(() => { void listComplianceObligations().then(setItems).catch((e) => setError(e instanceof Error ? e.message : String(e))); }, []);
  const now = Date.now(); const rows = useMemo(() => items.map((item) => ({ ...item, effectiveStatus: item.status === 'open' && item.dueAt && Date.parse(item.dueAt) < now ? 'overdue' : item.status })).filter((item) => filter === 'all' || item.effectiveStatus === filter).sort((a,b) => String(a.dueAt || '9999').localeCompare(String(b.dueAt || '9999'))), [filter, items, now]);
  const overdue = items.filter((item) => item.status === 'open' && item.dueAt && Date.parse(item.dueAt) < now).length;
  return <section className="space-y-5"><header><h1 className="text-2xl font-bold">Compliance Register</h1><p className="text-sm text-gray-600">Operational obligations with versioned rules and evidence, excluding trust-accounting and financial compliance.</p></header>{error && <div className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>}<div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl border bg-white p-4"><div className="text-xs uppercase text-gray-500">Open</div><div className="text-2xl font-bold">{items.filter(i => i.status === 'open').length}</div></div><div className="rounded-xl border bg-white p-4"><div className="text-xs uppercase text-gray-500">Overdue</div><div className="text-2xl font-bold">{overdue}</div></div><div className="rounded-xl border bg-white p-4"><div className="text-xs uppercase text-gray-500">Satisfied</div><div className="text-2xl font-bold">{items.filter(i => i.status === 'satisfied').length}</div></div></div><div className="flex gap-2">{(['all','open','overdue','satisfied'] as const).map((value) => <button key={value} className={`rounded px-3 py-1.5 text-sm ${filter === value ? 'bg-gray-950 text-white' : 'border bg-white'}`} onClick={() => setFilter(value)}>{value}</button>)}</div><div className="overflow-hidden rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-gray-50"><tr><th className="p-3">Obligation</th><th className="p-3">Entity</th><th className="p-3">Due</th><th className="p-3">Status</th></tr></thead><tbody>{rows.map((item) => <tr key={item.id} className="border-t"><td className="p-3 font-medium">{item.label}</td><td className="p-3 text-gray-600">{item.entityType} · {item.entityId}</td><td className="p-3">{item.dueAt ? new Date(item.dueAt).toLocaleDateString() : 'No date'}</td><td className="p-3">{item.effectiveStatus}</td></tr>)}</tbody></table></div></section>;
};
export default CompliancePage;
