import React, { useEffect, useState } from 'react';
import type { DocumentPacket } from '@pcr/domain';
import { approveDocumentPacket, createDocumentPacket, issueDocumentPacket, listDocumentPackets, validateDocumentPacket } from '../../services/platform/enhancementService';

const DocumentOperationsPage: React.FC = () => {
  const [packets, setPackets] = useState<DocumentPacket[]>([]); const [propertyId, setPropertyId] = useState(''); const [tenancyId, setTenancyId] = useState(''); const [policyId, setPolicyId] = useState(''); const [error, setError] = useState('');
  const load = async () => { try { setPackets(await listDocumentPackets()); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } };
  useEffect(() => { void load(); }, []);
  const create = async () => { if (!propertyId.trim() || !tenancyId.trim() || !policyId.trim()) return; try { await createDocumentPacket({ propertyId: propertyId.trim(), tenancyId: tenancyId.trim(), packetType: 'new_tenancy', jurisdictionPolicyVersionId: policyId.trim(), documentIds: [], recipients: [], status: 'draft', dataSnapshot: {}, dataSnapshotSha256: '', version: 1 }); await load(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } };
  const act = async (packet: DocumentPacket, action: 'validate' | 'approve' | 'issue') => { try { if (action === 'validate') await validateDocumentPacket(packet); else if (action === 'approve') await approveDocumentPacket(packet); else await issueDocumentPacket(packet); await load(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } };
  return <section className="space-y-5"><header><h1 className="text-2xl font-bold">Tenancy Documents</h1><p className="text-sm text-gray-600">Jurisdiction-aware document packets, approvals, issue and signing. Financial transactions remain external.</p></header>{error && <div className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>}<div className="grid gap-2 rounded-xl border bg-white p-4 lg:grid-cols-[1fr_1fr_1fr_auto]"><input className="rounded border px-3 py-2 text-sm" placeholder="Property ID" value={propertyId} onChange={(e) => setPropertyId(e.target.value)} /><input className="rounded border px-3 py-2 text-sm" placeholder="Tenancy ID" value={tenancyId} onChange={(e) => setTenancyId(e.target.value)} /><input className="rounded border px-3 py-2 text-sm" placeholder="Jurisdiction policy version ID" value={policyId} onChange={(e) => setPolicyId(e.target.value)} /><button className="rounded bg-gray-950 px-4 py-2 text-sm text-white" onClick={() => void create()}>Create packet</button></div><div className="grid gap-3">{packets.map((packet) => <article key={packet.id} className="rounded-xl border bg-white p-4"><div className="flex flex-wrap justify-between gap-3"><div><div className="font-semibold">{packet.packetType}</div><div className="text-sm text-gray-500">{packet.propertyId} · {packet.tenancyId} · {packet.status}</div><div className="mt-1 text-xs text-gray-500">{packet.documentIds.length} document(s) · {packet.recipients.length} recipient(s)</div></div><div className="flex gap-2"><button className="rounded border px-3 py-1.5 text-sm" onClick={() => void act(packet, 'validate')}>Validate</button><button className="rounded border px-3 py-1.5 text-sm" disabled={packet.status !== 'approval_required'} onClick={() => void act(packet, 'approve')}>Approve</button><button className="rounded bg-gray-950 px-3 py-1.5 text-sm text-white disabled:opacity-40" disabled={packet.status !== 'ready_to_issue'} onClick={() => void act(packet, 'issue')}>Issue</button></div></div></article>)}</div></section>;
};
export default DocumentOperationsPage;
