import React, { useEffect, useState } from 'react';
import type { PmsConnection } from '@pcr/domain';
import { createPmsConnection, listPmsConnections, runPmsSync } from '../../services/platform/enhancementService';

const IntegrationConnectionsPage: React.FC = () => {
  const [items, setItems] = useState<PmsConnection[]>([]); const [provider, setProvider] = useState('propertyme'); const [baseUrl, setBaseUrl] = useState(''); const [credentialReference, setCredentialReference] = useState(''); const [error, setError] = useState('');
  const load = async () => { try { setItems(await listPmsConnections()); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } };
  useEffect(() => { void load(); }, []);
  const create = async () => { if (!baseUrl.trim()) return; try { await createPmsConnection({ provider: provider.trim(), status: 'pending', credentialReference: credentialReference.trim() || undefined, enabledDirections: ['import','publish'], configuration: { baseUrl: baseUrl.trim() } }); setBaseUrl(''); setCredentialReference(''); await load(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } };
  const sync = async (item: PmsConnection, resource: string) => { try { await runPmsSync(item.id, { direction: 'import', resource }); await load(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } };
  return <section className="space-y-5"><header><h1 className="text-2xl font-bold">PMS Integrations</h1><p className="text-sm text-gray-600">Synchronise operational records with external property-management systems. Transactions, payments, trust ledgers and reconciliations are blocked by design.</p></header>{error && <div className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>}<div className="grid gap-2 rounded-xl border bg-white p-4 lg:grid-cols-[180px_1fr_1fr_auto]"><input className="rounded border px-3 py-2 text-sm" value={provider} onChange={(e) => setProvider(e.target.value)} placeholder="Provider" /><input className="rounded border px-3 py-2 text-sm" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} placeholder="HTTPS provider API/gateway base URL" /><input className="rounded border px-3 py-2 text-sm" value={credentialReference} onChange={(e) => setCredentialReference(e.target.value)} placeholder="Secret Manager credential reference" /><button className="rounded bg-gray-950 px-4 py-2 text-sm text-white" onClick={() => void create()}>Add connection</button></div><div className="grid gap-3">{items.map((item) => <article key={item.id} className="rounded-xl border bg-white p-4"><div className="flex flex-wrap justify-between gap-3"><div><div className="font-semibold">{item.provider}</div><div className="text-sm text-gray-500">{item.status} · last sync {item.lastSuccessfulSyncAt ? new Date(item.lastSuccessfulSyncAt).toLocaleString() : 'never'}</div></div><div className="flex flex-wrap gap-2">{['clients','properties','tenants','tenancies','operational_status'].map((resource) => <button key={resource} className="rounded border px-3 py-1.5 text-sm" disabled={item.status !== 'connected'} onClick={() => void sync(item, resource)}>Import {resource.replace('_',' ')}</button>)}</div></div></article>)}</div></section>;
};
export default IntegrationConnectionsPage;
