import React, { useEffect, useState } from 'react';
import type { AccessDeviceRegisterItem } from '@pcr/domain';
import { createKeyEvent, createKeyRegisterItem, listKeyRegister } from '../../services/platform/enhancementService';

const KeyRegisterPage: React.FC = () => {
  const [items, setItems] = useState<AccessDeviceRegisterItem[]>([]); const [error, setError] = useState(''); const [label, setLabel] = useState(''); const [propertyId, setPropertyId] = useState(''); const [holder, setHolder] = useState('');
  const load = async () => { try { setItems(await listKeyRegister()); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } };
  useEffect(() => { void load(); }, []);
  const add = async () => { if (!label.trim() || !propertyId.trim()) return; try { await createKeyRegisterItem({ propertyId: propertyId.trim(), label: label.trim(), kind: 'key', status: 'available' }); setLabel(''); await load(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } };
  const event = async (item: AccessDeviceRegisterItem, eventType: 'checked_out' | 'returned' | 'lost') => { try { await createKeyEvent(item.id, { eventType, toHolderId: eventType === 'checked_out' ? holder.trim() || undefined : undefined }); await load(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } };
  return <section className="space-y-5"><header><h1 className="text-2xl font-bold">Key & Access Register</h1><p className="text-sm text-gray-600">Append-only custody tracking for keys, fobs, remotes and access devices.</p></header>{error && <div className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>}<div className="grid gap-2 rounded-xl border bg-white p-4 md:grid-cols-[1fr_1fr_auto]"><input className="rounded border px-3 py-2 text-sm" placeholder="Property ID" value={propertyId} onChange={(e) => setPropertyId(e.target.value)} /><input className="rounded border px-3 py-2 text-sm" placeholder="Key label, e.g. P102-2" value={label} onChange={(e) => setLabel(e.target.value)} /><button className="rounded bg-gray-950 px-4 py-2 text-sm text-white" onClick={() => void add()}>Add device</button></div><div className="mb-2 max-w-sm"><input className="w-full rounded border px-3 py-2 text-sm" placeholder="Holder/user ID for checkout" value={holder} onChange={(e) => setHolder(e.target.value)} /></div><div className="grid gap-3">{items.map((item) => <article key={item.id} className="rounded-xl border bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="font-semibold">{item.label}</div><div className="text-sm text-gray-500">Property {item.propertyId} · {item.kind} · {item.status}</div>{item.currentHolderId && <div className="text-sm text-gray-600">Holder: {item.currentHolderId}</div>}</div><div className="flex gap-2">{item.status === 'available' ? <button className="rounded bg-gray-950 px-3 py-1.5 text-sm text-white" onClick={() => void event(item, 'checked_out')}>Check out</button> : <button className="rounded border px-3 py-1.5 text-sm" onClick={() => void event(item, 'returned')}>Return</button>}<button className="rounded border border-red-200 px-3 py-1.5 text-sm text-red-700" onClick={() => void event(item, 'lost')}>Mark lost</button></div></div></article>)}</div></section>;
};
export default KeyRegisterPage;
