import React, { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Bath, Bed, Building2, Car, FileSpreadsheet, Grid3X3, Layers3, List, Plus, Search, ShieldAlert } from 'lucide-react';
import type { OwnershipStructure, PropertyRecord, PropertyUse } from '../../types/platform';
import { listProperties } from '../../services/platform/propertyService';

const USE_OPTIONS: Array<{ value: PropertyUse | 'all'; label: string }> = [
  { value: 'all', label: 'All Uses' }, { value: 'residential', label: 'Residential' }, { value: 'commercial', label: 'Commercial' }, { value: 'industrial', label: 'Industrial' }, { value: 'retail', label: 'Retail' }, { value: 'mixed_use', label: 'Mixed Use' }, { value: 'strata_common_property', label: 'Strata / Common Property' }, { value: 'other', label: 'Other' },
];
const OWNERSHIP_OPTIONS: Array<{ value: OwnershipStructure | 'all'; label: string }> = [
  { value: 'all', label: 'All Ownership' }, { value: 'freehold', label: 'Freehold' }, { value: 'strata', label: 'Strata' }, { value: 'survey_strata', label: 'Survey Strata' }, { value: 'community_title', label: 'Community Title' }, { value: 'company_title', label: 'Company Title' }, { value: 'common_property', label: 'Common Property' }, { value: 'unknown', label: 'Unknown' },
];
function display(value?: string): string { return value ? value.replaceAll('_', ' ').replace(/\b\w/gu, (c) => c.toUpperCase()) : 'Not configured'; }

const PropertiesPage: React.FC = () => {
  const navigate = useNavigate();
  const [properties, setProperties] = useState<PropertyRecord[]>([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState('');
  const [useFilter, setUseFilter] = useState<PropertyUse | 'all'>('all'); const [typeFilter, setTypeFilter] = useState('all'); const [ownershipFilter, setOwnershipFilter] = useState<OwnershipStructure | 'all'>('all'); const [occupancyFilter, setOccupancyFilter] = useState('all'); const [readinessFilter, setReadinessFilter] = useState('all'); const [view, setView] = useState<'grid' | 'table'>('grid');
  useEffect(() => { void (async () => { setLoading(true); try { setProperties(await listProperties()); } finally { setLoading(false); } })(); }, []);
  const physicalTypes = useMemo(() => Array.from(new Set(properties.map((p) => p.physicalPropertyType || p.propertyType).filter(Boolean) as string[])).sort(), [properties]);
  const filtered = useMemo(() => properties.filter((p) => { const query = search.trim().toLowerCase(); const searchable = [p.address, p.suburb, p.postcode, p.landlordDetails?.name, p.tenantDetails?.primaryTenantName, p.strataDetails?.schemeName, p.strataDetails?.lotNumber].filter(Boolean).join(' ').toLowerCase(); const occupancy = p.tenantDetails?.occupancyStatus || 'vacant'; const readiness = p.onboarding?.status || 'legacy_record'; return (!query || searchable.includes(query)) && (useFilter === 'all' || p.propertyUse === useFilter) && (typeFilter === 'all' || (p.physicalPropertyType || p.propertyType) === typeFilter) && (ownershipFilter === 'all' || p.ownershipStructure === ownershipFilter) && (occupancyFilter === 'all' || occupancy === occupancyFilter) && (readinessFilter === 'all' || readiness === readinessFilter); }), [properties, search, useFilter, typeFilter, ownershipFilter, occupancyFilter, readinessFilter]);
  const strataCount = properties.filter((p) => ['strata', 'survey_strata', 'community_title', 'company_title', 'common_property'].includes(p.ownershipStructure || '')).length; const needsOnboarding = properties.filter((p) => p.onboarding?.status !== 'ready_for_inspection').length; const missingBaseline = properties.filter((p) => !(p.documents || []).some((d) => d.type === 'entry_report') && !(p.layoutVersions || []).length).length;
  const reset = () => { setSearch(''); setUseFilter('all'); setTypeFilter('all'); setOwnershipFilter('all'); setOccupancyFilter('all'); setReadinessFilter('all'); };
  return <div className="space-y-6 pb-16">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><h1 className="text-2xl font-black text-slate-950">Property Portfolio</h1><p className="mt-1 text-sm text-slate-500">Permanent property records, layouts, historical evidence, assets, access, tenancies and inspection history.</p></div><div className="flex flex-wrap gap-2"><button onClick={() => navigate('/app/admin/properties/import')} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs font-bold"><FileSpreadsheet size={16} /> Bulk Import</button><button onClick={() => navigate('/app/admin/properties/new')} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-xs font-bold text-white"><Plus size={16} /> Onboard Property</button></div></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Total Properties" value={properties.length} detail="managed records" /><Metric label="Strata / Common" value={strataCount} detail="ownership structures" /><Metric label="Needs Onboarding" value={needsOnboarding} detail="not inspection-ready" /><Metric label="Missing Historical Baseline" value={missingBaseline} detail="review recommended" /></div>
    <div className="flex flex-wrap gap-2"><button onClick={reset} className="rounded-full border border-slate-200 bg-white px-3 py-1.5 text-xs font-semibold">All Properties</button><button onClick={() => { reset(); setOwnershipFilter('strata'); }} className="rounded-full border border-slate-200 bg-white px-3 py-1.5 text-xs font-semibold">Strata Properties</button><button onClick={() => { reset(); setReadinessFilter('in_progress'); }} className="rounded-full border border-slate-200 bg-white px-3 py-1.5 text-xs font-semibold">Onboarding Incomplete</button></div>
    <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 xl:grid-cols-[minmax(260px,1fr)_160px_180px_170px_150px_170px_auto]"><div className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Address, suburb, owner, tenant, strata scheme..." className="w-full rounded-xl border border-slate-200 py-2 pl-9 pr-3 text-xs" /></div><select value={useFilter} onChange={(e) => setUseFilter(e.target.value as PropertyUse | 'all')} className="rounded-xl border border-slate-200 px-3 py-2 text-xs">{USE_OPTIONS.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}</select><select value={typeFilter} onChange={(e) => setTypeFilter(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2 text-xs"><option value="all">All Physical Types</option>{physicalTypes.map((item) => <option key={item} value={item}>{display(item)}</option>)}</select><select value={ownershipFilter} onChange={(e) => setOwnershipFilter(e.target.value as OwnershipStructure | 'all')} className="rounded-xl border border-slate-200 px-3 py-2 text-xs">{OWNERSHIP_OPTIONS.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}</select><select value={occupancyFilter} onChange={(e) => setOccupancyFilter(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2 text-xs"><option value="all">All Occupancy</option><option value="tenanted">Tenanted</option><option value="vacant">Vacant</option><option value="notice_given">Notice Given</option></select><select value={readinessFilter} onChange={(e) => setReadinessFilter(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2 text-xs"><option value="all">All Readiness</option><option value="ready_for_inspection">Inspection Ready</option><option value="in_progress">Onboarding In Progress</option><option value="not_started">Not Started</option><option value="legacy_record">Legacy Record</option></select><div className="flex rounded-xl border border-slate-200 p-1"><button onClick={() => setView('grid')} className={`rounded-lg p-1.5 ${view === 'grid' ? 'bg-slate-100 text-blue-600' : 'text-slate-400'}`}><Grid3X3 size={15} /></button><button onClick={() => setView('table')} className={`rounded-lg p-1.5 ${view === 'table' ? 'bg-slate-100 text-blue-600' : 'text-slate-400'}`}><List size={15} /></button></div></div></section>
    {loading ? <div className="p-10 text-center text-sm text-slate-500">Loading property portfolio...</div> : filtered.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center"><Building2 className="mx-auto text-slate-300" size={38} /><h3 className="mt-3 font-bold">No properties match these filters</h3></div> : view === 'grid' ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((p) => <PropertyCard key={p.id} property={p} />)}</div> : <div className="overflow-auto rounded-2xl border border-slate-200 bg-white"><table className="min-w-full text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th className="p-3">Property</th><th>Classification</th><th>Ownership</th><th>Occupancy</th><th>Areas</th><th>Documents</th><th>Readiness</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((p) => <tr key={p.id}><td className="p-3"><Link to={`/app/admin/properties/${p.id}`} className="font-bold text-slate-900 hover:text-blue-600">{p.address}</Link><div className="text-slate-400">{p.suburb} {p.postcode}</div></td><td>{display(p.propertyUse)}<div className="text-slate-400">{display(p.physicalPropertyType || p.propertyType)}</div></td><td>{display(p.ownershipStructure)}</td><td>{display(p.tenantDetails?.occupancyStatus || 'vacant')}</td><td>{p.roomsConfig?.length || 0}</td><td>{p.documents?.length || 0}</td><td>{display(p.onboarding?.status || 'legacy_record')}</td></tr>)}</tbody></table></div>}
  </div>;
};
const Metric: React.FC<{ label: string; value: number; detail: string }> = ({ label, value, detail }) => <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="text-[10px] font-bold uppercase tracking-wide text-slate-500">{label}</div><div className="mt-2 text-2xl font-black text-slate-950">{value}</div><div className="text-xs text-slate-400">{detail}</div></div>;
const PropertyCard: React.FC<{ property: PropertyRecord }> = ({ property }) => <Link to={`/app/admin/properties/${property.id}`} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:border-blue-300 hover:shadow-md"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap gap-1.5 text-[10px] font-bold uppercase"><span className="rounded bg-blue-50 px-2 py-1 text-blue-700">{display(property.propertyUse)}</span><span className="rounded bg-slate-100 px-2 py-1 text-slate-600">{display(property.physicalPropertyType || property.propertyType)}</span></div><h3 className="mt-3 text-base font-bold text-slate-950 group-hover:text-blue-600">{property.address}</h3><div className="text-xs text-slate-500">{[property.suburb, property.state, property.postcode].filter(Boolean).join(' ')}</div></div>{(property.alerts || []).some((a) => a.active) && <ShieldAlert size={18} className="text-amber-500" />}</div><div className="mt-4 flex flex-wrap gap-2 text-[11px] text-slate-600"><span className="inline-flex items-center gap-1 rounded-lg bg-slate-50 px-2 py-1"><Bed size={12} />{property.bedrooms || 0}</span><span className="inline-flex items-center gap-1 rounded-lg bg-slate-50 px-2 py-1"><Bath size={12} />{property.bathrooms || 0}</span><span className="inline-flex items-center gap-1 rounded-lg bg-slate-50 px-2 py-1"><Car size={12} />{property.parking || 0}</span><span className="inline-flex items-center gap-1 rounded-lg bg-slate-50 px-2 py-1"><Layers3 size={12} />{property.roomsConfig?.length || 0} areas</span></div><div className="mt-4 grid grid-cols-2 gap-2 rounded-xl bg-slate-50 p-3 text-xs"><Info title="Ownership" value={display(property.ownershipStructure)} /><Info title="Occupancy" value={display(property.tenantDetails?.occupancyStatus || 'vacant')} /><Info title="Documents" value={String(property.documents?.length || 0)} /><Info title="Readiness" value={display(property.onboarding?.status || 'legacy_record')} /></div></Link>;
const Info: React.FC<{ title: string; value: string }> = ({ title, value }) => <div><div className="text-[9px] uppercase text-slate-400">{title}</div><div className="font-semibold">{value}</div></div>;
export default PropertiesPage;
