import React, { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import type { PeopleDirectoryEntry, UserRole, WorkforceProfile } from '../../types/platform';
import { changePersonRole, getDeactivationImpact, listPeople, revokePersonSessions, saveWorkforceProfile, setMembershipStatus } from '../../services/platform/peopleService';
import { listAuditEventsForEntity } from '../../services/platform/auditService';
import type { AuditEvent } from '../../types/platform';

const roleOptions: UserRole[] = ['proinspect_admin', 'operations', 'inspector', 'analyst', 'reviewer'];
const tabs = ['Profile', 'Access', 'Work profile', 'Assignments', 'Security', 'Activity'] as const;

const UserWorkspacePage: React.FC = () => {
  const { userId = '' } = useParams(); const [person, setPerson] = useState<PeopleDirectoryEntry>(); const [tab, setTab] = useState<(typeof tabs)[number]>('Profile'); const [error, setError] = useState<string>(); const [audits, setAudits] = useState<AuditEvent[]>([]); const [impact, setImpact] = useState<any>();
  const load = async () => { try { const people = await listPeople(); setPerson(people.find((p) => p.id === userId)); setAudits(await listAuditEventsForEntity('user', userId)); setImpact(await getDeactivationImpact(userId)); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load user.'); } };
  useEffect(() => { void load(); }, [userId]);
  const capabilities = useMemo(() => person?.effectiveCapabilities ?? [], [person]);
  if (!person) return <div className="space-y-4"><Link to="/app/admin/users" className="text-sm underline">Back to users</Link>{error ? <div className="text-red-700">{error}</div> : <div>Loading user…</div>}</div>;
  const reason = () => window.prompt('Reason for this security-sensitive change:')?.trim();
  const doStatus = async (action: 'suspend'|'reactivate'|'revoke') => { const r = reason(); if (!r) return; try { await setMembershipStatus(person.id, action, r); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Action failed.'); } };
  const doRole = async (role: UserRole) => { const r = reason(); if (!r) return; try { await changePersonRole(person.id, role, r); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Role change failed.'); } };
  const saveWork = async () => { const current = person.workforceProfile; const profile: Partial<WorkforceProfile> = current ?? { agencyId: person.agencyId, userId: person.id, active: true, disciplines: person.role === 'reviewer' ? ['review'] : person.role === 'analyst' ? ['analysis'] : person.role === 'inspector' ? ['inspection'] : ['operations'], inspectionTypes: [], propertyUses: [], serviceAreas: [], commercialQualified: false, strataQualified: false }; try { await saveWorkforceProfile(person.id, profile); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Work profile update failed.'); } };
  return <div className="space-y-6"><div className="flex items-start justify-between gap-4"><div><Link to="/app/admin/users" className="text-sm text-gray-500 underline">People & Access</Link><h1 className="mt-2 text-2xl font-bold text-gray-950">{person.displayName || person.email}</h1><p className="text-sm text-gray-600">{person.email} · {person.role.replaceAll('_',' ')} · {person.membershipStatus}</p></div><div className="flex flex-wrap gap-2">{person.membershipStatus === 'active' && <button onClick={() => void doStatus('suspend')} className="rounded-lg border border-amber-300 px-3 py-2 text-sm">Suspend</button>}{person.membershipStatus === 'suspended' && <button onClick={() => void doStatus('reactivate')} className="rounded-lg border border-green-300 px-3 py-2 text-sm">Reactivate</button>}<button onClick={() => void doStatus('revoke')} className="rounded-lg border border-red-300 px-3 py-2 text-sm text-red-700">Revoke</button></div></div>{error && <div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="flex flex-wrap gap-2 border-b border-gray-200">{tabs.map((value) => <button key={value} onClick={() => setTab(value)} className={`px-3 py-2 text-sm font-medium ${tab === value ? 'border-b-2 border-gray-950 text-gray-950' : 'text-gray-500'}`}>{value}</button>)}</div>
  {tab === 'Profile' && <section className="grid gap-4 rounded-lg border border-gray-200 bg-white p-5 sm:grid-cols-2"><Field label="Name" value={person.displayName || '—'} /><Field label="Email" value={person.email} /><Field label="Identity UID" value={person.id} /><Field label="Last sign-in" value={person.identity?.lastSignInAt || 'No recorded sign-in'} /></section>}
  {tab === 'Access' && <section className="space-y-5 rounded-lg border border-gray-200 bg-white p-5"><div><label className="text-sm font-medium">Role</label><select value={person.role} onChange={(e) => void doRole(e.target.value as UserRole)} className="ml-3 rounded-lg border border-gray-300 px-3 py-2 text-sm">{roleOptions.map((r) => <option key={r} value={r}>{r.replaceAll('_',' ')}</option>)}</select></div><div><h3 className="font-semibold">Effective capabilities</h3><div className="mt-2 flex flex-wrap gap-2">{capabilities.map((c) => <span key={c} className="rounded-full bg-gray-100 px-2 py-1 text-xs text-gray-700">{c}</span>)}</div></div></section>}
  {tab === 'Work profile' && <section className="space-y-4 rounded-lg border border-gray-200 bg-white p-5"><p className="text-sm text-gray-600">Workforce capability is shared with inspection assignment and extends to analysis/review disciplines.</p><Field label="Disciplines" value={person.workforceProfile?.disciplines.join(', ') || 'Not configured'} /><Field label="Service areas" value={person.workforceProfile?.serviceAreas.join(', ') || 'Not configured'} /><Field label="Maximum jobs/day" value={String(person.workforceProfile?.maxJobsPerDay ?? 'Not set')} /><button onClick={() => void saveWork()} className="rounded-lg bg-gray-950 px-4 py-2 text-sm font-semibold text-white">{person.workforceProfile ? 'Refresh work profile' : 'Create work profile'}</button></section>}
  {tab === 'Assignments' && <section className="grid gap-3 rounded-lg border border-gray-200 bg-white p-5 sm:grid-cols-4"><Metric label="Active jobs" value={impact?.activeInspectionJobIds?.length ?? 0} /><Metric label="Active reports" value={impact?.activeReportIds?.length ?? 0} /><Metric label="Maintenance" value={impact?.activeMaintenanceItemIds?.length ?? 0} /><Metric label="Total impact" value={impact?.totalImpactedAssignments ?? 0} /></section>}
  {tab === 'Security' && <section className="space-y-4 rounded-lg border border-gray-200 bg-white p-5"><Field label="MFA policy" value={person.mfaRequired ? 'Required' : 'Optional'} /><Field label="Email verified" value={person.identity?.emailVerified ? 'Yes' : 'No'} /><Field label="Identity disabled" value={person.identity?.disabled ? 'Yes' : 'No'} /><button onClick={async () => { const r = reason(); if (!r) return; await revokePersonSessions(person.id, r); }} className="rounded-lg border border-gray-300 px-4 py-2 text-sm font-semibold">Revoke all sessions</button></section>}
  {tab === 'Activity' && <section className="space-y-3 rounded-lg border border-gray-200 bg-white p-5">{audits.length ? audits.map((event) => <div key={event.id} className="border-b border-gray-100 pb-3"><div className="text-sm font-medium">{event.eventType.replaceAll('_',' ')}</div><div className="text-xs text-gray-500">{new Date(event.timestamp).toLocaleString()} · {event.actorRole || 'system'}</div></div>) : <p className="text-sm text-gray-500">No user audit events are available.</p>}</section>}
  </div>;
};
const Field: React.FC<{label:string; value:string}> = ({label,value}) => <div><div className="text-xs uppercase text-gray-500">{label}</div><div className="mt-1 text-sm font-medium text-gray-900">{value}</div></div>;
const Metric: React.FC<{label:string; value:number}> = ({label,value}) => <div className="rounded-lg bg-gray-50 p-4"><div className="text-xs uppercase text-gray-500">{label}</div><div className="mt-1 text-2xl font-bold">{value}</div></div>;
export default UserWorkspacePage;
