/**
 * Source-backed reconciliation of the 67-table Appwrite foundation that
 * existed before the ProInspect and Strata-Site repositories were compared.
 * Keep this manifest explicit: it is migration evidence, not generated schema.
 */
export const RECONCILIATION_STATUSES = [
  'VERIFIED',
  'REQUIRES_CHANGE',
  'DUPLICATE',
  'UNSUPPORTED_ASSUMPTION',
  'MISSING_SOURCE',
  'NEW_CANONICAL_ENTITY',
];

const record = (table, source, sourceEntity, status, action) => ({ table, source, sourceEntity, status, action });

export const foundationReconciliation = [
  record('agencies', 'Firestore', 'agencies', 'VERIFIED', 'Retain as the agency tenancy root.'),
  record('managed_sites', 'Canonical + Strata D1', 'properties', 'NEW_CANONICAL_ENTITY', 'Retain as the operational site/scheme above inspectable properties.'),
  record('user_profiles', 'Firestore + Strata D1', 'users/people', 'REQUIRES_CHANGE', 'Retain profile data only; credentials and sessions are never rows.'),
  record('agency_memberships', 'Firestore', 'agencies/*/memberships', 'VERIFIED', 'Retain authoritative agency role and MFA requirement.'),
  record('site_memberships', 'Canonical + Strata D1', 'users.property_scope', 'NEW_CANONICAL_ENTITY', 'Retain explicit site scope instead of encoded role arrays.'),
  record('clients', 'Firestore', 'clients', 'REQUIRES_CHANGE', 'Add canonical account, billing, preference and external-reference fields.'),
  record('client_contacts', 'Firestore', 'clientContacts', 'REQUIRES_CHANGE', 'Preserve multi-role and communication/report preferences.'),
  record('properties', 'Firestore + Strata D1', 'properties', 'REQUIRES_CHANGE', 'Retain inspectable property/lot semantics; do not use it as a synonym for managed site.'),
  record('buildings', 'Firestore + Strata D1', 'property layout/buildings', 'REQUIRES_CHANGE', 'Allow a site or source property parent and preserve source IDs.'),
  record('property_levels', 'Firestore', 'property layout levels', 'NEW_CANONICAL_ENTITY', 'Retain normalized level nodes; Strata level_label values transform here.'),
  record('property_areas', 'Firestore + Strata D1', 'property layout areas/locations', 'REQUIRES_CHANGE', 'Retain location type and exclusive/common responsibility semantics.'),
  record('service_definitions', 'Firestore', 'serviceDefinitions', 'NEW_CANONICAL_ENTITY', 'Retain generic operational services independent of Shopify.'),
  record('service_requests', 'Firestore + Shopify', 'inspectionRequests/orders', 'NEW_CANONICAL_ENTITY', 'Retain generic intake before workflow-specific routing.'),
  record('service_request_items', 'Shopify + canonical', 'order line items', 'NEW_CANONICAL_ENTITY', 'Retain quantity and immutable provider references.'),
  record('shopify_service_mappings', 'Firestore + Shopify', 'inspectionServiceMappings/products/variants', 'REQUIRES_CHANGE', 'Keep Shopify mapping separate from service definition and financial truth.'),
  record('inspection_requests', 'Firestore', 'inspectionRequests', 'VERIFIED', 'Retain inspection-specific request and external references.'),
  record('inspection_jobs', 'Firestore', 'inspectionJobs', 'VERIFIED', 'Retain booking, assignment, readiness and immutable property snapshot.'),
  record('inspection_templates', 'Firestore + Strata D1', 'templates/inspection_templates', 'REQUIRES_CHANGE', 'Retain shared identity while preserving distinct template kinds.'),
  record('inspection_template_versions', 'Firestore', 'templateVersions', 'VERIFIED', 'Retain immutable published versions.'),
  record('inspections', 'Firestore', 'inspection jobs/report workspace', 'REQUIRES_CHANGE', 'Retain property-inspection execution; Strata operational inspections remain separate.'),
  record('inspection_sections', 'Firestore', 'reports/*/areas', 'REQUIRES_CHANGE', 'Add canonical area/version and responsibility snapshots.'),
  record('observations', 'Firestore', 'reports/*/areas/*/components', 'REQUIRES_CHANGE', 'Add canonical component/version, testing and source responsibility details.'),
  record('inspection_evidence', 'Firestore Storage', 'photoEvidence/photos', 'VERIFIED', 'Retain ordered evidence links; binary content stays in Storage.'),
  record('reports', 'Firestore', 'reports', 'VERIFIED', 'Retain property inspection report lifecycle only.'),
  record('report_versions', 'Firestore + Storage', 'reports/*/versions', 'REQUIRES_CHANGE', 'Preserve immutable snapshot hash and released file references.'),
  record('maintenance_candidates', 'Firestore', 'maintenanceCandidates', 'REQUIRES_CHANGE', 'Add canonical area/component source-version fields.'),
  record('maintenance_items', 'Firestore', 'maintenanceItems', 'VERIFIED', 'Retain triaged ProInspect maintenance item; do not collapse Strata defects into it.'),
  record('maintenance_quotes', 'Firestore', 'maintenanceQuotes', 'VERIFIED', 'Retain client-facing commercial quote distinct from contractor response.'),
  record('maintenance_estimates', 'Firestore', 'maintenanceEstimates', 'VERIFIED', 'Retain estimate lifecycle and basis.'),
  record('maintenance_approvals', 'Firestore', 'maintenance approval decisions', 'REQUIRES_CHANGE', 'Retain maintenance approval only; Strata approvals receive a separate target.'),
  record('maintenance_work_orders', 'Firestore', 'maintenanceWorkOrders', 'VERIFIED', 'Retain ProInspect maintenance work orders; Strata operational work orders are separate.'),
  record('maintenance_variations', 'Firestore', 'maintenanceVariations', 'VERIFIED', 'Retain variation approval lifecycle.'),
  record('preventive_maintenance', 'Firestore', 'preventiveMaintenanceSchedules', 'VERIFIED', 'Retain ProInspect preventive schedule.'),
  record('warranty_claims', 'Firestore', 'warrantyClaims', 'VERIFIED', 'Retain warranty lifecycle.'),
  record('contractor_quote_requests', 'Firestore', 'contractorQuoteRequests', 'VERIFIED', 'Retain vendor solicitation lifecycle.'),
  record('contractor_quotes', 'Firestore', 'contractorQuotes', 'VERIFIED', 'Retain vendor response distinct from client-facing quote.'),
  record('work_requests', 'Firestore', 'workRequests', 'VERIFIED', 'Retain lightweight external work request.'),
  record('tenant_instructions', 'Firestore', 'tenantInstructions', 'VERIFIED', 'Retain instruction lifecycle linked to a tenancy.'),
  record('external_contacts', 'Firestore', 'externalContacts', 'VERIFIED', 'Retain non-authenticated contact directory; do not use as contractor company.'),
  record('daily_activity_logs', 'Strata D1', 'daily_activity_logs', 'REQUIRES_CHANGE', 'Expand to the source operational form and provenance fields.'),
  record('resident_requests', 'Strata D1', 'resident_requests', 'REQUIRES_CHANGE', 'Use person/occupancy identity and preserve access/contact/defect linkage.'),
  record('contractor_attendance', 'Strata D1', 'contractor_attendance', 'REQUIRES_CHANGE', 'Preserve sign-in/out, key-return, safety and completion evidence.'),
  record('key_transactions', 'Strata D1', 'key_transactions', 'REQUIRES_CHANGE', 'Reference the controlled key register and attendance.'),
  record('access_devices', 'Strata D1', 'access_devices', 'REQUIRES_CHANGE', 'Preserve request, unit, collection, programming and deactivation state.'),
  record('access_device_history', 'Strata D1', 'access_device_history', 'VERIFIED', 'Retain append-only device event history.'),
  record('move_bookings', 'Strata D1', 'move_bookings', 'REQUIRES_CHANGE', 'Preserve request, approval, logistics, inspection and close gates.'),
  record('resident_onboarding', 'Strata D1', 'resident_onboarding', 'REQUIRES_CHANGE', 'Link person/occupancy and preserve module acknowledgements.'),
  record('operational_inspections', 'Strata D1', 'inspections', 'REQUIRES_CHANGE', 'Retain Building Management inspection lifecycle separate from property reports.'),
  record('assets', 'Strata D1 + Firestore', 'assets/property assets', 'REQUIRES_CHANGE', 'Preserve operational asset and source-specific metadata.'),
  record('maintenance_plans', 'Strata D1', 'maintenance_plans', 'VERIFIED', 'Retain source maintenance-plan semantics; do not silently merge with ProInspect schedules.'),
  record('waste_events', 'Strata D1', 'waste_events', 'REQUIRES_CHANGE', 'Preserve stream, quantity, issue, action and evidence.'),
  record('incidents', 'Strata D1', 'incidents', 'REQUIRES_CHANGE', 'Preserve emergency, damage, authority, follow-up and evidence semantics.'),
  record('bylaw_observations', 'Strata D1', 'bylaw_observations', 'REQUIRES_CHANGE', 'Preserve observation, decision, outcome, action and evidence.'),
  record('notices', 'Strata D1', 'notices', 'VERIFIED', 'Retain property/site notice lifecycle.'),
  record('communications', 'Strata D1', 'communications', 'REQUIRES_CHANGE', 'Retain delivery record; Firestore threads/messages remain separate source concepts.'),
  record('handovers', 'Strata D1', 'handovers', 'VERIFIED', 'Retain shift/manager handover.'),
  record('handover_checklist_items', 'Strata D1', 'handover_checklist_items', 'VERIFIED', 'Retain checklist completion evidence.'),
  record('operational_report_drafts', 'Strata D1', 'monthly_report_drafts', 'REQUIRES_CHANGE', 'Preserve report month, commentary and generated snapshot; finalisation is one way.'),
  record('operational_reports', 'Canonical from Strata D1', 'finalised monthly_report_drafts', 'NEW_CANONICAL_ENTITY', 'Create immutable release snapshots rather than updating a finalised draft.'),
  record('audit_events', 'Firestore + Strata D1', 'auditEvents/audit_events', 'REQUIRES_CHANGE', 'Preserve actor role, outcome and source timestamp; append-only writes only.'),
  record('integration_connections', 'Firestore', 'integrationConnections', 'VERIFIED', 'Retain provider configuration references; never store secrets.'),
  record('integration_events', 'Shopify + canonical', 'webhook deliveries', 'NEW_CANONICAL_ENTITY', 'Retain provider event deduplication and payload reference.'),
  record('integration_deliveries', 'Firestore', 'integrationDeliveries', 'VERIFIED', 'Retain provider delivery lifecycle.'),
  record('integration_exceptions', 'Firestore', 'integrationSyncExceptions', 'VERIFIED', 'Retain redacted reconciliation exceptions.'),
  record('integration_outbox', 'Strata D1 + canonical', 'integration_outbox/taskOutbox', 'VERIFIED', 'Retain immutable post-commit delivery work; no permanent dual write.'),
  record('evidence_files', 'Firebase Storage + Strata R2', 'object metadata/owning rows', 'NEW_CANONICAL_ENTITY', 'Retain canonical ownership/checksum metadata; files remain in scoped buckets.'),
  record('migration_id_map', 'Canonical migration control', 'all source entities', 'NEW_CANONICAL_ENTITY', 'Retain deterministic ID/checksum/idempotency ledger.'),
];
