const str = (key, size = 255, required = false, format) => ({ key, type: 'string', size, required, ...(format ? { format } : {}) });
const text = (key, required = false) => ({ key, type: 'longtext', required });
const datetime = (key, required = false) => ({ key, type: 'datetime', required });
const integer = (key, required = false) => ({ key, type: 'integer', required });
const number = (key, required = false) => ({ key, type: 'double', required });
const boolean = (key, required = false) => ({ key, type: 'boolean', required });
const index = (key, columns, orders) => ({ key, type: 'key', columns, ...(orders ? { orders } : {}) });
const unique = (key, columns) => ({ key, type: 'unique', columns });

const timestamps = [datetime('createdAt', true), datetime('updatedAt', true)];
const auditActors = [str('createdBy', 36), str('updatedBy', 36)];
const legacy = [str('legacySystem', 32), str('legacyId', 128)];
const agencyBase = [str('agencyId', 36, true), str('status', 64, true), ...timestamps, ...auditActors, ...legacy];

function table(id, columns, indexes = []) {
  const uniqueColumns = [...new Map(columns.map((column) => [column.key, column])).values()];
  return { $id: id, databaseId: 'proinspect_core', name: id.split('_').map((part) => part[0].toUpperCase() + part.slice(1)).join(' '), $permissions: [], rowSecurity: true, enabled: true, columns: uniqueColumns, indexes };
}

function agencyEntity(id, columns = [], indexes = []) {
  return table(id, [...agencyBase, ...columns], [index('agency_status', ['agencyId', 'status']), ...indexes]);
}

export const tables = [
  table('agencies', [str('name', 255, true), str('code', 64, true), str('status', 32, true), str('timezone', 64, true), ...timestamps, ...auditActors], [unique('agency_code', ['code']), index('status_name', ['status', 'name'])]),
  agencyEntity('managed_sites', [str('name',255,true),str('siteType',64,true),str('timezone',64,true),str('streetAddress',512),str('suburb',128),str('state',64),str('postcode',16),str('country',64),str('strataPlanNumber',128),str('schemeName',255),str('externalReference',128)], [index('agency_name',['agencyId','name'])]),
  table('user_profiles', [str('userId',36,true),str('displayName',255,true),str('preferredName',128),str('email',320,true,'email'),str('phone',32),str('status',32,true),...timestamps,...legacy], [unique('user_id',['userId']),index('status_email',['status','email'])]),
  table('agency_memberships', [str('userId',36,true),str('agencyId',36,true),str('role',64,true),str('status',32,true),datetime('validFrom'),datetime('validUntil'),boolean('mfaRequired',true),...timestamps], [unique('user_agency',['userId','agencyId']),index('agency_role_status',['agencyId','role','status'])]),
  table('site_memberships', [str('userId',36,true),str('agencyId',36,true),str('managedSiteId',36,true),str('role',64,true),str('status',32,true),datetime('validFrom'),datetime('validUntil'),...timestamps], [unique('user_site',['userId','managedSiteId']),index('site_role_status',['managedSiteId','role','status']),index('agency_user',['agencyId','userId'])]),
  agencyEntity('clients', [str('name',255,true),str('legalName',255),str('tradingName',255),str('abn',32),str('clientType',64),str('shopifyCustomerId',128),text('contactDetails')], [index('agency_name',['agencyId','name']),index('shopify_customer',['shopifyCustomerId'])]),
  agencyEntity('client_contacts', [str('clientId',36,true),str('name',255,true),str('email',320,false,'email'),str('phone',32),str('role',64),boolean('primary',true)], [index('client_status',['clientId','status']),index('agency_email',['agencyId','email'])]),
  agencyEntity('properties', [str('managedSiteId',36),str('clientId',36),str('propertyType',64,true),str('propertyUse',64,true),str('ownershipStructure',64,true),str('streetAddress',512,true),str('suburb',128),str('state',64),str('postcode',16),str('country',64),str('lotNumber',64),str('unitNumber',64),str('buildingName',255),str('strataPlanNumber',128),str('externalReference',128),text('strataDetails')], [index('agency_site_status',['agencyId','managedSiteId','status']),index('client_status',['clientId','status']),index('site_unit',['managedSiteId','unitNumber'])]),
  agencyEntity('buildings', [str('managedSiteId',36,true),str('name',255,true),str('code',64),integer('sequence')], [index('site_sequence',['managedSiteId','sequence'])]),
  agencyEntity('property_levels', [str('managedSiteId',36,true),str('buildingId',36,true),str('name',128,true),str('code',64),integer('sequence')], [index('building_sequence',['buildingId','sequence'])]),
  agencyEntity('property_areas', [str('managedSiteId',36),str('propertyId',36),str('buildingId',36),str('levelId',36),str('name',255,true),str('areaType',64),str('responsibility',64),integer('sequence')], [index('property_sequence',['propertyId','sequence']),index('level_sequence',['levelId','sequence'])]),

  agencyEntity('service_definitions', [str('code',64,true),str('name',255,true),str('category',64,true),str('workflowType',64,true),text('description'),text('defaultConfiguration')], [unique('agency_code',['agencyId','code']),index('workflow_status',['workflowType','status'])]),
  agencyEntity('service_requests', [str('managedSiteId',36),str('propertyId',36),str('clientId',36),str('serviceDefinitionId',36,true),str('source',64,true),str('sourceReference',255,true),str('requestedByUserId',36),str('requestedForName',255),str('requestedForEmail',320,false,'email'),str('requestedForPhone',32),str('paymentStatus',64,true),str('schedulingStatus',64,true),str('priority',32,true),datetime('requestedDate'),text('notes'),text('accessInstructions')], [index('agency_status_created',['agencyId','status','createdAt'],['ASC','ASC','DESC']),unique('source_reference',['agencyId','source','sourceReference']),index('property_created',['propertyId','createdAt'],['ASC','DESC'])]),
  agencyEntity('service_request_items', [str('serviceRequestId',36,true),str('serviceDefinitionId',36,true),integer('quantity',true),str('status',64,true),text('configuration')], [index('request_status',['serviceRequestId','status'])]),
  agencyEntity('shopify_service_mappings', [str('shopifyProductId',128,true),str('shopifyVariantId',128),str('serviceDefinitionId',36,true),boolean('active',true),text('mappingConfiguration')], [unique('agency_variant',['agencyId','shopifyProductId','shopifyVariantId']),index('service_active',['serviceDefinitionId','active'])]),

  agencyEntity('inspection_requests', [str('serviceRequestId',36),str('propertyId',36),str('inspectionType',128),str('source',64,true),str('sourceReference',255),str('paymentStatus',64),str('schedulingStatus',64),str('priority',32),text('shopifyReference'),text('calendarReference')], [index('agency_status_created',['agencyId','status','createdAt']),index('property_status',['propertyId','status'])]),
  agencyEntity('inspection_jobs', [str('inspectionRequestId',36),str('serviceRequestId',36),str('propertyId',36,true),str('inspectorId',36),str('reviewerId',36),str('inspectionType',128,true),datetime('scheduledDate'),str('priority',32),integer('version',true),text('propertySnapshot')], [index('inspector_schedule',['inspectorId','scheduledDate']),index('property_status',['propertyId','status'])]),
  agencyEntity('inspection_templates', [str('code',64,true),str('name',255,true),str('inspectionType',128,true),str('currentVersionId',36)], [unique('agency_code',['agencyId','code']),index('type_status',['inspectionType','status'])]),
  agencyEntity('inspection_template_versions', [str('templateId',36,true),integer('version',true),str('contentHash',128,true),text('definition',true),datetime('publishedAt'),boolean('immutable',true)], [unique('template_version',['templateId','version'])]),
  agencyEntity('inspections', [str('inspectionJobId',36,true),str('propertyId',36,true),str('inspectorId',36,true),datetime('startedAt'),datetime('submittedAt'),integer('version',true)], [unique('inspection_job',['inspectionJobId']),index('inspector_status',['inspectorId','status'])]),
  agencyEntity('inspection_sections', [str('inspectionId',36,true),str('areaId',36),str('name',255,true),integer('sequence',true),str('status',64)], [index('inspection_sequence',['inspectionId','sequence'])]),
  agencyEntity('observations', [str('inspectionId',36,true),str('sectionId',36,true),str('componentId',36),str('condition',64),str('cleanliness',64),str('workingStatus',64),text('commentary'),boolean('maintenanceRequired')], [index('inspection_section',['inspectionId','sectionId']),index('component_condition',['componentId','condition'])]),
  agencyEntity('inspection_evidence', [str('inspectionId',36,true),str('observationId',36),str('evidenceFileId',36,true),str('category',64),integer('sequence')], [index('inspection_sequence',['inspectionId','sequence']),index('observation',['observationId'])]),
  agencyEntity('reports', [str('inspectionJobId',36),str('propertyId',36,true),str('currentVersionId',36),str('lifecycleStatus',64,true),integer('version',true),datetime('finalisedAt'),str('finalisedBy',36)], [index('property_status',['propertyId','lifecycleStatus']),index('job_status',['inspectionJobId','lifecycleStatus'])]),
  agencyEntity('report_versions', [str('reportId',36,true),integer('version',true),str('contentHash',128,true),str('fileId',36),boolean('immutable',true),datetime('finalisedAt'),str('supersedesVersionId',36)], [unique('report_version',['reportId','version']),index('report_finalised',['reportId','finalisedAt'])]),

  agencyEntity('maintenance_candidates', [str('propertyId',36,true),str('inspectionJobId',36),str('reportId',36),str('observationId',36),str('title',255,true),text('description',true),str('category',64,true),str('priority',32,true),number('confidence'),str('confirmedItemId',36)], [index('property_status',['propertyId','status']),index('report_status',['reportId','status'])]),
  agencyEntity('maintenance_items', [str('managedSiteId',36),str('propertyId',36,true),str('candidateId',36),str('assignedContractorId',36),str('title',255,true),text('description',true),str('category',64,true),str('priority',32,true),str('approvalStatus',64),datetime('dueDate'),integer('version',true)], [index('site_status',['managedSiteId','status']),index('site_priority_status',['managedSiteId','priority','status']),index('property_status',['propertyId','status']),index('contractor_status',['assignedContractorId','status'])]),
  agencyEntity('maintenance_quotes', [str('maintenanceItemId',36,true),str('contractorId',36),str('currency',3),number('amount'),str('approvalStatus',64),datetime('validUntil'),text('scope')], [index('item_status',['maintenanceItemId','status']),index('contractor_status',['contractorId','status'])]),
  agencyEntity('maintenance_estimates', [str('maintenanceItemId',36,true),str('currency',3),number('amount'),text('basis'),datetime('validUntil')], [index('item_status',['maintenanceItemId','status'])]),
  agencyEntity('maintenance_approvals', [str('maintenanceItemId',36,true),str('quoteId',36),str('approvedBy',36),str('decision',32,true),text('reason'),datetime('decidedAt')], [index('item_decision',['maintenanceItemId','decision'])]),
  agencyEntity('maintenance_work_orders', [str('maintenanceItemId',36,true),str('quoteId',36),str('contractorId',36),str('assignedInternalUserId',36),str('priority',32),datetime('dueDate'),datetime('completedAt'),text('instructions'),integer('version',true)], [index('item_status',['maintenanceItemId','status']),index('contractor_status',['contractorId','status']),index('due_status',['dueDate','status'])]),
  agencyEntity('maintenance_variations', [str('workOrderId',36,true),number('amount'),str('currency',3),str('approvalStatus',64),text('reason',true)], [index('work_order_status',['workOrderId','status'])]),
  agencyEntity('preventive_maintenance', [str('managedSiteId',36),str('propertyId',36),str('assetId',36),str('cadence',64,true),datetime('nextDueAt',true),text('instructions')], [index('site_next_due',['managedSiteId','nextDueAt']),index('property_status',['propertyId','status'])]),
  agencyEntity('warranty_claims', [str('maintenanceItemId',36),str('assetId',36),str('provider',255),str('reference',128),datetime('lodgedAt'),text('details')], [index('item_status',['maintenanceItemId','status']),index('asset_status',['assetId','status'])]),
  agencyEntity('contractor_quote_requests', [str('maintenanceItemId',36,true),str('contractorId',36,true),datetime('dueAt'),text('scope',true)], [index('item_status',['maintenanceItemId','status']),index('contractor_status',['contractorId','status'])]),
  agencyEntity('contractor_quotes', [str('quoteRequestId',36,true),str('maintenanceItemId',36,true),str('contractorId',36,true),number('amount'),str('currency',3),text('scope'),datetime('submittedAt')], [index('item_status',['maintenanceItemId','status']),index('contractor_status',['contractorId','status'])]),
  agencyEntity('work_requests', [str('maintenanceItemId',36,true),str('externalContactId',36,true),str('priority',32),datetime('dueDate'),text('instructions',true),text('responseNotes')], [index('item_status',['maintenanceItemId','status']),index('contact_status',['externalContactId','status'])]),
  agencyEntity('tenant_instructions', [str('propertyId',36,true),str('tenancyId',36,true),str('maintenanceItemId',36),str('instructionType',64,true),str('title',255,true),text('instruction',true),datetime('dueDate')], [index('tenancy_status',['tenancyId','status']),index('item_status',['maintenanceItemId','status'])]),
  agencyEntity('external_contacts', [str('name',255,true),str('businessName',255),str('email',320,false,'email'),str('phone',32),str('contactType',64,true)], [index('agency_type_status',['agencyId','contactType','status']),index('email',['email'])]),

  agencyEntity('daily_activity_logs', [str('managedSiteId',36,true),str('authorUserId',36,true),datetime('activityDate',true),str('category',64),text('summary',true)], [index('site_activity_date',['managedSiteId','activityDate'])]),
  agencyEntity('resident_requests', [str('managedSiteId',36,true),str('propertyId',36),str('residentUserId',36,true),str('requestType',64,true),str('priority',32),str('assignedUserId',36),text('description',true)], [index('site_status',['managedSiteId','status']),index('resident_status',['residentUserId','status'])]),
  agencyEntity('contractor_attendance', [str('managedSiteId',36,true),str('contractorId',36,true),str('workOrderId',36),datetime('checkedInAt',true),datetime('checkedOutAt'),str('checkedInBy',36)], [index('site_checkin',['managedSiteId','checkedInAt']),index('contractor_checkin',['contractorId','checkedInAt'])]),
  agencyEntity('key_transactions', [str('managedSiteId',36,true),str('keyId',36,true),str('holderType',64),str('holderId',36),str('transactionType',64,true),datetime('occurredAt',true),str('authorisedBy',36),text('notes')], [index('key_occurred',['keyId','occurredAt']),index('site_occurred',['managedSiteId','occurredAt'])]),
  agencyEntity('access_devices', [str('managedSiteId',36,true),str('propertyId',36),str('deviceType',64,true),str('identifier',128,true),str('assignedToUserId',36)], [unique('site_identifier',['managedSiteId','identifier']),index('property_status',['propertyId','status'])]),
  agencyEntity('access_device_history', [str('accessDeviceId',36,true),str('action',64,true),str('actorUserId',36),str('assignedToUserId',36),datetime('occurredAt',true),text('notes')], [index('device_occurred',['accessDeviceId','occurredAt'])]),
  agencyEntity('move_bookings', [str('managedSiteId',36,true),str('propertyId',36,true),str('residentUserId',36),str('moveType',32,true),datetime('startAt',true),datetime('endAt',true),str('approvalStatus',64),text('conditions')], [index('site_start',['managedSiteId','startAt']),index('property_status',['propertyId','status'])]),
  agencyEntity('resident_onboarding', [str('managedSiteId',36,true),str('propertyId',36,true),str('residentUserId',36,true),str('occupancyType',64),datetime('inductedAt'),str('inductedBy',36),text('checklist')], [unique('site_resident',['managedSiteId','residentUserId']),index('property_status',['propertyId','status'])]),
  agencyEntity('operational_inspections', [str('managedSiteId',36,true),str('propertyId',36),str('inspectorId',36,true),str('inspectionType',64,true),datetime('scheduledAt'),datetime('completedAt'),text('result')], [index('site_status',['managedSiteId','status']),index('inspector_schedule',['inspectorId','scheduledAt'])]),
  agencyEntity('assets', [str('managedSiteId',36,true),str('propertyId',36),str('assetType',64,true),str('name',255,true),str('serialNumber',128),datetime('installedAt'),datetime('warrantyUntil'),text('metadata')], [index('site_type_status',['managedSiteId','assetType','status']),index('property_status',['propertyId','status'])]),
  agencyEntity('maintenance_plans', [str('managedSiteId',36,true),str('assetId',36),str('name',255,true),str('cadence',64,true),datetime('nextDueAt'),text('tasks')], [index('site_next_due',['managedSiteId','nextDueAt']),index('asset_status',['assetId','status'])]),
  agencyEntity('waste_events', [str('managedSiteId',36,true),str('eventType',64,true),datetime('occurredAt',true),str('reportedBy',36),text('details',true)], [index('site_occurred',['managedSiteId','occurredAt'])]),
  agencyEntity('incidents', [str('managedSiteId',36,true),str('propertyId',36),str('incidentType',64,true),str('severity',32,true),datetime('occurredAt',true),str('reportedBy',36),text('description',true),text('resolution')], [index('site_status',['managedSiteId','status']),index('site_severity',['managedSiteId','severity']),index('property_status',['propertyId','status'])]),
  agencyEntity('bylaw_observations', [str('managedSiteId',36,true),str('propertyId',36),str('bylawReference',128),datetime('observedAt',true),str('observedBy',36),text('description',true),text('resolution')], [index('site_status',['managedSiteId','status']),index('property_status',['propertyId','status'])]),
  agencyEntity('notices', [str('managedSiteId',36,true),str('noticeType',64,true),str('title',255,true),text('content',true),datetime('publishedAt'),datetime('expiresAt'),str('publishedBy',36)], [index('site_status',['managedSiteId','status']),index('site_published',['managedSiteId','publishedAt'])]),
  agencyEntity('communications', [str('managedSiteId',36),str('channel',32,true),str('recipientType',64),str('recipientId',36),str('subject',255),text('content'),str('deliveryStatus',64),datetime('sentAt')], [index('site_created',['managedSiteId','createdAt']),index('recipient_created',['recipientId','createdAt'])]),
  agencyEntity('handovers', [str('managedSiteId',36,true),str('fromUserId',36,true),str('toUserId',36,true),datetime('handoverAt',true),text('summary',true)], [index('site_handover',['managedSiteId','handoverAt'])]),
  agencyEntity('handover_checklist_items', [str('handoverId',36,true),str('title',255,true),str('itemStatus',32,true),str('completedBy',36),datetime('completedAt'),text('notes')], [index('handover_status',['handoverId','itemStatus'])]),
  agencyEntity('operational_report_drafts', [str('managedSiteId',36,true),str('period',32,true),str('preparedBy',36,true),integer('version',true),text('content',true)], [unique('site_period_version',['managedSiteId','period','version']),index('site_status',['managedSiteId','status'])]),
  agencyEntity('operational_reports', [str('managedSiteId',36,true),str('period',32,true),str('draftId',36),str('fileId',36,true),str('contentHash',128,true),str('finalisedBy',36,true),datetime('finalisedAt',true),boolean('immutable',true)], [unique('site_period',['managedSiteId','period']),index('site_finalised',['managedSiteId','finalisedAt'])]),

  agencyEntity('audit_events', [str('managedSiteId',36),str('actorUserId',36),str('actorType',64,true),str('action',128,true),str('entityType',64,true),str('entityId',36,true),str('source',64,true),text('previousState'),text('newState'),str('requestId',128),str('correlationId',128,true),str('ipAddress',64),str('userAgent',1024),datetime('createdAt',true)], [index('agency_created',['agencyId','createdAt']),index('entity_created',['entityType','entityId','createdAt']),index('correlation',['correlationId'])]),
  agencyEntity('integration_connections', [str('provider',64,true),str('externalAccountId',255),str('credentialReference',255),datetime('lastSuccessfulAt'),datetime('lastAttemptedAt'),text('configuration'),text('lastError')], [unique('agency_provider',['agencyId','provider']),index('provider_status',['provider','status'])]),
  agencyEntity('integration_events', [str('provider',64,true),str('eventType',128,true),str('externalEventId',255,true),str('deduplicationId',255,true),str('payloadReference',512),str('processingStatus',64,true),integer('attempts',true),text('errorState'),datetime('firstReceivedAt',true),datetime('lastAttemptedAt'),datetime('processedAt')], [unique('provider_dedup',['agencyId','provider','deduplicationId']),index('status_attempted',['processingStatus','lastAttemptedAt'])]),
  agencyEntity('integration_deliveries', [str('provider',64,true),str('eventId',36),str('externalDeliveryId',255,true),str('deliveryStatus',64,true),integer('attempts',true),datetime('lastAttemptedAt'),datetime('deliveredAt'),text('errorState')], [unique('provider_delivery',['agencyId','provider','externalDeliveryId']),index('status_attempted',['deliveryStatus','lastAttemptedAt'])]),
  agencyEntity('integration_exceptions', [str('provider',64,true),str('category',64,true),str('severity',32,true),str('entityType',64),str('entityId',36),text('detail',true),text('resolution'),datetime('resolvedAt')], [index('provider_severity',['provider','severity'])]),
  agencyEntity('integration_outbox', [str('eventType',128,true),str('entityType',64,true),str('entityId',36,true),text('payload',true),str('deliveryStatus',64,true),integer('attempts',true),datetime('availableAt',true),datetime('lastAttemptedAt')], [index('status_available',['deliveryStatus','availableAt']),index('entity',['entityType','entityId'])]),
  agencyEntity('evidence_files', [str('bucketId',36,true),str('fileId',36,true),str('managedSiteId',36),str('propertyId',36),str('entityType',64,true),str('entityId',36,true),str('category',64),str('mimeType',255,true),str('originalFilename',512,true),integer('size',true),str('checksum',128,true),str('uploadedBy',36,true),datetime('capturedAt'),str('legacyFileId',255)], [unique('bucket_file',['bucketId','fileId']),index('entity_created',['entityType','entityId','createdAt']),index('property_created',['propertyId','createdAt'])]),
  table('migration_id_map', [str('sourceSystem',64,true),str('sourceEntity',128,true),str('sourceId',255,true),str('targetTable',36,true),str('targetId',36),str('sourceChecksum',128,true),str('migratedChecksum',128),str('migrationVersion',64,true),datetime('migratedAt'),str('status',32,true),text('error')], [unique('source_identity',['sourceSystem','sourceEntity','sourceId']),index('status_source',['status','sourceSystem']),index('target',['targetTable','targetId'])]),
];

export const expectedTableIds = tables.map((item) => item.$id);
