const str = (key, size = 255, required = false, format) => ({ key, type: 'string', size, required, ...(format ? { format } : {}) });
const text = (key, required = false) => ({ key, type: 'longtext', required });
const datetime = (key, required = false) => ({ key, type: 'datetime', required });
const integer = (key, required = false) => ({ key, type: 'integer', required });
const number = (key, required = false) => ({ key, type: 'double', required });
const boolean = (key, required = false) => ({ key, type: 'boolean', required });
const index = (key, columns, orders) => ({ key, type: 'key', columns, ...(orders ? { orders } : {}) });
const unique = (key, columns) => ({ key, type: 'unique', columns });

const timestamps = [datetime('createdAt', true), datetime('updatedAt', true)];
const auditActors = [str('createdBy', 36), str('updatedBy', 36)];
const legacy = [str('legacySystem', 32), str('legacyId', 128)];
const agencyBase = [str('agencyId', 36, true), str('status', 64, true), ...timestamps, ...auditActors, ...legacy];

function table(id, columns, indexes = []) {
  const uniqueColumns = [...new Map(columns.map((column) => [column.key, column])).values()];
  return { $id: id, databaseId: 'proinspect_core', name: id.split('_').map((part) => part[0].toUpperCase() + part.slice(1)).join(' '), $permissions: [], rowSecurity: true, enabled: true, columns: uniqueColumns, indexes };
}

function agencyEntity(id, columns = [], indexes = []) {
  return table(id, [...agencyBase, ...columns], [index('agency_status', ['agencyId', 'status']), ...indexes]);
}

export const tables = [
  table('agencies', [str('name', 255, true), str('code', 64, true), str('status', 32, true), str('timezone', 64, true), ...timestamps, ...auditActors], [unique('agency_code', ['code']), index('status_name', ['status', 'name'])]),
  agencyEntity('managed_sites', [str('name',255,true),str('siteType',64,true),str('timezone',64,true),str('streetAddress',512),str('suburb',128),str('state',64),str('postcode',16),str('country',64),str('strataPlanNumber',128),str('schemeName',255),str('externalReference',128)], [index('agency_name',['agencyId','name'])]),
  table('user_profiles', [str('userId',36,true),str('displayName',255,true),str('preferredName',128),str('email',320,true,'email'),str('phone',32),str('status',32,true),...timestamps,...legacy], [unique('user_id',['userId']),index('status_email',['status','email'])]),
  table('agency_memberships', [str('userId',36,true),str('agencyId',36,true),str('role',64,true),str('status',32,true),datetime('validFrom'),datetime('validUntil'),boolean('mfaRequired',true),...timestamps], [unique('user_agency',['userId','agencyId']),index('agency_role_status',['agencyId','role','status'])]),
  table('site_memberships', [str('userId',36,true),str('agencyId',36,true),str('managedSiteId',36,true),str('role',64,true),str('status',32,true),datetime('validFrom'),datetime('validUntil'),...timestamps], [unique('user_site',['userId','managedSiteId']),index('site_role_status',['managedSiteId','role','status']),index('agency_user',['agencyId','userId'])]),
  agencyEntity('clients', [str('name',255,true),str('legalName',255),str('tradingName',255),str('abn',32),str('clientType',64),str('accountType',64),str('billingMethod',64),str('billingEmail',320,false,'email'),str('shopifyCustomerId',128),text('contactDetails'),text('billingProfile'),text('inspectionPreferences'),text('maintenancePolicy'),text('externalReferences')], [index('agency_name',['agencyId','name']),index('shopify_customer',['shopifyCustomerId'])]),
  agencyEntity('client_contacts', [str('clientId',36,true),str('name',255,true),str('email',320,false,'email'),str('phone',32),str('role',64),text('roles'),boolean('primary',true),boolean('receivesReports'),boolean('receivesAccounts'),boolean('receivesMaintenance'),text('communicationPreferences')], [index('client_status',['clientId','status']),index('agency_email',['agencyId','email'])]),
  agencyEntity('properties', [str('managedSiteId',36),str('clientId',36),str('propertyType',64,true),str('propertyUse',64,true),str('ownershipStructure',64,true),str('streetAddress',512,true),str('suburb',128),str('state',64),str('postcode',16),str('country',64),str('lotNumber',64),str('unitNumber',64),str('buildingName',255),str('strataPlanNumber',128),str('externalReference',128),text('strataDetails')], [index('agency_site_status',['agencyId','managedSiteId','status']),index('client_status',['clientId','status']),index('site_unit',['managedSiteId','unitNumber'])]),
  agencyEntity('buildings', [str('managedSiteId',36,true),str('sourcePropertyId',36),str('name',255,true),str('code',64),integer('sequence')], [index('site_sequence',['managedSiteId','sequence']),index('source_property',['sourcePropertyId'])]),
  agencyEntity('property_levels', [str('managedSiteId',36,true),str('buildingId',36,true),str('name',128,true),str('code',64),integer('sequence')], [index('building_sequence',['buildingId','sequence'])]),
  agencyEntity('property_areas', [str('managedSiteId',36),str('propertyId',36),str('buildingId',36),str('levelId',36),str('name',255,true),str('areaType',64),str('locationType',64),str('levelLabel',80),str('responsibility',64),str('exclusiveUseUnitId',36),integer('sequence')], [index('property_sequence',['propertyId','sequence']),index('level_sequence',['levelId','sequence']),index('site_type',['managedSiteId','locationType'])]),

  agencyEntity('service_definitions', [str('code',64,true),str('name',255,true),str('category',64,true),str('workflowType',64,true),text('description'),text('defaultConfiguration')], [unique('agency_code',['agencyId','code']),index('workflow_status',['workflowType','status'])]),
  agencyEntity('service_requests', [str('managedSiteId',36),str('propertyId',36),str('clientId',36),str('serviceDefinitionId',36,true),str('source',64,true),str('sourceReference',255,true),str('requestedByUserId',36),str('requestedForName',255),str('requestedForEmail',320,false,'email'),str('requestedForPhone',32),str('paymentStatus',64,true),str('schedulingStatus',64,true),str('priority',32,true),datetime('requestedDate'),text('notes'),text('accessInstructions')], [index('agency_status_created',['agencyId','status','createdAt'],['ASC','ASC','DESC']),unique('source_reference',['agencyId','source','sourceReference']),index('property_created',['propertyId','createdAt'],['ASC','DESC'])]),
  agencyEntity('service_request_items', [str('serviceRequestId',36,true),str('serviceDefinitionId',36,true),integer('quantity',true),str('status',64,true),text('configuration')], [index('request_status',['serviceRequestId','status'])]),
  agencyEntity('shopify_service_mappings', [str('shopDomain',255),str('shopifyProductId',128,true),str('shopifyVariantId',128),str('serviceDefinitionId',36,true),boolean('active',true),text('mappingConfiguration')], [unique('agency_variant',['agencyId','shopifyProductId','shopifyVariantId']),index('service_active',['serviceDefinitionId','active'])]),

  agencyEntity('inspection_requests', [str('serviceRequestId',36),str('propertyId',36),str('inspectionType',128),str('source',64,true),str('sourceReference',255),str('paymentStatus',64),str('schedulingStatus',64),str('priority',32),text('shopifyReference'),text('calendarReference')], [index('agency_status_created',['agencyId','status','createdAt']),index('property_status',['propertyId','status'])]),
  agencyEntity('inspection_jobs', [str('inspectionRequestId',36),str('serviceRequestId',36),str('propertyId',36,true),str('inspectorId',36),str('analystId',36),str('reviewerId',36),str('inspectionType',128,true),datetime('scheduledDate'),str('priority',32),integer('version',true),text('propertySnapshot')], [index('inspector_schedule',['inspectorId','scheduledDate']),index('analyst_status',['analystId','status']),index('reviewer_status',['reviewerId','status']),index('property_status',['propertyId','status'])]),
  agencyEntity('inspection_templates', [str('code',64,true),str('name',255,true),str('templateKind',64),str('inspectionType',128,true),str('currentVersionId',36)], [unique('agency_code',['agencyId','code']),index('type_status',['inspectionType','status'])]),
  agencyEntity('inspection_template_versions', [str('templateId',36,true),integer('version',true),str('contentHash',128,true),text('definition',true),datetime('publishedAt'),boolean('immutable',true)], [unique('template_version',['templateId','version'])]),
  agencyEntity('inspections', [str('inspectionJobId',36,true),str('propertyId',36,true),str('inspectorId',36,true),datetime('startedAt'),datetime('submittedAt'),integer('version',true)], [unique('inspection_job',['inspectionJobId']),index('inspector_status',['inspectorId','status'])]),
  agencyEntity('inspection_sections', [str('inspectionId',36,true),str('areaId',36),str('canonicalAreaId',36),str('canonicalAreaVersionId',36),str('name',255,true),str('responsibility',64),integer('sequence',true),str('status',64)], [index('inspection_sequence',['inspectionId','sequence'])]),
  agencyEntity('observations', [str('inspectionId',36,true),str('sectionId',36,true),str('componentId',36),str('canonicalComponentId',36),str('canonicalComponentVersionId',36),str('condition',64),str('cleanliness',64),str('workingStatus',64),str('testingStatus',64),text('testRecord'),text('commentary'),boolean('maintenanceRequired'),str('responsibility',64)], [index('inspection_section',['inspectionId','sectionId']),index('component_condition',['componentId','condition'])]),
  agencyEntity('inspection_evidence', [str('inspectionId',36,true),str('observationId',36),str('evidenceFileId',36,true),str('category',64),integer('sequence')], [index('inspection_sequence',['inspectionId','sequence']),index('observation',['observationId'])]),
  agencyEntity('reports', [str('inspectionJobId',36),str('propertyId',36,true),str('inspectorId',36),str('analystId',36),str('reviewerId',36),str('currentVersionId',36),str('lifecycleStatus',64,true),integer('version',true),datetime('finalisedAt'),str('finalisedBy',36)], [index('property_status',['propertyId','lifecycleStatus']),index('job_status',['inspectionJobId','lifecycleStatus']),index('analyst_status',['analystId','lifecycleStatus']),index('reviewer_status',['reviewerId','lifecycleStatus'])]),
  agencyEntity('report_versions', [str('reportId',36,true),integer('version',true),str('contentHash',128,true),str('fileId',36),text('snapshot'),boolean('immutable',true),datetime('finalisedAt'),str('supersedesVersionId',36)], [unique('report_version',['reportId','version']),index('report_finalised',['reportId','finalisedAt'])]),

  agencyEntity('maintenance_candidates', [str('propertyId',36,true),str('inspectionJobId',36),str('reportId',36),str('observationId',36),str('canonicalAreaId',36),str('canonicalAreaVersionId',36),str('canonicalComponentId',36),str('canonicalComponentVersionId',36),str('title',255,true),text('description',true),str('category',64,true),str('priority',32,true),number('confidence'),str('confirmedItemId',36)], [index('property_status',['propertyId','status']),index('report_status',['reportId','status'])]),
  agencyEntity('maintenance_items', [str('managedSiteId',36),str('propertyId',36,true),str('candidateId',36),str('assignedContractorId',36),str('assignedUserId',36),str('title',255,true),text('description',true),str('category',64,true),str('priority',32,true),str('approvalStatus',64),datetime('dueDate'),integer('version',true)], [index('site_status',['managedSiteId','status']),index('site_priority_status',['managedSiteId','priority','status']),index('property_status',['propertyId','status']),index('contractor_status',['assignedContractorId','status']),index('assignee_status',['assignedUserId','status'])]),
  agencyEntity('maintenance_quotes', [str('maintenanceItemId',36,true),str('contractorId',36),str('currency',3),number('amount'),str('approvalStatus',64),datetime('validUntil'),text('scope')], [index('item_status',['maintenanceItemId','status']),index('contractor_status',['contractorId','status'])]),
  agencyEntity('maintenance_estimates', [str('maintenanceItemId',36,true),str('currency',3),number('amount'),text('basis'),datetime('validUntil')], [index('item_status',['maintenanceItemId','status'])]),
  agencyEntity('maintenance_approvals', [str('maintenanceItemId',36,true),str('quoteId',36),str('approvedBy',36),str('decision',32,true),text('reason'),datetime('decidedAt')], [index('item_decision',['maintenanceItemId','decision'])]),
  agencyEntity('client_approvals', [str('propertyId',36,true),str('maintenanceItemId',36,true),str('clientId',36,true),str('clientContactId',36),str('recipientEmail',320,true,'email'),text('summary',true),text('recommendedAction',true),str('priority',32,true),text('evidencePhotoIds'),text('clientNotes'),datetime('respondedAt'),str('accessGrantId',36),str('quoteId',36),str('quoteVersionId',36),str('quoteNumber',128),number('amount'),str('currency',3),datetime('quoteExpiresAt'),datetime('decisionTokenVerifiedAt'),integer('version',true)], [index('item_status',['maintenanceItemId','status']),index('client_status',['clientId','status']),index('recipient_status',['recipientEmail','status'])]),
  agencyEntity('maintenance_work_orders', [str('maintenanceItemId',36,true),str('quoteId',36),str('contractorId',36),str('assignedInternalUserId',36),str('priority',32),datetime('dueDate'),datetime('completedAt'),text('instructions'),integer('version',true)], [index('item_status',['maintenanceItemId','status']),index('contractor_status',['contractorId','status']),index('due_status',['dueDate','status'])]),
  agencyEntity('maintenance_variations', [str('workOrderId',36,true),number('amount'),str('currency',3),str('approvalStatus',64),text('reason',true)], [index('work_order_status',['workOrderId','status'])]),
  agencyEntity('preventive_maintenance', [str('managedSiteId',36),str('propertyId',36),str('assetId',36),str('cadence',64,true),datetime('nextDueAt',true),text('instructions')], [index('site_next_due',['managedSiteId','nextDueAt']),index('property_status',['propertyId','status'])]),
  agencyEntity('warranty_claims', [str('maintenanceItemId',36),str('assetId',36),str('provider',255),str('reference',128),datetime('lodgedAt'),text('details')], [index('item_status',['maintenanceItemId','status']),index('asset_status',['assetId','status'])]),
  agencyEntity('contractor_quote_requests', [str('maintenanceItemId',36,true),str('contractorId',36,true),datetime('dueAt'),text('scope',true)], [index('item_status',['maintenanceItemId','status']),index('contractor_status',['contractorId','status'])]),
  agencyEntity('contractor_quotes', [str('quoteRequestId',36,true),str('maintenanceItemId',36,true),str('contractorId',36,true),number('amount'),str('currency',3),text('scope'),datetime('submittedAt')], [index('item_status',['maintenanceItemId','status']),index('contractor_status',['contractorId','status'])]),
  agencyEntity('work_requests', [str('maintenanceItemId',36,true),str('externalContactId',36,true),str('priority',32),datetime('dueDate'),text('instructions',true),text('responseNotes')], [index('item_status',['maintenanceItemId','status']),index('contact_status',['externalContactId','status'])]),
  agencyEntity('tenant_instructions', [str('propertyId',36,true),str('tenancyId',36,true),str('maintenanceItemId',36),str('instructionType',64,true),str('title',255,true),text('instruction',true),datetime('dueDate')], [index('tenancy_status',['tenancyId','status']),index('item_status',['maintenanceItemId','status'])]),
  agencyEntity('external_contacts', [str('name',255,true),str('businessName',255),str('email',320,false,'email'),str('phone',32),str('contactType',64,true)], [index('agency_type_status',['agencyId','contactType','status']),index('email',['email'])]),

  agencyEntity('daily_activity_logs', [str('managedSiteId',36,true),str('authorUserId',36,true),datetime('activityDate',true),datetime('occurredAt'),str('category',64),text('summary',true),text('actionTaken'),str('propertyAreaId',36),str('buildingId',36),str('levelLabel',80),str('specificLocation',255),str('unitId',36),str('contractorId',36),boolean('followUpRequired'),datetime('followUpDate'),str('responsibleParty',64),str('priority',32),integer('minutesSpent'),str('evidenceFileId',36),text('additionalNotes'),str('sourceEntityType',64),str('sourceEntityId',36),str('clientSubmissionId',128)], [index('site_activity_date',['managedSiteId','activityDate']),index('site_follow_up',['managedSiteId','followUpRequired','followUpDate'])]),
  agencyEntity('resident_requests', [str('managedSiteId',36,true),str('propertyId',36),str('unitId',36),str('requestedByPersonId',36),str('residentUserId',36,true),str('requestType',64,true),str('category',64),str('priority',32),str('urgency',32),str('assignedUserId',36),str('contactPreference',64),boolean('accessPermission'),text('accessInstructions'),text('description',true),str('defectId',36),str('clientSubmissionId',128)], [index('site_status',['managedSiteId','status']),index('resident_status',['residentUserId','status']),index('person_status',['requestedByPersonId','status'])]),
  agencyEntity('contractor_attendance', [str('managedSiteId',36,true),str('contractorId',36,true),str('contractorUserId',36),str('workOrderId',36),str('visitorName',255),str('visitorMobile',64),str('visitorEmail',320,false,'email'),text('purpose'),str('areaAccessed',255),str('residentUnitId',36),integer('expectedDurationMinutes'),str('accessItemType',64),str('accessItemIdentifier',128),str('vehicleRegistration',64),str('parkingLocation',128),boolean('siteRulesAcknowledged'),datetime('checkedInAt',true),datetime('checkedOutAt'),str('checkedInBy',36),boolean('workCompleted'),text('workDescription'),text('additionalDefects'),boolean('furtherAttendanceRequired'),boolean('quoteOrReportToFollow'),boolean('keysReturned'),boolean('areaLeftClean'),boolean('bmInspected'),text('signoutNotes'),str('serviceReportEvidenceId',36)], [index('site_checkin',['managedSiteId','checkedInAt']),index('contractor_checkin',['contractorId','checkedInAt']),index('site_status',['managedSiteId','status'])]),
  agencyEntity('key_transactions', [str('managedSiteId',36,true),str('keyId',36,true),str('contractorAttendanceId',36),str('issuedTo',255),str('holderType',64),str('holderId',36),str('transactionType',64,true),datetime('occurredAt',true),str('authorisedBy',36),text('notes')], [index('key_occurred',['keyId','occurredAt']),index('site_occurred',['managedSiteId','occurredAt']),index('attendance',['contractorAttendanceId'])]),
  agencyEntity('access_devices', [str('managedSiteId',36,true),str('propertyId',36),str('unitId',36),str('personId',36),str('requestId',36),str('deviceType',64,true),str('identifier',128,true),str('assignedToUserId',36),str('accessProfile',128),boolean('identityChecked'),str('collectedBy',255),datetime('issuedAt'),str('systemReference',128),str('programmingReference',128),datetime('activatedAt'),datetime('deactivatedAt'),str('replacementDeviceId',36)], [unique('site_identifier',['managedSiteId','identifier']),index('property_status',['propertyId','status']),index('request_status',['requestId','status'])]),
  agencyEntity('access_device_history', [str('accessDeviceId',36,true),str('action',64,true),str('actorUserId',36),str('assignedToUserId',36),datetime('occurredAt',true),text('notes')], [index('device_occurred',['accessDeviceId','occurredAt'])]),
  agencyEntity('move_bookings', [str('managedSiteId',36,true),str('propertyId',36,true),str('unitId',36),str('requestedByPersonId',36),str('residentUserId',36),str('moveType',32,true),datetime('requestedAt'),datetime('startAt',true),datetime('endAt',true),str('removalistName',255),str('vehicleRegistration',64),integer('vehicleHeightMm'),str('liftRequired',32),str('loadingZoneRequired',32),text('conditions'),text('specialRequirements'),str('approvalStatus',64),text('declineReason'),str('approvedBy',36),datetime('approvedAt'),datetime('preMoveInspectionAt'),datetime('postMoveInspectionAt'),boolean('damageRecorded'),boolean('keysReturned'),datetime('closedAt')], [index('site_start',['managedSiteId','startAt']),index('property_status',['propertyId','status']),index('unit_status',['unitId','status'])]),
  agencyEntity('resident_onboarding', [str('managedSiteId',36,true),str('propertyId',36,true),str('unitId',36),str('personId',36),str('occupancyId',36),str('residentUserId',36,true),str('residentName',255),str('residentRole',64),str('occupancyType',64),datetime('moveInDate'),datetime('inductedAt'),str('inductedBy',36),text('modules'),text('checklist'),boolean('rulesAcknowledged'),str('acknowledgementName',255),text('questionsRaised'),text('outstandingMatters'),text('bmNotes')], [index('site_resident',['managedSiteId','residentUserId']),index('property_status',['propertyId','status']),index('occupancy',['occupancyId'])]),
  agencyEntity('operational_inspections', [str('managedSiteId',36,true),str('propertyId',36),str('templateId',36),str('inspectorId',36,true),str('inspectionType',64,true),datetime('scheduledAt'),datetime('startedAt'),datetime('completedAt'),text('summary'),text('result')], [index('site_status',['managedSiteId','status']),index('inspector_schedule',['inspectorId','scheduledAt'])]),
  agencyEntity('assets', [str('sourceType',64),str('managedSiteId',36,true),str('propertyId',36),str('propertyAreaId',36),str('assetType',64,true),str('name',255,true),str('manufacturer',255),str('model',128),str('serialNumber',128),datetime('commissionedAt'),datetime('installedAt'),datetime('warrantyUntil'),str('criticality',32),str('responsibleContractorId',36),str('qrCode',128),text('metadata')], [index('site_type_status',['managedSiteId','assetType','status']),index('property_status',['propertyId','status'])]),
  agencyEntity('maintenance_plans', [str('managedSiteId',36,true),str('assetId',36),str('responsibleContractorId',36),str('name',255,true),str('cadence',64,true),integer('frequencyDays'),datetime('lastServicedAt'),datetime('nextDueAt'),text('scope'),text('evidenceRequirements'),text('reminderConfiguration'),text('tasks')], [index('site_next_due',['managedSiteId','nextDueAt']),index('asset_status',['assetId','status'])]),
  agencyEntity('waste_events', [str('managedSiteId',36,true),str('wasteServiceId',36),str('unitId',36),str('eventType',64,true),str('wasteType',64),str('activity',64),number('quantity'),str('condition',64),str('responsibleUnit',64),datetime('occurredAt',true),str('reportedBy',36),text('issue'),text('actionTaken'),datetime('collectionAt'),str('evidenceFileId',36),text('details',true)], [index('site_occurred',['managedSiteId','occurredAt']),index('site_type',['managedSiteId','wasteType'])]),
  agencyEntity('incidents', [str('managedSiteId',36,true),str('propertyId',36),str('unitId',36),str('personId',36),str('incidentType',64,true),str('severity',32,true),str('riskLevel',32),datetime('occurredAt',true),str('reportedBy',36),str('reportedByName',255),text('description',true),text('immediateActions'),boolean('emergencyServicesCalled'),text('damageDetails'),text('temporaryRepair'),str('defectId',36),text('witnesses'),text('cctvDetails'),str('policeReference',128),boolean('strataNotified'),datetime('followUpAt'),text('resolution'),str('evidenceFileId',36)], [index('site_status',['managedSiteId','status']),index('site_severity',['managedSiteId','severity']),index('property_status',['propertyId','status']),index('site_follow_up',['managedSiteId','followUpAt'])]),
  agencyEntity('bylaw_observations', [str('managedSiteId',36,true),str('propertyId',36),str('unitId',36),str('bylawReference',128),str('category',64),datetime('observedAt',true),str('observedBy',36),str('specificLocation',255),text('description',true),str('decision',64),str('outcome',64),str('decidedBy',36),text('actionTaken'),str('evidenceFileId',36),datetime('followUpAt'),text('resolution')], [index('site_status',['managedSiteId','status']),index('property_status',['propertyId','status']),index('site_follow_up',['managedSiteId','followUpAt'])]),
  agencyEntity('notices', [str('managedSiteId',36,true),str('noticeType',64,true),str('title',255,true),text('content',true),datetime('publishedAt'),datetime('expiresAt'),str('publishedBy',36)], [index('site_status',['managedSiteId','status']),index('site_published',['managedSiteId','publishedAt'])]),
  agencyEntity('communications', [str('managedSiteId',36),str('channel',32,true),str('recipientType',64),str('recipientId',36),str('subject',255),text('content'),str('deliveryStatus',64),datetime('sentAt')], [index('site_created',['managedSiteId','createdAt']),index('recipient_created',['recipientId','createdAt'])]),
  agencyEntity('handovers', [str('managedSiteId',36,true),str('fromUserId',36,true),str('toUserId',36,true),datetime('handoverAt',true),text('summary',true)], [index('site_handover',['managedSiteId','handoverAt'])]),
  agencyEntity('handover_checklist_items', [str('handoverId',36,true),str('title',255,true),str('itemStatus',32,true),str('completedBy',36),datetime('completedAt'),text('notes')], [index('handover_status',['handoverId','itemStatus'])]),
  agencyEntity('operational_report_drafts', [str('managedSiteId',36,true),str('period',32,true),str('title',255),str('preparedBy',36,true),integer('version',true),text('commentary'),text('snapshot'),text('content',true),datetime('generatedAt'),datetime('finalisedAt')], [unique('site_period_version',['managedSiteId','period','version']),index('site_status',['managedSiteId','status'])]),
  agencyEntity('operational_reports', [str('managedSiteId',36,true),str('period',32,true),str('draftId',36),str('fileId',36,true),str('contentHash',128,true),text('snapshot'),str('finalisedBy',36,true),datetime('finalisedAt',true),boolean('immutable',true),str('supersedesReportId',36)], [unique('site_period',['managedSiteId','period']),index('site_finalised',['managedSiteId','finalisedAt'])]),

  agencyEntity('people', [str('fullName',255,true),str('email',320,false,'email'),str('phone',64),str('appwriteUserId',36)], [index('agency_email',['agencyId','email']),index('user',['appwriteUserId'])]),
  agencyEntity('people_invitations', [str('userId',36,true),str('email',320,true,'email'),str('displayName',255),str('role',64,true),boolean('mfaRequired',true),datetime('expiresAt',true),str('invitedBy',36,true),datetime('acceptedAt'),datetime('cancelledAt')], [index('agency_email_status',['agencyId','email','status']),index('user_status',['userId','status']),index('expiry_status',['expiresAt','status'])]),
  agencyEntity('workforce_profiles', [str('userId',36,true),boolean('active',true),text('disciplines',true),text('inspectionTypes',true),text('propertyUses',true),text('serviceAreas',true),boolean('commercialQualified',true),boolean('strataQualified',true),integer('maxJobsPerDay'),integer('maxActiveAnalyses'),integer('maxActiveReviews'),str('defaultCalendarId',128),text('workingHours'),text('unavailableDates'),integer('version',true)], [unique('agency_user',['agencyId','userId']),index('active_user',['active','userId'])]),
  agencyEntity('tenants', [str('personId',36),str('userId',36),str('displayName',255,true),str('email',320,false,'email'),str('phone',64)], [index('agency_email',['agencyId','email']),index('user_status',['userId','status'])]),
  agencyEntity('tenancies', [str('managedSiteId',36),str('propertyId',36,true),str('primaryTenantId',36),str('landlordPersonId',36),str('lifecycleStatus',64,true),datetime('startDate'),datetime('endDate'),datetime('noticeDate'),text('terms')], [index('property_lifecycle',['propertyId','lifecycleStatus']),index('site_lifecycle',['managedSiteId','lifecycleStatus'])]),
  agencyEntity('tenancy_participants', [str('tenancyId',36,true),str('tenantId',36),str('personId',36),str('role',64,true),datetime('startDate'),datetime('endDate')], [index('tenancy_status',['tenancyId','status']),index('person_status',['personId','status'])]),
  agencyEntity('occupancies', [str('managedSiteId',36,true),str('unitId',36,true),str('personId',36,true),str('userId',36),str('tenancyId',36),str('occupancyRole',64,true),datetime('startDate'),datetime('endDate'),boolean('current',true)], [index('unit_current',['unitId','current']),index('person_current',['personId','current']),index('site_current',['managedSiteId','current'])]),
  agencyEntity('units', [str('managedSiteId',36,true),str('buildingId',36),str('propertyId',36),str('unitNumber',64,true),str('lotNumber',64),str('levelLabel',80),str('unitType',64)], [unique('site_unit',['managedSiteId','unitNumber']),index('building_unit',['buildingId','unitNumber']),index('property_status',['propertyId','status'])]),
  agencyEntity('contractors', [str('companyName',255,true),str('contactName',255),str('contactEmail',320,false,'email'),str('contactPhone',64),str('tradeCategory',128),str('licenceNumber',128),datetime('insuranceExpiresAt'),text('complianceDetails'),boolean('emergencyAvailable'),text('sitesCovered'),text('accessPermissions')], [index('agency_company',['agencyId','companyName']),index('trade_status',['tradeCategory','status'])]),
  agencyEntity('property_client_relationships', [str('propertyId',36,true),str('clientId',36,true),str('relationshipType',64,true),boolean('primary',true),datetime('startDate'),datetime('endDate'),text('serviceScope')], [unique('property_client_type',['propertyId','clientId','relationshipType']),index('client_status',['clientId','status'])]),
  agencyEntity('key_register', [str('managedSiteId',36,true),str('description',255,true),str('identifier',128),str('storageLocation',255),str('custodyStatus',64,true),str('currentHolderType',64),str('currentHolderId',36),str('currentHolderName',255)], [unique('site_identifier',['managedSiteId','identifier']),index('site_custody',['managedSiteId','custodyStatus'])]),
  agencyEntity('access_device_requests', [str('managedSiteId',36,true),str('unitId',36,true),str('requestedByPersonId',36),str('requestType',64,true),str('requesterRole',64),str('ownerAuthorisationStatus',64),str('paymentReference',128),datetime('collectionAppointmentAt'),str('applicantName',255),str('managingAgentName',255),str('contactPhone',64),str('contactEmail',320,false,'email'),str('deviceTypeRequested',64),integer('quantityRequested'),text('requestReason'),str('authorisationEvidenceFileId',36),datetime('requestedCollectionDate'),text('internalNotes'),str('clientSubmissionId',128)], [index('site_status',['managedSiteId','status']),index('unit_status',['unitId','status']),index('person_status',['requestedByPersonId','status'])]),
  agencyEntity('defects', [str('managedSiteId',36,true),str('propertyAreaId',36),str('unitId',36),str('assetId',36),str('source',64,true),str('sourceResidentRequestId',36),str('sourceInspectionId',36),str('sourceIncidentId',36),str('category',64,true),text('description',true),str('riskLevel',32),str('priority',32),boolean('commonProperty'),text('immediateResponse'),str('assignedUserId',36),str('assignedContractorId',36),boolean('quoteRequired'),datetime('dueDate'),boolean('strataApprovalRequired'),text('workCompletedNotes'),number('completionCost'),datetime('nextFollowUpDate'),str('verifiedBy',36),datetime('verifiedAt'),str('maintenanceItemId',36)], [index('site_status',['managedSiteId','status']),index('site_follow_up',['managedSiteId','nextFollowUpDate']),index('contractor_status',['assignedContractorId','status'])]),
  agencyEntity('operational_inspection_checkpoints', [str('templateId',36,true),str('name',255,true),str('category',64),integer('sequence',true),boolean('evidenceRequired'),text('instructions')], [index('template_sequence',['templateId','sequence'])]),
  agencyEntity('operational_inspection_results', [str('operationalInspectionId',36,true),str('checkpointId',36,true),str('propertyAreaId',36),str('result',64,true),str('riskLevel',32),text('notes'),boolean('actionRequired'),boolean('maintenanceRequired'),datetime('followUpAt'),str('evidenceFileId',36),str('defectId',36)], [index('inspection_checkpoint',['operationalInspectionId','checkpointId']),index('inspection_result',['operationalInspectionId','result'])]),
  agencyEntity('service_events', [str('managedSiteId',36,true),str('maintenancePlanId',36),str('workOrderId',36),datetime('scheduledAt'),datetime('completedAt'),str('completedBy',36),str('verifiedBy',36),datetime('verifiedAt'),text('evidenceRequirements')], [index('site_schedule',['managedSiteId','scheduledAt']),index('plan_status',['maintenancePlanId','status'])]),
  agencyEntity('waste_services', [str('managedSiteId',36,true),str('wasteStream',64,true),str('collectionDay',32),str('provider',255),text('notes')], [index('site_stream',['managedSiteId','wasteStream'])]),
  agencyEntity('tasks', [str('managedSiteId',36,true),str('title',255,true),str('taskType',64,true),str('linkedEntityType',64),str('linkedEntityId',36),datetime('dueAt'),str('priority',32),str('assigneeUserId',36),str('assigneeRole',64),datetime('completedAt'),str('completionEvidenceFileId',36)], [index('site_status',['managedSiteId','status']),index('due_status',['dueAt','status']),index('assignee_status',['assigneeUserId','status'])]),
  agencyEntity('calendar_events', [str('managedSiteId',36,true),str('eventType',64,true),str('linkedEntityType',64),str('linkedEntityId',36),str('title',255,true),datetime('startAt',true),datetime('endAt'),boolean('allDay'),text('details')], [index('site_start',['managedSiteId','startAt']),index('entity',['linkedEntityType','linkedEntityId'])]),
  agencyEntity('documents', [str('managedSiteId',36,true),str('title',255,true),str('category',64,true),str('linkedEntityType',64),str('linkedEntityId',36),str('evidenceFileId',36,true),str('contentType',255),integer('version',true),str('visibility',64,true),str('uploadedBy',36)], [index('site_category',['managedSiteId','category']),index('entity',['linkedEntityType','linkedEntityId'])]),
  agencyEntity('inventory_items', [str('managedSiteId',36,true),str('name',255,true),str('category',64),number('quantity'),str('unit',32),str('storageLocation',255),number('reorderLevel'),text('notes')], [index('site_category',['managedSiteId','category']),index('site_status',['managedSiteId','status'])]),
  agencyEntity('notifications', [str('managedSiteId',36),str('userId',36),str('role',64),str('title',255,true),text('body',true),str('linkedEntityType',64),str('linkedEntityId',36),str('deliveryStatus',64),datetime('readAt'),datetime('sentAt')], [index('user_read',['userId','readAt']),index('site_created',['managedSiteId','createdAt'])]),
  agencyEntity('form_submissions', [str('managedSiteId',36,true),str('formType',64,true),str('schemaVersion',32,true),str('entityType',64,true),str('entityId',36,true),str('clientSubmissionId',128),text('payload',true),str('submittedBy',36,true),datetime('submittedAt',true)], [unique('site_client_submission',['managedSiteId','clientSubmissionId']),index('site_form_created',['managedSiteId','formType','createdAt'])]),
  agencyEntity('idempotency_keys', [str('operation',128,true),str('keyHash',128,true),str('payloadHash',128,true),str('executionState',32,true),integer('responseStatus'),text('responseBody'),datetime('expiresAt',true)], [unique('agency_operation_key',['agencyId','operation','keyHash']),index('state_expiry',['executionState','expiresAt'])]),
  agencyEntity('upload_sessions', [str('userId',36,true),str('bucketId',36,true),str('fileId',36,true),str('managedSiteId',36),str('propertyId',36),str('inspectionJobId',36),str('reportId',36),str('entityType',64),str('entityId',36),str('originalFilename',512,true),str('mimeType',255,true),integer('size',true),str('checksum',128,true),datetime('expiresAt',true),datetime('completedAt')], [unique('bucket_file',['bucketId','fileId']),index('user_status',['userId','status']),index('entity_status',['entityType','entityId','status'])]),
  agencyEntity('property_operating_settings', [str('managedSiteId',36,true),text('moveBookingInstructions'),text('contractorSignInInstructions'),text('accessDeviceInstructions'),text('residentOnboardingInstructions'),text('wasteInstructions')], [unique('site',['managedSiteId'])]),
  agencyEntity('operational_quotes', [str('managedSiteId',36,true),str('defectId',36),str('contractorId',36),number('amount'),str('currency',3),text('scope'),str('documentEvidenceFileId',36),datetime('validUntil')], [index('defect_status',['defectId','status']),index('contractor_status',['contractorId','status'])]),
  agencyEntity('operational_approvals', [str('managedSiteId',36,true),str('quoteId',36),str('entityType',64,true),str('entityId',36,true),str('decision',64,true),str('decidedBy',36),datetime('decidedAt'),text('reason')], [index('entity_decision',['entityType','entityId','decision']),index('site_status',['managedSiteId','status'])]),
  agencyEntity('operational_work_orders', [str('managedSiteId',36,true),str('defectId',36),str('serviceEventId',36),str('propertyAreaId',36),str('assetId',36),str('quoteId',36),str('contractorId',36),str('priority',32),datetime('scheduledAt'),datetime('dueDate'),datetime('completedAt'),datetime('verifiedAt'),str('verifiedBy',36),text('scope',true),text('accessRequirements'),text('shutdownRequirements'),text('residentImpact'),text('findings'),text('workPerformed'),text('recommendations'),str('serviceReportEvidenceId',36)], [index('site_status',['managedSiteId','status']),index('defect_status',['defectId','status']),index('contractor_status',['contractorId','status']),index('due_status',['dueDate','status'])]),
  agencyEntity('report_review_comments', [str('reportId',36,true),str('scope',64,true),str('scopeEntityId',36),str('authorUserId',36,true),text('comment',true),str('resolvedBy',36),datetime('resolvedAt')], [index('report_status',['reportId','status']),index('scope',['scope','scopeEntityId'])]),
  agencyEntity('report_distributions', [str('reportId',36,true),str('reportVersionId',36,true),str('recipientRole',64),str('recipientId',36),str('recipientEmail',320,false,'email'),datetime('expiresAt'),datetime('sentAt'),datetime('viewedAt')], [index('report_status',['reportId','status']),index('recipient_status',['recipientId','status'])]),
  agencyEntity('report_acknowledgements', [str('reportId',36,true),str('reportVersionId',36,true),str('distributionId',36),str('acknowledgedBy',36),str('acknowledgementType',64),datetime('acknowledgedAt',true),text('details')], [index('report_acknowledged',['reportId','acknowledgedAt']),index('distribution',['distributionId'])]),
  agencyEntity('report_recipient_responses', [str('reportId',36,true),str('reportVersionId',36,true),str('distributionId',36),str('respondentId',36),str('respondentRole',64),text('response',true),datetime('submittedAt',true),datetime('resolvedAt'),str('resolvedBy',36)], [index('report_status',['reportId','status']),index('distribution_status',['distributionId','status'])]),
  agencyEntity('report_supersessions', [str('reportId',36,true),str('supersededVersionId',36,true),str('replacementVersionId',36,true),str('reason',512,true),str('authorisedBy',36,true),datetime('supersededAt',true)], [unique('superseded_version',['supersededVersionId']),index('report_time',['reportId','supersededAt'])]),
  agencyEntity('tenant_communications', [str('tenancyId',36,true),str('tenantId',36),str('direction',32,true),str('channel',32,true),str('subject',255),text('content',true),str('senderUserId',36),datetime('sentAt'),datetime('deliveredAt')], [index('tenancy_created',['tenancyId','createdAt']),index('tenant_status',['tenantId','status'])]),
  agencyEntity('tenancy_documents', [str('tenancyId',36,true),str('documentType',64,true),str('evidenceFileId',36,true),integer('version',true),str('contentHash',128,true),datetime('issuedAt'),boolean('immutable',true),text('signers')], [unique('tenancy_type_version',['tenancyId','documentType','version']),index('tenancy_status',['tenancyId','status'])]),
  agencyEntity('tenant_portal_grants', [str('tenancyId',36,true),str('tenantId',36),str('userId',36,true),text('permissions',true),datetime('validFrom'),datetime('validUntil'),str('revokedBy',36),datetime('revokedAt')], [index('user_status',['userId','status']),index('tenancy_status',['tenancyId','status'])]),
  agencyEntity('external_access_grants', [str('resourceType',64,true),str('resourceId',128,true),str('tokenHash',64,true),str('recipientEmail',320,false,'email'),str('tenantId',36),str('tenancyId',36),str('externalContactId',36),str('purpose',64),datetime('expiresAt',true),datetime('revokedAt'),str('revokedBy',36),datetime('lastAccessedAt'),str('replacedByGrantId',36),integer('version',true)], [unique('token_hash',['tokenHash']),index('agency_type',['agencyId','resourceType']),index('agency_resource',['agencyId','resourceType','resourceId']),index('expiry_status',['expiresAt','status'])]),

  agencyEntity('audit_events', [str('managedSiteId',36),str('actorUserId',36),str('actorType',64,true),str('actorRole',64),str('action',128,true),str('entityType',64,true),str('entityId',36,true),str('source',64,true),str('outcome',64),text('previousState'),text('newState'),str('requestId',128),str('correlationId',128,true),str('ipAddress',64),str('userAgent',1024),datetime('sourceCreatedAt')], [index('agency_created',['agencyId','createdAt']),index('entity_created',['entityType','entityId','createdAt']),index('correlation',['correlationId'])]),
  agencyEntity('integration_connections', [str('provider',64,true),str('externalAccountId',255),str('credentialReference',255),datetime('lastSuccessfulAt'),datetime('lastAttemptedAt'),text('configuration'),text('lastError')], [unique('agency_provider',['agencyId','provider']),index('provider_status',['provider','status'])]),
  agencyEntity('integration_events', [str('provider',64,true),str('eventType',128,true),str('externalEventId',255,true),str('deduplicationId',255,true),str('payloadReference',512),str('processingStatus',64,true),integer('attempts',true),text('errorState'),datetime('firstReceivedAt',true),datetime('lastAttemptedAt'),datetime('processedAt')], [unique('provider_dedup',['agencyId','provider','deduplicationId']),index('status_attempted',['processingStatus','lastAttemptedAt'])]),
  agencyEntity('integration_deliveries', [str('provider',64,true),str('eventId',36),str('externalDeliveryId',255,true),str('deliveryStatus',64,true),integer('attempts',true),datetime('lastAttemptedAt'),datetime('deliveredAt'),text('errorState')], [unique('provider_delivery',['agencyId','provider','externalDeliveryId']),index('status_attempted',['deliveryStatus','lastAttemptedAt'])]),
  agencyEntity('integration_exceptions', [str('provider',64,true),str('category',64,true),str('severity',32,true),str('entityType',64),str('entityId',36),text('detail',true),text('resolution'),datetime('resolvedAt')], [index('provider_severity',['provider','severity'])]),
  agencyEntity('integration_outbox', [str('eventType',128,true),str('entityType',64,true),str('entityId',36,true),text('payload',true),str('deliveryStatus',64,true),integer('attempts',true),datetime('availableAt',true),datetime('lastAttemptedAt')], [index('status_available',['deliveryStatus','availableAt']),index('entity',['entityType','entityId'])]),
  agencyEntity('evidence_files', [str('bucketId',36,true),str('fileId',36,true),str('managedSiteId',36),str('propertyId',36),str('entityType',64,true),str('entityId',36,true),str('category',64),str('mimeType',255,true),str('originalFilename',512,true),integer('size',true),str('checksum',128,true),str('uploadedBy',36,true),datetime('capturedAt'),str('legacyFileId',255),str('storageVersion',128)], [unique('bucket_file',['bucketId','fileId']),index('entity_created',['entityType','entityId','createdAt']),index('property_created',['propertyId','createdAt'])]),
  table('migration_id_map', [str('sourceSystem',64,true),str('sourceEntity',128,true),str('sourceId',255,true),str('targetTable',36,true),str('targetId',36),str('sourceChecksum',128,true),str('migratedChecksum',128),str('migrationVersion',64,true),datetime('migratedAt'),str('status',32,true),text('error')], [unique('source_identity',['sourceSystem','sourceEntity','sourceId']),index('status_source',['status','sourceSystem']),index('target',['targetTable','targetId'])]),
];

export const expectedTableIds = tables.map((item) => item.$id);
