import { randomUUID } from 'node:crypto';
import type { IncomingMessage } from 'node:http';
import { applicationDefault, getApps, initializeApp } from 'firebase-admin/app';
import { getStorage } from 'firebase-admin/storage';
import { authenticateAndAuthorise } from '../security/authoriseRequest.js';
import { ConfiguredESignProvider } from '../services/eSignProvider.js';
import { ApiError, type ApiResponse } from './router.js';
import type { ApiDependencies, StoredRecord } from './types.js';

function adminApp() { return getApps()[0] ?? initializeApp({ credential: applicationDefault() }); }
function route(req: IncomingMessage) { return new URL(req.url ?? '/', 'http://localhost').pathname.split('/').filter(Boolean); }
function agencyHeader(req: IncomingMessage) { const value = req.headers['x-agency-id']?.toString().trim(); if (!value) throw new ApiError(400, 'AGENCY_HEADER_REQUIRED', 'x-agency-id is required.'); return value; }
async function rawBody(req: IncomingMessage, max = 1_000_000) { const chunks: Buffer[] = []; let size = 0; for await (const chunk of req) { const value = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk); size += value.length; if (size > max) throw new ApiError(413, 'PAYLOAD_TOO_LARGE', 'Request is too large.'); chunks.push(value); } return Buffer.concat(chunks); }
function parse(raw: Buffer): Record<string, unknown> { if (!raw.length) return {}; try { const value = JSON.parse(raw.toString('utf8')) as unknown; if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error(); return value as Record<string, unknown>; } catch { throw new ApiError(400, 'INVALID_JSON', 'Request body must be valid JSON.'); } }
async function listAll(deps: ApiDependencies, collection: string, agencyId: string): Promise<StoredRecord[]> { const out: StoredRecord[] = []; let cursor: string | undefined; do { const page = await deps.repository.list(collection, agencyId, 100, cursor); out.push(...page.items); cursor = page.nextCursor; } while (cursor); return out; }
function bucketName() { const projectId = process.env.GOOGLE_CLOUD_PROJECT?.trim(); return process.env.DOCUMENT_BUCKET?.trim() || process.env.REPORT_BUCKET?.trim() || (projectId ? `${projectId}-reports` : ''); }

async function documentUrl(document: StoredRecord): Promise<string> { const bucket = bucketName(); if (!bucket || !document.objectPath) throw new ApiError(409, 'DOCUMENT_ARTIFACT_REQUIRED', 'Document artifact is required before signing.'); const [url] = await getStorage(adminApp()).bucket(bucket).file(String(document.objectPath)).getSignedUrl({ version: 'v4', action: 'read', expires: Date.now() + 15 * 60_000 }); return url; }

export async function routeESignExternalWebhook(req: IncomingMessage, deps: ApiDependencies, correlationId: string): Promise<ApiResponse | undefined> {
  const parts = route(req); if (parts[0] !== 'api' || parts[1] !== 'v1' || parts[2] !== 'external' || parts[3] !== 'esign' || parts[4] !== 'webhook' || req.method !== 'POST') return undefined;
  const raw = await rawBody(req); const provider = new ConfiguredESignProvider(); const signature = req.headers['x-esign-signature']?.toString(); if (!provider.verifyWebhook(raw, signature)) throw new ApiError(401, 'ESIGN_WEBHOOK_INVALID', 'E-sign webhook signature is invalid.'); const event = parse(raw); const agencyId = String(event.agencyId || ''); const providerEnvelopeId = String(event.envelopeId || event.id || ''); if (!agencyId || !providerEnvelopeId) throw new ApiError(400, 'ESIGN_WEBHOOK_FIELDS_REQUIRED', 'agencyId and envelopeId are required.');
  const envelopes = await listAll(deps, 'esignEnvelopes', agencyId); const envelope = envelopes.find((candidate) => candidate.providerEnvelopeId === providerEnvelopeId); if (!envelope) throw new ApiError(404, 'ESIGN_ENVELOPE_NOT_FOUND', 'E-sign envelope was not found.');
  const providerStatus = String(event.status || ''); const status = providerStatus === 'completed' ? 'completed' : providerStatus === 'declined' ? 'declined' : providerStatus === 'voided' ? 'voided' : providerStatus === 'expired' ? 'expired' : providerStatus === 'delivered' ? 'delivered' : providerStatus.includes('partial') ? 'partially_signed' : 'sent';
  const now = new Date().toISOString(); const updated = await deps.repository.update('esignEnvelopes', agencyId, envelope.id, { status, providerEvent: event, ...(status === 'completed' ? { completedAt: now } : {}) }, Number(envelope.version), 'system:esign-webhook');
  const documentId = String(envelope.documentId || ''); if (documentId) { const document = await deps.repository.get('tenancyDocuments', agencyId, documentId); if (document) await deps.repository.update('tenancyDocuments', agencyId, documentId, { status: status === 'completed' ? 'signed' : status === 'partially_signed' ? 'partially_signed' : document.status, signatureMethod: 'external_esign', ...(status === 'completed' ? { signedAt: now } : {}) }, Number(document.version), 'system:esign-webhook'); }
  return { status: 200, body: { data: { accepted: true, envelope: updated }, meta: { correlationId } } };
}

export async function routeESignCommandRequest(req: IncomingMessage, deps: ApiDependencies, correlationId: string): Promise<ApiResponse | undefined> {
  const parts = route(req); if (parts[0] !== 'api' || parts[1] !== 'v1') return undefined;
  const provider = new ConfiguredESignProvider();
  if (parts[2] === 'tenancy-documents' && parts[3] && parts[4] === 'signing-envelope' && req.method === 'POST') {
    const agencyId = agencyHeader(req); const principal = await authenticateAndAuthorise(req, deps, 'document.sign.manage', { agencyId }, correlationId); const body = parse(await rawBody(req)); const document = await deps.repository.get('tenancyDocuments', agencyId, parts[3]); if (!document) throw new ApiError(404, 'TENANCY_DOCUMENT_NOT_FOUND', 'Tenancy document was not found.'); if (!document.sha256 || !document.objectPath) throw new ApiError(409, 'DOCUMENT_ARTIFACT_REQUIRED', 'Document must be rendered before an envelope can be created.');
    const signers = Array.isArray(document.signers) ? document.signers as Array<Record<string, unknown>> : []; const recipients = signers.filter((item) => item.required !== false).map((item, index) => ({ id: String(item.id || randomUUID()), name: String(item.name || ''), email: String(item.email || ''), role: String(item.kind || 'signer'), order: index + 1, authentication: String(body.authentication || 'email') })).filter((item) => item.name && item.email); if (!recipients.length) throw new ApiError(409, 'ESIGN_RECIPIENTS_REQUIRED', 'At least one signer with name and email is required.');
    const envelopeId = randomUUID(); const callbackBase = process.env.WEB_APP_BASE_URL?.trim()?.replace(/\/$/u, '') || process.env.API_PUBLIC_BASE_URL?.trim()?.replace(/\/$/u, ''); const created = await provider.createEnvelope({ externalReference: envelopeId, documentUrl: await documentUrl(document), documentSha256: String(document.sha256), title: String(document.title || 'Tenancy document'), recipients, callbackUrl: callbackBase ? `${callbackBase}/api/v1/external/esign/webhook` : undefined }); const now = new Date().toISOString(); const envelope = await deps.repository.create('esignEnvelopes', agencyId, envelopeId, { provider: String(body.provider || 'configured'), providerEnvelopeId: created.id, documentId: document.id, documentVersion: Number(document.documentVersion || 1), documentSha256: document.sha256, status: created.status || 'sent', recipients: recipients.map((item) => ({ ...item, required: true, status: 'pending' })), sentAt: now }, principal.uid); await deps.repository.update('tenancyDocuments', agencyId, document.id, { status: 'signature_required', signatureMethod: 'external_esign', eSignEnvelopeId: envelopeId }, Number(document.version), principal.uid); return { status: 201, body: { data: envelope, meta: { correlationId } } };
  }

  if (parts[2] === 'esign-envelopes' && parts[3] && parts[4] && req.method === 'POST') {
    const agencyId = agencyHeader(req); const principal = await authenticateAndAuthorise(req, deps, 'document.sign.manage', { agencyId }, correlationId); const envelope = await deps.repository.get('esignEnvelopes', agencyId, parts[3]); if (!envelope) throw new ApiError(404, 'ESIGN_ENVELOPE_NOT_FOUND', 'E-sign envelope was not found.'); const providerEnvelopeId = String(envelope.providerEnvelopeId || ''); if (!providerEnvelopeId) throw new ApiError(409, 'ESIGN_PROVIDER_ID_REQUIRED', 'Envelope is not linked to a provider.'); const body = parse(await rawBody(req)); if (parts[4] === 'resend') await provider.resendEnvelope(providerEnvelopeId); else if (parts[4] === 'void') await provider.voidEnvelope(providerEnvelopeId, String(body.reason || 'Voided by authorised user')); else if (parts[4] === 'refresh') { const remote = await provider.getEnvelope(providerEnvelopeId); const updated = await deps.repository.update('esignEnvelopes', agencyId, envelope.id, { status: remote.status, providerSnapshot: remote }, Number(envelope.version), principal.uid); return { status: 200, body: { data: updated, meta: { correlationId } } }; } else return undefined; const refreshed = await deps.repository.get('esignEnvelopes', agencyId, envelope.id); return { status: 200, body: { data: refreshed, meta: { correlationId } } };
  }
  return undefined;
}
