import { createHash, randomUUID } from 'node:crypto';
import type { IncomingMessage } from 'node:http';
import { applicationDefault, getApps, initializeApp } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';
import { ApiError, type ApiResponse } from './router.js';
import type { ApiDependencies } from './types.js';

interface PortalGrant { id: string; agencyId: string; tenantId: string; tenancyId: string; tokenHash: string; expiresAt: string; revokedAt?: string; }
function adminApp() { return getApps()[0] ?? initializeApp({ credential: applicationDefault() }); }
function hash(value: string) { return createHash('sha256').update(value.trim()).digest('hex'); }
function parts(req: IncomingMessage) { return new URL(req.url ?? '/', 'http://localhost').pathname.split('/').filter(Boolean); }
async function readJson(req: IncomingMessage) { const chunks: Buffer[] = []; for await (const chunk of req) chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)); if (!chunks.length) return {}; const value = JSON.parse(Buffer.concat(chunks).toString('utf8')) as unknown; if (!value || typeof value !== 'object' || Array.isArray(value)) throw new ApiError(400, 'INVALID_JSON', 'Request body must be an object.'); return value as Record<string, unknown>; }
async function resolveGrant(token: string): Promise<PortalGrant> { const result = await getFirestore(adminApp()).collectionGroup('tenantPortalGrants').where('tokenHash', '==', hash(token)).limit(2).get(); if (result.size !== 1) throw new ApiError(401, 'INVALID_GRANT_TOKEN', 'Tenant portal link is invalid.'); const grant = result.docs[0].data() as PortalGrant; if (grant.revokedAt || Date.parse(grant.expiresAt) <= Date.now()) throw new ApiError(401, 'GRANT_TOKEN_EXPIRED', 'Tenant portal link is expired or revoked.'); return grant; }
async function listAll(deps: ApiDependencies, collection: string, agency: string) { const result = []; let cursor: string | undefined; do { const page = await deps.repository.list(collection, agency, 100, cursor); result.push(...page.items); cursor = page.nextCursor; } while (cursor); return result; }

export async function routeRemoteInspectionPortalRequest(req: IncomingMessage, deps: ApiDependencies, correlationId: string): Promise<ApiResponse | undefined> {
  const route = parts(req); if (route[0] !== 'api' || route[1] !== 'v1' || route[2] !== 'external' || route[3] !== 'remote-inspections' || !route[4]) return undefined;
  const grant = await resolveGrant(route[4]); const assignmentId = route[5];
  if (req.method === 'GET' && !assignmentId) { const assignments = (await listAll(deps, 'remoteInspectionAssignments', grant.agencyId)).filter((item) => item.tenantId === grant.tenantId && item.tenancyId === grant.tenancyId && !['accepted','rejected','expired'].includes(String(item.status))); return { status: 200, body: { data: assignments, meta: { correlationId } } }; }
  if (!assignmentId) return undefined;
  const assignment = await deps.repository.get('remoteInspectionAssignments', grant.agencyId, assignmentId); if (!assignment || assignment.tenantId !== grant.tenantId || assignment.tenancyId !== grant.tenancyId) throw new ApiError(404, 'REMOTE_INSPECTION_NOT_FOUND', 'Remote inspection assignment was not found.');
  if (req.method === 'GET') return { status: 200, body: { data: assignment, meta: { correlationId } } };
  if (req.method === 'POST' && route[6] === 'submit') {
    const body = await readJson(req); const requirementId = String(body.requirementId || ''); if (!requirementId) throw new ApiError(400, 'REQUIREMENT_REQUIRED', 'requirementId is required.'); const evidenceIds = Array.isArray(body.evidenceIds) ? body.evidenceIds.filter((item): item is string => typeof item === 'string') : []; const requirements = Array.isArray(assignment.requirements) ? assignment.requirements as Array<Record<string, unknown>> : []; const requirement = requirements.find((item) => String(item.id) === requirementId); if (!requirement) throw new ApiError(404, 'REQUIREMENT_NOT_FOUND', 'Inspection requirement was not found.'); const requiredCount = Number(requirement.requiredEvidenceCount || 0); if (evidenceIds.length < requiredCount) throw new ApiError(409, 'EVIDENCE_REQUIRED', `At least ${requiredCount} evidence item(s) are required.`); const commentaryRequired = requirement.commentaryRequired === true; if (commentaryRequired && !String(body.commentary || '').trim()) throw new ApiError(409, 'COMMENTARY_REQUIRED', 'Commentary is required for this inspection item.'); const submission = await deps.repository.create('remoteInspectionSubmissions', grant.agencyId, randomUUID(), { assignmentId, requirementId, tenantId: grant.tenantId, commentary: body.commentary, evidenceIds, source: 'tenant', submittedAt: new Date().toISOString(), reviewStatus: 'pending' }, `external:${grant.id}`); const all = (await listAll(deps, 'remoteInspectionSubmissions', grant.agencyId)).filter((item) => item.assignmentId === assignmentId); const completed = new Set(all.map((item) => String(item.requirementId))); completed.add(requirementId); if (requirements.every((item) => completed.has(String(item.id)))) await deps.repository.update('remoteInspectionAssignments', grant.agencyId, assignmentId, { status: 'submitted', submittedAt: new Date().toISOString() }, Number(assignment.version), `external:${grant.id}`); else if (assignment.status === 'issued') await deps.repository.update('remoteInspectionAssignments', grant.agencyId, assignmentId, { status: 'in_progress' }, Number(assignment.version), `external:${grant.id}`); return { status: 201, body: { data: submission, meta: { correlationId } } };
  }
  return undefined;
}
