import type { AuthorisationTarget } from '@pcr/domain';
import type { RoutePolicy } from './types.js';

function target(body: Record<string, unknown>, id?: string): AuthorisationTarget {
  const agencyId = typeof body.agencyId === 'string' ? body.agencyId : '';
  return {
    agencyId,
    ...(typeof body.clientAccountId === 'string' ? { clientAccountId: body.clientAccountId } : {}),
    ...(typeof body.clientId === 'string' ? { clientAccountId: body.clientId } : {}),
    ...(typeof body.clientContactId === 'string' ? { clientContactId: body.clientContactId } : {}),
    ...(typeof body.contactId === 'string' ? { clientContactId: body.contactId } : {}),
    ...(typeof body.tenantId === 'string' ? { tenantId: body.tenantId } : {}),
    ...(typeof body.propertyId === 'string' ? { propertyId: body.propertyId } : {}),
    ...(typeof body.tenancyId === 'string' ? { tenancyId: body.tenancyId } : {}),
    ...(typeof body.inspectionJobId === 'string' ? { inspectionJobId: body.inspectionJobId } : {}),
    ...(typeof body.reportId === 'string' ? { reportId: body.reportId } : {}),
    ...(typeof body.maintenanceItemId === 'string' ? { maintenanceItemId: body.maintenanceItemId } : {}),
    ...(typeof body.maintenanceQuoteId === 'string' ? { maintenanceQuoteId: body.maintenanceQuoteId } : {}),
    ...(typeof body.quoteId === 'string' ? { maintenanceQuoteId: body.quoteId } : {}),
    ...(typeof body.priceBookId === 'string' ? { priceBookId: body.priceBookId } : {}),
    ...(typeof body.assignedInspectorId === 'string' ? { assignedInspectorId: body.assignedInspectorId } : {}),
    ...(typeof body.assignedAnalystId === 'string' ? { assignedAnalystId: body.assignedAnalystId } : {}),
    ...(typeof body.assignedReviewerId === 'string' ? { assignedReviewerId: body.assignedReviewerId } : {}),
    ...(typeof body.lifecycleStatus === 'string' ? { lifecycleStatus: body.lifecycleStatus } : {}),
    ...(!body.reportId && id && !body.clientAccountId && !body.clientId ? { reportId: id } : {}),
  };
}

export const ROUTE_POLICIES: Record<string, RoutePolicy> = {
  agencies: { collection: 'agencies', readCapability: 'agency.read', writeCapability: 'agency.manage', target },
  users: { collection: 'users', readCapability: 'agency.read', writeCapability: 'user.suspend', target },
  invitations: { collection: 'invitations', readCapability: 'agency.read', writeCapability: 'user.invite', target },
  clients: { collection: 'clients', readCapability: 'client.read', writeCapability: 'client.manage', target },
  'client-contacts': { collection: 'clientContacts', readCapability: 'client.read', writeCapability: 'client.contact.manage', target },
  'client-engagements': { collection: 'clientEngagements', readCapability: 'client.read', writeCapability: 'client.engagement.manage', target },
  'property-client-relationships': { collection: 'propertyClientRelationships', readCapability: 'client.read', writeCapability: 'client.relationship.manage', target },
  'client-documents': { collection: 'clientDocuments', readCapability: 'client.read', writeCapability: 'client.document.manage', target },
  'client-portal-users': { collection: 'clientPortalUsers', readCapability: 'client.read', writeCapability: 'client.portal.manage', target },
  'client-timeline-events': { collection: 'clientTimelineEvents', readCapability: 'client.read', target },
  properties: { collection: 'properties', readCapability: 'property.read', writeCapability: 'property.manage', target },
  tenants: { collection: 'tenants', readCapability: 'tenant.read', writeCapability: 'tenant.manage', target },
  tenancies: { collection: 'tenancies', readCapability: 'tenancy.read', writeCapability: 'tenancy.manage', target },
  'tenancy-participants': { collection: 'tenancyParticipants', readCapability: 'tenancy.read', writeCapability: 'tenancy.manage', target },
  'tenant-communications': { collection: 'tenantCommunications', readCapability: 'tenant.communication.read', writeCapability: 'tenant.communication.send', target },
  'tenancy-documents': { collection: 'tenancyDocuments', readCapability: 'tenant.document.read', writeCapability: 'tenant.document.manage', target },
  'inspection-jobs': { collection: 'inspectionJobs', readCapability: 'job.read', writeCapability: 'job.manage', target },
  'inspection-requests': { collection: 'inspectionRequests', readCapability: 'job.read', writeCapability: 'job.manage', target },
  'inspection-service-mappings': { collection: 'inspectionServiceMappings', readCapability: 'agency.read', writeCapability: 'agency.manage', target },
  'inspector-capability-profiles': { collection: 'inspectorCapabilityProfiles', readCapability: 'job.read', writeCapability: 'agency.manage', target },
  'recurring-inspections': { collection: 'recurringInspectionSchedules', readCapability: 'job.read', writeCapability: 'job.manage', target },
  'inspection-communications': { collection: 'inspectionCommunications', readCapability: 'job.read', writeCapability: 'job.manage', target },
  'inspection-operational-events': { collection: 'inspectionOperationalEvents', readCapability: 'job.read', writeCapability: 'job.manage', target },
  'integration-connections': { collection: 'integrationConnections', readCapability: 'agency.read', writeCapability: 'agency.manage', target },
  'integration-deliveries': { collection: 'integrationDeliveries', readCapability: 'audit.read', target },
  'integration-sync-exceptions': { collection: 'integrationSyncExceptions', readCapability: 'job.read', writeCapability: 'job.manage', target },
  reports: { collection: 'reports', readCapability: 'report.read', writeCapability: 'report.edit', target },
  templates: { collection: 'templates', readCapability: 'report.read', target },
  'report-presentation-templates': { collection: 'reportPresentationTemplateVersions', readCapability: 'report.read', writeCapability: 'template.manage', target },
  'report-branding-profiles': { collection: 'reportBrandingProfileVersions', readCapability: 'report.read', writeCapability: 'template.manage', target },
  'report-versions': { collection: 'reportVersions', readCapability: 'report.read', writeCapability: 'report.edit', target },
  uploads: { collection: 'uploadSessions', readCapability: 'report.read', writeCapability: 'upload.create', target },
  'analysis-jobs': { collection: 'analysisJobs', readCapability: 'report.read', writeCapability: 'analysis.create', target },
  'pdf-jobs': { collection: 'pdfJobs', readCapability: 'report.read', writeCapability: 'pdf.create', target },
  'tenant-responses': { collection: 'tenantResponses', readCapability: 'report.read', writeCapability: 'tenant_response.submit', target },
  notifications: { collection: 'notificationJobs', readCapability: 'audit.read', writeCapability: 'notification.send', target },
  'audit-history': { collection: 'auditEvents', readCapability: 'audit.read', target },
  'maintenance-candidates': { collection: 'maintenanceCandidates', readCapability: 'maintenance.read', writeCapability: 'maintenance.triage', target },
  'maintenance-items': { collection: 'maintenanceItems', readCapability: 'maintenance.read', target },
  'maintenance-estimates': { collection: 'maintenanceEstimates', readCapability: 'maintenance.read', target },
  'maintenance-quotes': { collection: 'maintenanceQuotes', readCapability: 'maintenance.read', target },
  'maintenance-quote-versions': { collection: 'maintenanceQuoteVersions', readCapability: 'maintenance.read', target },
  'maintenance-work-orders': { collection: 'maintenanceWorkOrders', readCapability: 'maintenance.read', target },
  'maintenance-variations': { collection: 'maintenanceVariations', readCapability: 'maintenance.read', target },
  'price-books': { collection: 'priceBooks', readCapability: 'maintenance.read', target },
  'price-book-versions': { collection: 'priceBookVersions', readCapability: 'maintenance.read', target },
  'price-book-imports': { collection: 'priceBookImports', readCapability: 'maintenance.read', target },
  'quote-approval-policies': { collection: 'quoteApprovalPolicies', readCapability: 'maintenance.read', target },
  'contractor-quote-requests': { collection: 'contractorQuoteRequests', readCapability: 'maintenance.read', target },
  'contractor-quotes': { collection: 'contractorQuotes', readCapability: 'maintenance.read', target },
  'preventive-maintenance-schedules': { collection: 'preventiveMaintenanceSchedules', readCapability: 'maintenance.read', writeCapability: 'maintenance.manage', target },
  'warranty-claims': { collection: 'warrantyClaims', readCapability: 'maintenance.read', target },
  'work-requests': { collection: 'workRequests', readCapability: 'maintenance.read', target },
  'tenant-instructions': { collection: 'tenantInstructions', readCapability: 'tenant_instruction.manage', target },
  'external-contacts': { collection: 'externalContacts', readCapability: 'external_contact.manage', writeCapability: 'external_contact.manage', target },
  'external-access-grants': { collection: 'externalAccessGrants', readCapability: 'maintenance.read', writeCapability: 'maintenance.manage', target },
  'client-approvals': { collection: 'clientApprovals', readCapability: 'client_approval.manage', writeCapability: 'client_approval.manage', target },
};

export const API_ROUTE_NAMES = Object.freeze(Object.keys(ROUTE_POLICIES));
