import type { PortalId } from '@pcr/domain';
import type { PortalCreateField, PortalFeatureDefinition } from './portalFeatureRegistry';

const FORMS: Readonly<Record<string, readonly PortalCreateField[]>> = {
  'building:activity': [
    { name: 'activityDate', label: 'Activity date', type: 'datetime-local', required: true },
    { name: 'category', label: 'Category', required: true },
    { name: 'summary', label: 'Summary', type: 'textarea', required: true },
    { name: 'actionTaken', label: 'Action taken', type: 'textarea' },
    { name: 'followUpRequired', label: 'Follow-up required', type: 'checkbox' },
    { name: 'followUpDate', label: 'Follow-up date', type: 'datetime-local' },
    { name: 'priority', label: 'Priority' },
  ],
  'building:tasks': [
    { name: 'title', label: 'Task', required: true },
    { name: 'taskType', label: 'Type', required: true },
    { name: 'priority', label: 'Priority' },
    { name: 'dueAt', label: 'Due', type: 'datetime-local' },
    { name: 'linkedEntityType', label: 'Related record type' },
    { name: 'linkedEntityId', label: 'Related record ID' },
  ],
  'building:defects-maintenance': [
    { name: 'category', label: 'Category', required: true },
    { name: 'description', label: 'Defect description', type: 'textarea', required: true },
    { name: 'riskLevel', label: 'Risk level' },
    { name: 'priority', label: 'Priority' },
    { name: 'commonProperty', label: 'Common property', type: 'checkbox' },
    { name: 'immediateResponse', label: 'Immediate response', type: 'textarea' },
    { name: 'quoteRequired', label: 'Quote required', type: 'checkbox' },
    { name: 'strataApprovalRequired', label: 'Strata approval required', type: 'checkbox' },
    { name: 'dueDate', label: 'Due date', type: 'datetime-local' },
  ],
  'building:inspections': [
    { name: 'inspectionType', label: 'Inspection type', required: true },
    { name: 'templateId', label: 'Template ID' },
    { name: 'inspectorId', label: 'Inspector user ID', required: true },
    { name: 'scheduledAt', label: 'Scheduled for', type: 'datetime-local' },
    { name: 'summary', label: 'Instructions / summary', type: 'textarea' },
  ],
  'building:moves-deliveries': [
    { name: 'propertyId', label: 'Property ID', required: true },
    { name: 'unitId', label: 'Unit ID' },
    { name: 'moveType', label: 'Move type', required: true },
    { name: 'startAt', label: 'Start', type: 'datetime-local', required: true },
    { name: 'endAt', label: 'End', type: 'datetime-local', required: true },
    { name: 'removalistName', label: 'Removalist / supplier' },
    { name: 'vehicleRegistration', label: 'Vehicle registration' },
    { name: 'specialRequirements', label: 'Special requirements', type: 'textarea' },
  ],
  'building:access-devices-keys': [
    { name: 'unitId', label: 'Unit ID', required: true },
    { name: 'requestType', label: 'Request type', required: true },
    { name: 'deviceTypeRequested', label: 'Device type', required: true },
    { name: 'quantityRequested', label: 'Quantity', type: 'number' },
    { name: 'requestReason', label: 'Reason', type: 'textarea' },
  ],
  'building:incidents-security': [
    { name: 'incidentType', label: 'Incident type', required: true },
    { name: 'severity', label: 'Severity', required: true },
    { name: 'riskLevel', label: 'Risk level' },
    { name: 'occurredAt', label: 'Occurred at', type: 'datetime-local', required: true },
    { name: 'description', label: 'Incident details', type: 'textarea', required: true },
    { name: 'immediateActions', label: 'Immediate actions', type: 'textarea' },
    { name: 'emergencyServicesCalled', label: 'Emergency services called', type: 'checkbox' },
  ],
  'building:bylaw-observations': [
    { name: 'bylawReference', label: 'By-law reference' },
    { name: 'category', label: 'Category' },
    { name: 'observedAt', label: 'Observed at', type: 'datetime-local', required: true },
    { name: 'specificLocation', label: 'Specific location' },
    { name: 'description', label: 'Observation', type: 'textarea', required: true },
  ],
  'building:assets': [
    { name: 'assetType', label: 'Asset type', required: true },
    { name: 'name', label: 'Asset name', required: true },
    { name: 'manufacturer', label: 'Manufacturer' },
    { name: 'model', label: 'Model' },
    { name: 'serialNumber', label: 'Serial number' },
    { name: 'criticality', label: 'Criticality' },
    { name: 'qrCode', label: 'QR identifier' },
    { name: 'warrantyUntil', label: 'Warranty until', type: 'datetime-local' },
  ],
  'building:waste': [
    { name: 'eventType', label: 'Event type', required: true },
    { name: 'wasteType', label: 'Waste type' },
    { name: 'activity', label: 'Activity' },
    { name: 'occurredAt', label: 'Occurred at', type: 'datetime-local', required: true },
    { name: 'details', label: 'Details', type: 'textarea', required: true },
    { name: 'issue', label: 'Issue', type: 'textarea' },
    { name: 'actionTaken', label: 'Action taken', type: 'textarea' },
  ],
  'building:monthly-reports': [
    { name: 'period', label: 'Reporting period', required: true, placeholder: 'YYYY-MM' },
    { name: 'title', label: 'Report title' },
    { name: 'content', label: 'Initial commentary / content', type: 'textarea', required: true },
  ],
  'building:handover': [
    { name: 'toUserId', label: 'Handover to user ID', required: true },
    { name: 'handoverAt', label: 'Handover at', type: 'datetime-local', required: true },
    { name: 'summary', label: 'Handover summary', type: 'textarea', required: true },
  ],
  'strata:notices': [
    { name: 'noticeType', label: 'Notice type', required: true },
    { name: 'title', label: 'Title', required: true },
    { name: 'content', label: 'Notice', type: 'textarea', required: true },
    { name: 'publishedAt', label: 'Publish at', type: 'datetime-local' },
    { name: 'expiresAt', label: 'Expires at', type: 'datetime-local' },
  ],
  'resident:issues-requests': [
    { name: 'requestType', label: 'Request type', required: true },
    { name: 'category', label: 'Category' },
    { name: 'urgency', label: 'Urgency' },
    { name: 'description', label: 'Describe the issue or request', type: 'textarea', required: true },
    { name: 'accessPermission', label: 'Management may access if required', type: 'checkbox' },
    { name: 'accessInstructions', label: 'Access instructions', type: 'textarea' },
  ],
  'resident:bookings': [
    { name: 'propertyId', label: 'Property ID', required: true },
    { name: 'unitId', label: 'Unit ID' },
    { name: 'moveType', label: 'Move type', required: true },
    { name: 'startAt', label: 'Start', type: 'datetime-local', required: true },
    { name: 'endAt', label: 'End', type: 'datetime-local', required: true },
    { name: 'specialRequirements', label: 'Special requirements', type: 'textarea' },
  ],
  'resident:access-keys': [
    { name: 'unitId', label: 'Unit ID', required: true },
    { name: 'requestType', label: 'Request type', required: true },
    { name: 'deviceTypeRequested', label: 'Device type', required: true },
    { name: 'quantityRequested', label: 'Quantity', type: 'number' },
    { name: 'requestReason', label: 'Reason', type: 'textarea' },
  ],
  'resident:messages': [
    { name: 'subject', label: 'Subject', required: true },
    { name: 'linkedEntityType', label: 'Related record type', required: true },
    { name: 'linkedEntityId', label: 'Related record ID', required: true },
  ],
  'contractor:check-in-out': [
    { name: 'visitorName', label: 'Attendee name', required: true },
    { name: 'purpose', label: 'Purpose', type: 'textarea', required: true },
    { name: 'workOrderId', label: 'Work order ID' },
    { name: 'areaAccessed', label: 'Area accessed' },
    { name: 'vehicleRegistration', label: 'Vehicle registration' },
    { name: 'siteRulesAcknowledged', label: 'Site rules acknowledged', type: 'checkbox', required: true },
  ],
};

export function effectivePortalCreateFields(portalId: PortalId, feature: PortalFeatureDefinition): readonly PortalCreateField[] {
  return FORMS[`${portalId}:${feature.slug}`] ?? feature.createFields ?? [];
}
