import { apiRequest } from '../apiClient';

export interface PropertyHistoryObservation { reportId:string; reportVersionId:string; reportType:string; inspectionDate?:string; lifecycleStatus:string; areaId:string; areaName:string; canonicalAreaDefinitionId?:string; canonicalAreaDefinitionVersion?:number; componentId:string; componentName:string; canonicalComponentDefinitionId?:string; canonicalComponentDefinitionVersion?:number; canonicalAreaComponentRuleId?:string; canonicalAreaComponentRuleVersion?:number; conditionCategory:string; cleanlinessCategory:string; workingStatus:string; testStatus:string; commentary:string; defects:string[]; evidencePhotoIds:string[]; versionCreatedAt?:string; }
export interface PropertyHistoryMaintenance { id:string; title:string; category:string; priority:string; status:string; sourceReportId?:string; sourceReportVersionId?:string; sourceAreaId?:string; sourceComponentId?:string; sourceCanonicalAreaDefinitionId?:string; sourceCanonicalAreaDefinitionVersion?:number; sourceCanonicalComponentDefinitionId?:string; sourceCanonicalComponentDefinitionVersion?:number; sourceEvidenceIds:string[]; completionEvidenceIds:string[]; createdAt?:string; updatedAt?:string; closedAt?:string; }
export interface PropertyComponentHistory { stableKey:string; identityMode:'canonical_occurrence'|'canonical_semantic'|'legacy_instance'; areaId:string; areaName:string; canonicalAreaDefinitionId?:string; componentId:string; componentName:string; canonicalComponentDefinitionId?:string; observations:PropertyHistoryObservation[]; maintenance:PropertyHistoryMaintenance[]; }
export interface PropertyHistory { propertyId:string; propertyAddress:string; identityMode?:'canonical_first'; inspections:Array<{ reportId:string; reportType:string; inspectionDate?:string; lifecycleStatus:string; currentVersionId?:string; templateId?:string; templateVersion?:number; propertyLayoutVersionId?:string; structureResolutionVersion?:number; canonicalCatalogueId?:string; canonicalCatalogueVersion?:number; immutableVersionCount:number; sourceMaintenanceItemIds?:string[]; }>; components:PropertyComponentHistory[]; maintenance:PropertyHistoryMaintenance[]; generatedAt:string; }

export async function getPropertyHistory(propertyId: string, agencyId?: string): Promise<PropertyHistory> {
  return apiRequest<PropertyHistory>(agencyId, `/api/v1/properties/${encodeURIComponent(propertyId)}/history`);
}
