import { createHash } from 'node:crypto';
import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { applicationDefault, getApps, initializeApp } from 'firebase-admin/app';
import { getFirestore, FieldValue } from 'firebase-admin/firestore';

interface SyncTask { taskId: string; agencyId: string; connectionId: string; syncRunId: string; direction: 'import' | 'publish'; resource: string; entityId?: string; }
interface Connection { id: string; provider: string; status: string; credentialReference?: string; configuration?: Record<string, unknown>; }

const ALLOWED_IMPORTS = new Set(['clients', 'properties', 'tenants', 'tenancies', 'operational_status']);
const ALLOWED_PUBLISH = new Set(['inspection_completed', 'report_finalised', 'maintenance_updated', 'document_completed']);
const FORBIDDEN_FINANCIAL_RESOURCES = new Set(['transactions', 'payments', 'receipts', 'trust_ledger', 'rent_ledger', 'bank_accounts', 'disbursements', 'reconciliations']);

function app() { return getApps()[0] ?? initializeApp({ credential: applicationDefault() }); }
function json(res: ServerResponse, status: number, value: unknown) { res.writeHead(status, { 'content-type': 'application/json', 'cache-control': 'no-store' }); res.end(JSON.stringify(value)); }
async function requestBody(req: IncomingMessage): Promise<unknown> { const chunks: Buffer[] = []; for await (const chunk of req) chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)); return chunks.length ? JSON.parse(Buffer.concat(chunks).toString('utf8')) : {}; }
function decode(input: unknown): SyncTask { if (!input || typeof input !== 'object') throw new Error('Integration task is required.'); const value = input as Record<string, unknown>; const message = value.message && typeof value.message === 'object' ? value.message as Record<string, unknown> : undefined; const payload = message?.data ? JSON.parse(Buffer.from(String(message.data), 'base64').toString('utf8')) as Record<string, unknown> : value; const direction = String(payload.direction); if (direction !== 'import' && direction !== 'publish') throw new Error('direction must be import or publish.'); return { taskId: String(payload.taskId || ''), agencyId: String(payload.agencyId || ''), connectionId: String(payload.connectionId || ''), syncRunId: String(payload.syncRunId || ''), direction, resource: String(payload.resource || ''), entityId: typeof payload.entityId === 'string' ? payload.entityId : undefined }; }
async function metadataToken(): Promise<string> { const response = await fetch('http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token', { headers: { 'Metadata-Flavor': 'Google' }, signal: AbortSignal.timeout(5_000) }); if (!response.ok) throw new Error(`Metadata token request failed with ${response.status}.`); const payload = await response.json() as { access_token?: string }; if (!payload.access_token) throw new Error('Metadata token was missing.'); return payload.access_token; }
async function secret(reference: string | undefined): Promise<string | undefined> { if (!reference) return undefined; if (process.env.NODE_ENV === 'test') return process.env.PMS_TEST_TOKEN; const projectId = process.env.GOOGLE_CLOUD_PROJECT?.trim(); if (!projectId) throw new Error('GOOGLE_CLOUD_PROJECT is required to resolve PMS credentials.'); const token = await metadataToken(); const name = reference.includes('/secrets/') ? reference : `projects/${projectId}/secrets/${reference}/versions/latest`; const response = await fetch(`https://secretmanager.googleapis.com/v1/${name}:access`, { headers: { authorization: `Bearer ${token}` }, signal: AbortSignal.timeout(8_000) }); if (!response.ok) throw new Error(`PMS credential resolution failed with ${response.status}.`); const payload = await response.json() as { payload?: { data?: string } }; return payload.payload?.data ? Buffer.from(payload.payload.data, 'base64').toString('utf8') : undefined; }
function pathFor(connection: Connection, direction: 'import' | 'publish', resource: string): string { const config = connection.configuration || {}; const key = `${direction}_${resource}_path`; const path = typeof config[key] === 'string' ? String(config[key]) : ''; if (!path) throw new Error(`Connection does not define ${key}.`); return path; }
function baseUrl(connection: Connection): string { const value = String(connection.configuration?.baseUrl || '').replace(/\/$/u, ''); if (!/^https:\/\//u.test(value)) throw new Error('PMS connection baseUrl must use HTTPS.'); return value; }
function localCollection(resource: string): string { return ({ clients: 'clients', properties: 'properties', tenants: 'tenants', tenancies: 'tenancies', operational_status: 'externalOperationalStatuses' } as Record<string, string>)[resource] || resource; }
function externalId(record: Record<string, unknown>): string { const value = record.id ?? record.externalId ?? record.uuid ?? record.reference; if (typeof value !== 'string' && typeof value !== 'number') throw new Error('Imported PMS record did not expose a stable external identifier.'); return String(value); }
function cleanOperationalRecord(resource: string, record: Record<string, unknown>): Record<string, unknown> { if (resource !== 'operational_status') return record; return { entityType: record.entityType, entityId: record.entityId, sourceSystem: record.sourceSystem, rentStatus: record.rentStatus, bondStatus: record.bondStatus, invoiceStatus: record.invoiceStatus, retrievedAt: record.retrievedAt || new Date().toISOString() }; }

async function perform(task: SyncTask) {
  if (!task.taskId || !task.agencyId || !task.connectionId || !task.syncRunId || !task.resource) throw new Error('taskId, agencyId, connectionId, syncRunId and resource are required.');
  if (FORBIDDEN_FINANCIAL_RESOURCES.has(task.resource)) throw new Error(`Financial resource ${task.resource} is outside the ProInspect licensing boundary.`);
  if (task.direction === 'import' && !ALLOWED_IMPORTS.has(task.resource)) throw new Error(`Import resource ${task.resource} is not allow-listed.`);
  if (task.direction === 'publish' && !ALLOWED_PUBLISH.has(task.resource)) throw new Error(`Publish resource ${task.resource} is not allow-listed.`);
  const db = getFirestore(app()); const connectionRef = db.doc(`agencies/${task.agencyId}/pmsConnections/${task.connectionId}`); const connectionSnap = await connectionRef.get(); if (!connectionSnap.exists) throw new Error('PMS connection was not found.'); const connection = { id: connectionSnap.id, ...connectionSnap.data() } as Connection; if (connection.status !== 'connected') throw new Error('PMS connection is not connected.');
  const runRef = db.doc(`agencies/${task.agencyId}/integrationSyncRuns/${task.syncRunId}`); const now = new Date().toISOString(); await runRef.set({ status: 'running', startedAt: now, updatedAt: now }, { merge: true });
  const credential = await secret(connection.credentialReference); const endpoint = new URL(pathFor(connection, task.direction, task.resource), `${baseUrl(connection)}/`); const headers: Record<string, string> = { accept: 'application/json', 'content-type': 'application/json' }; if (credential) headers.authorization = credential.startsWith('Bearer ') ? credential : `Bearer ${credential}`;
  let processed = 0; let failed = 0;
  try {
    if (task.direction === 'import') {
      const response = await fetch(endpoint, { headers, signal: AbortSignal.timeout(30_000) }); if (!response.ok) throw new Error(`PMS import failed with ${response.status}.`); const payload = await response.json() as unknown; const rows = Array.isArray(payload) ? payload : payload && typeof payload === 'object' && Array.isArray((payload as Record<string, unknown>).items) ? (payload as { items: unknown[] }).items : [];
      const collection = localCollection(task.resource);
      for (const raw of rows) {
        try { if (!raw || typeof raw !== 'object' || Array.isArray(raw)) throw new Error('Record must be an object.'); const record = cleanOperationalRecord(task.resource, raw as Record<string, unknown>); const extId = externalId(record); const mappingId = createHash('sha256').update(`${connection.provider}:${task.resource}:${extId}`).digest('hex'); const mappingRef = db.doc(`agencies/${task.agencyId}/externalReferences/${mappingId}`); const mapping = await mappingRef.get(); const entityId = mapping.exists ? String(mapping.data()?.entityId) : `pms-${mappingId.slice(0, 24)}`; await db.doc(`agencies/${task.agencyId}/${collection}/${entityId}`).set({ ...record, id: entityId, agencyId: task.agencyId, sourceSystem: connection.provider, sourceExternalId: extId, updatedAt: new Date().toISOString(), ...(mapping.exists ? {} : { createdAt: new Date().toISOString() }) }, { merge: true }); await mappingRef.set({ id: mappingId, agencyId: task.agencyId, provider: connection.provider, entityType: task.resource.replace(/s$/u, ''), entityId, externalId: extId, lastSyncedAt: new Date().toISOString(), updatedAt: new Date().toISOString(), createdAt: mapping.exists ? mapping.data()?.createdAt || new Date().toISOString() : new Date().toISOString(), version: FieldValue.increment(1) }, { merge: true }); processed += 1; } catch { failed += 1; }
      }
    } else {
      if (!task.entityId) throw new Error('entityId is required for publish tasks.'); const sourceCollection = task.resource === 'inspection_completed' ? 'inspectionJobs' : task.resource === 'report_finalised' ? 'reports' : task.resource === 'maintenance_updated' ? 'maintenanceItems' : 'documentPackets'; const source = await db.doc(`agencies/${task.agencyId}/${sourceCollection}/${task.entityId}`).get(); if (!source.exists) throw new Error('Publish source record was not found.'); const response = await fetch(endpoint, { method: 'POST', headers, body: JSON.stringify({ event: task.resource, entityId: task.entityId, data: source.data() }), signal: AbortSignal.timeout(30_000) }); if (!response.ok) throw new Error(`PMS publish failed with ${response.status}.`); processed = 1;
    }
    const completedAt = new Date().toISOString(); await runRef.set({ status: failed ? 'partially_succeeded' : 'succeeded', processed, failed, completedAt, updatedAt: completedAt }, { merge: true }); await connectionRef.set({ lastSuccessfulSyncAt: completedAt, lastAttemptedSyncAt: completedAt, lastErrorCode: null, lastErrorMessage: null, updatedAt: completedAt }, { merge: true }); await db.doc(`agencies/${task.agencyId}/taskOutbox/${task.taskId}`).set({ status: 'completed', completedAt, result: { processed, failed }, updatedAt: completedAt }, { merge: true }); return { processed, failed };
  } catch (error) { const message = error instanceof Error ? error.message : String(error); const failedAt = new Date().toISOString(); await runRef.set({ status: 'failed', processed, failed: failed + 1, error: message, completedAt: failedAt, updatedAt: failedAt }, { merge: true }); await connectionRef.set({ status: 'attention_required', lastAttemptedSyncAt: failedAt, lastErrorCode: 'SYNC_FAILED', lastErrorMessage: message, updatedAt: failedAt }, { merge: true }); await db.doc(`agencies/${task.agencyId}/taskOutbox/${task.taskId}`).set({ status: 'failed', error: message, updatedAt: failedAt }, { merge: true }); throw error; }
}

const server = createServer(async (req, res) => { try { if (req.method === 'GET' && req.url === '/health') return json(res, 200, { status: 'ok', service: 'integration-worker' }); if (req.method !== 'POST') return json(res, 405, { error: 'Method not allowed' }); return json(res, 200, { data: await perform(decode(await requestBody(req))) }); } catch (error) { console.error(JSON.stringify({ level: 'error', message: 'integration-worker.failed', error: error instanceof Error ? error.message : String(error) })); return json(res, 500, { error: error instanceof Error ? error.message : String(error) }); } });
server.listen(Number(process.env.PORT || 8080), '0.0.0.0');
