import { createHash } from 'node:crypto';
import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { createAppwriteServerServices, loadAppwriteServerConfig } from '@pcr/appwrite-server';

interface SyncTask { taskId: string; agencyId: string; connectionId: string; syncRunId: string; direction: 'import' | 'publish'; resource: string; entityId?: string; }
interface ConnectionRow { $id: string; agencyId: string; provider: string; status: string; credentialReference?: string; configuration?: string; lastSuccessfulAt?: string; lastAttemptedAt?: string; }
type Row = Record<string, unknown> & { $id: string; agencyId?: string };

const services = createAppwriteServerServices(loadAppwriteServerConfig());
const SYSTEM_ACTOR = 'system:integration-worker';
const ALLOWED_IMPORTS = new Set(['clients', 'properties', 'tenants', 'tenancies']);
const ALLOWED_PUBLISH = new Set(['inspection_completed', 'report_finalised', 'maintenance_updated', 'document_completed']);
const FORBIDDEN_FINANCIAL_RESOURCES = new Set(['transactions', 'payments', 'receipts', 'trust_ledger', 'rent_ledger', 'bank_accounts', 'disbursements', 'reconciliations']);

function json(res: ServerResponse, status: number, value: unknown) { res.writeHead(status, { 'content-type': 'application/json', 'cache-control': 'no-store' }); res.end(JSON.stringify(value)); }
async function requestBody(req: IncomingMessage): Promise<unknown> { const chunks: Buffer[] = []; for await (const chunk of req) chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)); return chunks.length ? JSON.parse(Buffer.concat(chunks).toString('utf8')) : {}; }
function decode(input: unknown): SyncTask { if (!input || typeof input !== 'object') throw new Error('Integration task is required.'); const value = input as Record<string, unknown>; const message = value.message && typeof value.message === 'object' ? value.message as Record<string, unknown> : undefined; const payload = message?.data ? JSON.parse(Buffer.from(String(message.data), 'base64').toString('utf8')) as Record<string, unknown> : value; const direction = String(payload.direction); if (direction !== 'import' && direction !== 'publish') throw new Error('direction must be import or publish.'); return { taskId: String(payload.taskId || ''), agencyId: String(payload.agencyId || ''), connectionId: String(payload.connectionId || ''), syncRunId: String(payload.syncRunId || ''), direction, resource: String(payload.resource || ''), entityId: typeof payload.entityId === 'string' ? payload.entityId : undefined }; }
function appwriteCode(error: unknown): number | undefined { return error && typeof error === 'object' && 'code' in error ? Number((error as { code?: unknown }).code) : undefined; }
function nowIso(): string { return new Date().toISOString(); }
function deterministicId(prefix: string, value: string): string { return `${prefix}${createHash('sha256').update(value).digest('hex').slice(0, 35)}`; }
function cleanRow(row: Row): Record<string, unknown> { return Object.fromEntries(Object.entries(row).filter(([key]) => !key.startsWith('$'))); }
function configuration(row: ConnectionRow): Record<string, unknown> { if (!row.configuration) return {}; try { const parsed = JSON.parse(row.configuration) as unknown; return parsed && typeof parsed === 'object' && !Array.isArray(parsed) ? parsed as Record<string, unknown> : {}; } catch { throw new Error('Integration connection configuration is not valid JSON.'); } }
function baseData(agencyId: string, status = 'active', existing?: Row): Record<string, unknown> { const now = nowIso(); return { agencyId, status, createdAt: typeof existing?.createdAt === 'string' ? existing.createdAt : now, updatedAt: now, createdBy: typeof existing?.createdBy === 'string' ? existing.createdBy : SYSTEM_ACTOR, updatedBy: SYSTEM_ACTOR }; }
async function getScoped(tableId: string, rowId: string, agencyId: string): Promise<Row | undefined> { try { const row = await services.tables.getRow({ databaseId: services.databaseId, tableId, rowId }) as unknown as Row; return row.agencyId === agencyId ? row : undefined; } catch (error) { if (appwriteCode(error) === 404) return undefined; throw error; } }
async function upsertScoped(tableId: string, rowId: string, agencyId: string, data: Record<string, unknown>): Promise<Row> { const existing = await getScoped(tableId, rowId, agencyId); if (existing) return services.tables.updateRow({ databaseId: services.databaseId, tableId, rowId, data: { ...data, updatedAt: nowIso(), updatedBy: SYSTEM_ACTOR } }) as unknown as Row; return services.tables.createRow({ databaseId: services.databaseId, tableId, rowId, permissions: [], data: { ...baseData(agencyId), ...data } }) as unknown as Row; }
async function updateScoped(tableId: string, rowId: string, agencyId: string, data: Record<string, unknown>): Promise<void> { const existing = await getScoped(tableId, rowId, agencyId); if (!existing) return; await services.tables.updateRow({ databaseId: services.databaseId, tableId, rowId, data: { ...data, updatedAt: nowIso(), updatedBy: SYSTEM_ACTOR } }); }

async function metadataToken(): Promise<string> { const response = await fetch('http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token', { headers: { 'Metadata-Flavor': 'Google' }, signal: AbortSignal.timeout(5_000) }); if (!response.ok) throw new Error(`Metadata token request failed with ${response.status}.`); const payload = await response.json() as { access_token?: string }; if (!payload.access_token) throw new Error('Metadata token was missing.'); return payload.access_token; }
async function secret(reference: string | undefined): Promise<string | undefined> { if (!reference) return undefined; if (process.env.NODE_ENV === 'test') return process.env.PMS_TEST_TOKEN; const projectId = process.env.GOOGLE_CLOUD_PROJECT?.trim(); if (!projectId) throw new Error('GOOGLE_CLOUD_PROJECT is required to resolve PMS credentials.'); const token = await metadataToken(); const name = reference.includes('/secrets/') ? reference : `projects/${projectId}/secrets/${reference}/versions/latest`; const response = await fetch(`https://secretmanager.googleapis.com/v1/${name}:access`, { headers: { authorization: `Bearer ${token}` }, signal: AbortSignal.timeout(8_000) }); if (!response.ok) throw new Error(`PMS credential resolution failed with ${response.status}.`); const payload = await response.json() as { payload?: { data?: string } }; return payload.payload?.data ? Buffer.from(payload.payload.data, 'base64').toString('utf8') : undefined; }
function pathFor(connection: ConnectionRow, direction: 'import' | 'publish', resource: string): string { const config = configuration(connection); const key = `${direction}_${resource}_path`; const path = typeof config[key] === 'string' ? String(config[key]) : ''; if (!path) throw new Error(`Connection does not define ${key}.`); return path; }
function baseUrl(connection: ConnectionRow): string { const value = String(configuration(connection).baseUrl || '').replace(/\/$/u, ''); if (!/^https:\/\//u.test(value)) throw new Error('PMS connection baseUrl must use HTTPS.'); return value; }
function externalId(record: Record<string, unknown>): string { const value = record.id ?? record.externalId ?? record.uuid ?? record.reference; if (typeof value !== 'string' && typeof value !== 'number') throw new Error('Imported PMS record did not expose a stable external identifier.'); return String(value); }
function stringValue(record: Record<string, unknown>, ...keys: string[]): string | undefined { for (const key of keys) { const value = record[key]; if (typeof value === 'string' && value.trim()) return value.trim(); } return undefined; }
function requiredString(record: Record<string, unknown>, label: string, ...keys: string[]): string { const value = stringValue(record, ...keys); if (!value) throw new Error(`Imported ${label} is required.`); return value; }
function targetId(provider: string, resource: string, external: string): string { return deterministicId('p', `${provider}:${resource}:${external}`); }
function targetReference(provider: string, resource: string, external: unknown): string | undefined { if (typeof external !== 'string' && typeof external !== 'number') return undefined; return targetId(provider, resource, String(external)); }

function transformImport(connection: ConnectionRow, task: SyncTask, record: Record<string, unknown>): { tableId: string; rowId: string; data: Record<string, unknown> } {
  const extId = externalId(record); const rowId = targetId(connection.provider, task.resource, extId); const source = { legacySystem: connection.provider, legacyId: extId };
  if (task.resource === 'clients') {
    const name = requiredString(record, 'client name', 'name', 'legalName', 'tradingName');
    return { tableId: 'clients', rowId, data: { ...source, name, legalName: stringValue(record, 'legalName'), tradingName: stringValue(record, 'tradingName'), abn: stringValue(record, 'abn'), clientType: stringValue(record, 'clientType'), accountType: stringValue(record, 'accountType'), billingMethod: stringValue(record, 'billingMethod'), billingEmail: stringValue(record, 'billingEmail', 'email'), externalReferences: JSON.stringify({ provider: connection.provider, externalId: extId }) } };
  }
  if (task.resource === 'properties') {
    return { tableId: 'properties', rowId, data: { ...source, clientId: targetReference(connection.provider, 'clients', record.clientId ?? record.clientExternalId), propertyType: requiredString(record, 'propertyType', 'propertyType', 'type'), propertyUse: requiredString(record, 'propertyUse', 'propertyUse', 'use'), ownershipStructure: requiredString(record, 'ownershipStructure', 'ownershipStructure', 'ownership'), streetAddress: requiredString(record, 'streetAddress', 'streetAddress', 'address'), suburb: stringValue(record, 'suburb'), state: stringValue(record, 'state'), postcode: stringValue(record, 'postcode'), country: stringValue(record, 'country'), lotNumber: stringValue(record, 'lotNumber'), unitNumber: stringValue(record, 'unitNumber'), buildingName: stringValue(record, 'buildingName'), strataPlanNumber: stringValue(record, 'strataPlanNumber'), externalReference: extId } };
  }
  if (task.resource === 'tenants') {
    return { tableId: 'tenants', rowId, data: { ...source, displayName: requiredString(record, 'tenant displayName', 'displayName', 'fullName', 'name'), email: stringValue(record, 'email'), phone: stringValue(record, 'phone'), personId: stringValue(record, 'personId'), userId: stringValue(record, 'userId') } };
  }
  if (task.resource === 'tenancies') {
    const propertyId = targetReference(connection.provider, 'properties', record.propertyId ?? record.propertyExternalId); if (!propertyId) throw new Error('Imported tenancy propertyId is required.');
    return { tableId: 'tenancies', rowId, data: { ...source, propertyId, primaryTenantId: targetReference(connection.provider, 'tenants', record.primaryTenantId ?? record.tenantId ?? record.tenantExternalId), lifecycleStatus: requiredString(record, 'tenancy lifecycleStatus', 'lifecycleStatus', 'status'), startDate: stringValue(record, 'startDate', 'leaseStartDate'), endDate: stringValue(record, 'endDate', 'leaseEndDate'), noticeDate: stringValue(record, 'noticeDate'), terms: typeof record.terms === 'string' ? record.terms : record.terms ? JSON.stringify(record.terms) : undefined } };
  }
  throw new Error(`Import resource ${task.resource} has no approved Appwrite transform.`);
}

function publishTable(resource: string): string { const value = ({ inspection_completed: 'inspection_jobs', report_finalised: 'reports', maintenance_updated: 'maintenance_items', document_completed: 'tenancy_documents' } as Record<string, string>)[resource]; if (!value) throw new Error(`Publish resource ${resource} has no Appwrite source table.`); return value; }
async function syncEvent(task: SyncTask, provider: string, status: string, attempts: number, error?: string): Promise<string> { const rowId = deterministicId('s', `${task.agencyId}:${task.syncRunId}`); const existing = await getScoped('integration_events', rowId, task.agencyId); const firstReceivedAt = typeof existing?.firstReceivedAt === 'string' ? existing.firstReceivedAt : nowIso(); await upsertScoped('integration_events', rowId, task.agencyId, { provider, eventType: `pms.${task.direction}.${task.resource}`, externalEventId: task.syncRunId, deduplicationId: task.syncRunId, processingStatus: status, attempts, firstReceivedAt, lastAttemptedAt: nowIso(), ...(status === 'processed' ? { processedAt: nowIso() } : {}), ...(error ? { errorState: error } : {}) }); return rowId; }
async function exception(task: SyncTask, provider: string, message: string): Promise<void> { const rowId = deterministicId('x', `${task.taskId}:${Date.now()}`); await services.tables.createRow({ databaseId: services.databaseId, tableId: 'integration_exceptions', rowId, permissions: [], data: { ...baseData(task.agencyId, 'open'), provider, category: 'pms_sync', severity: 'error', entityType: task.resource, entityId: task.entityId || task.syncRunId, detail: message } }); }

async function perform(task: SyncTask) {
  if (!task.taskId || !task.agencyId || !task.connectionId || !task.syncRunId || !task.resource) throw new Error('taskId, agencyId, connectionId, syncRunId and resource are required.');
  if (FORBIDDEN_FINANCIAL_RESOURCES.has(task.resource)) throw new Error(`Financial resource ${task.resource} is outside the ProInspect licensing boundary.`);
  if (task.direction === 'import' && task.resource === 'operational_status') throw new Error('operational_status import is blocked until an approved canonical Appwrite mapping is defined.');
  if (task.direction === 'import' && !ALLOWED_IMPORTS.has(task.resource)) throw new Error(`Import resource ${task.resource} is not allow-listed.`);
  if (task.direction === 'publish' && !ALLOWED_PUBLISH.has(task.resource)) throw new Error(`Publish resource ${task.resource} is not allow-listed.`);
  const rawConnection = await getScoped('integration_connections', task.connectionId, task.agencyId); if (!rawConnection) throw new Error('PMS connection was not found.'); const connection = rawConnection as unknown as ConnectionRow; if (connection.status !== 'connected') throw new Error('PMS connection is not connected.');
  await syncEvent(task, connection.provider, 'processing', 1);
  await updateScoped('integration_outbox', task.taskId, task.agencyId, { deliveryStatus: 'processing', lastAttemptedAt: nowIso() });
  const credential = await secret(connection.credentialReference); const endpoint = new URL(pathFor(connection, task.direction, task.resource), `${baseUrl(connection)}/`); const headers: Record<string, string> = { accept: 'application/json', 'content-type': 'application/json' }; if (credential) headers.authorization = credential.startsWith('Bearer ') ? credential : `Bearer ${credential}`;
  let processed = 0; let failed = 0;
  try {
    if (task.direction === 'import') {
      const response = await fetch(endpoint, { headers, signal: AbortSignal.timeout(30_000) }); if (!response.ok) throw new Error(`PMS import failed with ${response.status}.`); const payload = await response.json() as unknown; const rows = Array.isArray(payload) ? payload : payload && typeof payload === 'object' && Array.isArray((payload as Record<string, unknown>).items) ? (payload as { items: unknown[] }).items : [];
      for (const raw of rows) { try { if (!raw || typeof raw !== 'object' || Array.isArray(raw)) throw new Error('Record must be an object.'); const transformed = transformImport(connection, task, raw as Record<string, unknown>); const existing = await getScoped(transformed.tableId, transformed.rowId, task.agencyId); await upsertScoped(transformed.tableId, transformed.rowId, task.agencyId, { ...transformed.data, status: stringValue(raw as Record<string, unknown>, 'status') || String(existing?.status || 'active') }); processed += 1; } catch (error) { failed += 1; await exception(task, connection.provider, error instanceof Error ? error.message : String(error)); } }
    } else {
      if (!task.entityId) throw new Error('entityId is required for publish tasks.'); const source = await getScoped(publishTable(task.resource), task.entityId, task.agencyId); if (!source) throw new Error('Publish source record was not found.'); const response = await fetch(endpoint, { method: 'POST', headers, body: JSON.stringify({ event: task.resource, entityId: task.entityId, data: cleanRow(source) }), signal: AbortSignal.timeout(30_000) }); if (!response.ok) throw new Error(`PMS publish failed with ${response.status}.`); processed = 1;
    }
    const completedAt = nowIso(); await syncEvent(task, connection.provider, failed ? 'partially_processed' : 'processed', 1, failed ? `${failed} imported record(s) failed validation.` : undefined); await updateScoped('integration_connections', task.connectionId, task.agencyId, { status: failed ? 'attention_required' : 'connected', lastSuccessfulAt: completedAt, lastAttemptedAt: completedAt, lastError: failed ? `${failed} imported record(s) failed validation.` : '' }); await updateScoped('integration_outbox', task.taskId, task.agencyId, { deliveryStatus: failed ? 'partially_completed' : 'completed', lastAttemptedAt: completedAt }); return { processed, failed };
  } catch (error) { const message = error instanceof Error ? error.message : String(error); const failedAt = nowIso(); await syncEvent(task, connection.provider, 'failed', 1, message); await updateScoped('integration_connections', task.connectionId, task.agencyId, { status: 'attention_required', lastAttemptedAt: failedAt, lastError: message }); await updateScoped('integration_outbox', task.taskId, task.agencyId, { deliveryStatus: 'failed', lastAttemptedAt: failedAt }); await exception(task, connection.provider, message); throw error; }
}

const server = createServer(async (req, res) => { try { if (req.method === 'GET' && req.url === '/health') return json(res, 200, { status: 'ok', service: 'integration-worker', authority: 'appwrite' }); if (req.method !== 'POST') return json(res, 405, { error: 'Method not allowed' }); return json(res, 200, { data: await perform(decode(await requestBody(req))) }); } catch (error) { console.error(JSON.stringify({ level: 'error', message: 'integration-worker.failed', error: error instanceof Error ? error.message : String(error) })); return json(res, 500, { error: error instanceof Error ? error.message : String(error) }); } });
server.listen(Number(process.env.PORT || 8080), '0.0.0.0');
