import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,mkdirSync,writeFileSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve } from 'node:path';
import { inspectWorkerAuthority } from '../actions/runtime-authority.mjs';
import { buildConfiguration,runtimeArguments } from '../actions/google.mjs';

test('worker authority scanner rejects Firebase runtime dependencies/imports',()=>{const base=mkdtempSync(resolve(tmpdir(),'pi-authority-'));try{mkdirSync(resolve(base,'apps/pdf-worker/src'),{recursive:true});writeFileSync(resolve(base,'apps/pdf-worker/package.json'),JSON.stringify({dependencies:{'firebase-admin':'1.0.0'}}));writeFileSync(resolve(base,'apps/pdf-worker/src/index.ts'),"import { getFirestore } from 'firebase-admin/firestore';\n");const report=inspectWorkerAuthority(base,['pdf-worker']);assert.equal(report.pass,false);assert(report.violations.some((v)=>v.reason.includes('firebase-admin')));}finally{rmSync(base,{recursive:true,force:true});}});
test('worker authority scanner accepts Appwrite-only runtime',()=>{const base=mkdtempSync(resolve(tmpdir(),'pi-authority-'));try{mkdirSync(resolve(base,'apps/pdf-worker/src'),{recursive:true});writeFileSync(resolve(base,'apps/pdf-worker/package.json'),JSON.stringify({dependencies:{'@pcr/appwrite-server':'*'}}));writeFileSync(resolve(base,'apps/pdf-worker/src/index.ts'),"import { createAppwriteServerServices } from '@pcr/appwrite-server';\n");assert.equal(inspectWorkerAuthority(base,['pdf-worker']).pass,true);}finally{rmSync(base,{recursive:true,force:true});}});
test('Google build uses the provisioned Cloud Build service account',()=>{const target={projectId:'proinspect-development-gcp',region:'australia-southeast1',imageRepository:'pcr-containers',services:['api']};const build=buildConfiguration(target,'a'.repeat(40));assert.equal(build.serviceAccount,'projects/proinspect-development-gcp/serviceAccounts/cloud-build@proinspect-development-gcp.iam.gserviceaccount.com');});
test('Cloud Run deployment updates rather than clears Terraform service defaults',()=>{const target={google:{environment:'development',projectId:'proinspect-development-gcp',runtimeBindings:{api:{env:{AUTH_PROVIDER:'appwrite',APPWRITE_BACKEND_MODE:'appwrite'},secretRefs:{APPWRITE_API_KEY:'appwrite-api:1'}}}},appwrite:{endpoint:'https://syd.cloud.appwrite.io/v1',projectId:'proinspect-development',databaseId:'proinspect_core'}};const args=runtimeArguments(target,'api','a'.repeat(40));assert(args.includes('--update-env-vars'));assert(args.includes('--update-secrets'));assert(!args.includes('--set-env-vars'));assert(!args.includes('--clear-secrets'));});
